### ISSUE TITLE
IPAdapter weight does not have any effect.

### ISSUE THREAD

**Issue by kvochko** [siliconflow/onediff#1003]
### Describe the bug
When the weight parameter in IPAdapterAdvanced changes, it has no effect on the output image, and does not cause model recompilation.

### Your environment
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

#### OneDiff git commit id
ee5fe704c6af98db3eec08ccaacf461f0f53c8e0

####  OneFlow version info if you have installed oneflow
```
version: 0.9.1.dev20240515+cu122
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```

### How To Reproduce
See the attached ComfyUI workflow. Run once, change weight, run again.

![workflow (69)](https://github.com/siliconflow/onediff/assets/2308830/dd253a27-651c-47e7-bfb2-31d246ec889b)

**Comment by lijunliangTG** [comment]
Now you can try to switch to the``` fix_onediff_comfy_nodes_docs ```branch, where the IPAdapter is working properly.

![image](https://github.com/user-attachments/assets/99d6a53e-b193-4fef-b74e-1ab7882ab515)
![image](https://github.com/user-attachments/assets/d6b4aec6-604f-4149-aac4-fe6ad2b89457)

**Comment by kvochko** [comment]
Confirmed that it works, thank you!
