### ISSUE TITLE
test_torch2of_demo problem

### ISSUE THREAD

**Issue by Shiroha-Key** [siliconflow/onediff#1004]
### Describe the bug
执行test_torch2of_demo报错：
FAILED test_torch2of_demo.py::TestTorch2ofDemo::test_torch2of_demo - AttributeError: 'oneflow._oneflow_internal.nn.graph.CNNGraph' object has no attribute 'get_runtime_var_states'
### Your environment
onediff                   1.1.0
oneflow                   1.0.0.dev20240708+cu118
torch                     2.1.2+cu118
torchaudio                2.1.2+cu118
torchdiffeq               0.2.4
torchsde                  0.2.6
torchvision               0.16.2+cu118
#### OS 
操作系统名称： posix
操作系统详细信息： Linux
操作系统版本： 4.19.127-0419127-generic
操作系统的位数： ('64bit', '')
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
####  OneFlow version info if you have installed oneflow
5ce6e2a497a0ec050225707c786cdeca5181afee
Run `python -m oneflow --doctor` and paste it here.
$ python -m oneflow --doctor
libibverbs not available, ibv_fork_init skipped
path: ['/root/miniforge3/envs/anime/lib/python3.10/site-packages/oneflow']
version: 1.0.0.dev20240708+cu118
git_commit: 850b4ad
cmake_build_type: Release
rdma: True
mlir: True
### How To Reproduce
Steps to reproduce the behavior(code or script):
python -m pytest test_torch2of_demo.py
### The complete error message
================================================================ test session starts ================================================================
platform linux -- Python 3.10.14, pytest-8.2.2, pluggy-1.5.0
rootdir: /root/picasso/hld@meitu.com/onediff
configfile: pyproject.toml
plugins: xdist-3.6.1, repeat-0.9.3, anyio-4.4.0
collected 1 item                                                                                                                                    

test_torch2of_demo.py F                                                                                                                       [100%]

===================================================================== FAILURES ======================================================================
________________________________________________________ TestTorch2ofDemo.test_torch2of_demo ________________________________________________________

self = <test_torch2of_demo.TestTorch2ofDemo testMethod=test_torch2of_demo>

    def test_torch2of_demo(self):
        # Register PyTorch model to OneDiff
        cls_key = transform_mgr.get_transformed_entity_name(PyTorchModel)
        transform_mgr.update_class_proxies({cls_key: OneFlowModel})
    
        # Compile PyTorch model to OneFlow
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        pytorch_model = PyTorchModel().to(device)
        of_model = oneflow_compile(pytorch_model)
    
        # Verify conversion
        x = torch.randn(4, 4).to(device)
    
        #### 1. Use apply_model method
        y_pt = pytorch_model.apply_model(x)
        y_of = of_model.apply_model(x)
        self.judge_tensor_func(y_pt, y_of)
    
        #### 2. Use __call__ method
        y_pt = pytorch_model(x)
>       y_of = of_model(x)

test_torch2of_demo.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/root/miniforge3/envs/anime/lib/python3.10/site-packages/torch/nn/modules/module.py:1518: in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
/root/miniforge3/envs/anime/lib/python3.10/site-packages/torch/nn/modules/module.py:1581: in _call_impl
    hook_result = hook(self, args, result)
/root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/param_utils.py:171: in forward_generate_constant_folding_info_hook
    generate_constant_folding_info(module)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

deployable_module = MixedOneflowDeployableModule(of PyTorchModel)(
  (linear): Linear(in_features=4, out_features=4, bias=True)
)
torch_module = PyTorchModel(
  (linear): Linear(in_features=4, out_features=4, bias=True)
)

    def generate_constant_folding_info(
        deployable_module, torch_module: torch.nn.Module = None
    ) -> Dict[str, flow.Tensor]:
        removeprefix = lambda ss, prefix: ss[len(prefix) :] if ss.startswith(prefix) else ss
    
        # convert str like 'variable_transpose_model.input_blocks.10.0.in_layers.2.weight_239'
        # to 'input_blocks.10.0.in_layers.2.weight'
        def convert_var_name(s: str, prefix="variable_transpose_"):
            s = removeprefix(s, prefix)
            s = re.sub(r"_[0-9]+$", "", s)
            s = removeprefix(s, "model.")
            return s
    
        from onediff.infer_compiler import DeployableModule
    
        if not isinstance(deployable_module, DeployableModule):
            raise TypeError(
                f"deployable_model must be a DeployableModule, got {type(deployable_module)}"
            )
        if torch_module is None:
            torch_module = deployable_module._torch_module
    
        graph = deployable_module._deployable_module_dpl_graph
        if graph is None:
            raise RuntimeError(f"The graph of deployable_module is not built yet")
    
        result = {
            convert_var_name(k): v
>           for k, v in zip(*graph._c_nn_graph.get_runtime_var_states())
            if k.startswith("variable_transpose_") and v.ndim == 4
        }
E       AttributeError: 'oneflow._oneflow_internal.nn.graph.CNNGraph' object has no attribute 'get_runtime_var_states'

/root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/param_utils.py:108: AttributeError
--------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
(GRAPH:OneflowGraph_0:OneflowGraph) got a new input shape, is compiling a new graph.
(GRAPH:OneflowGraph_0:OneflowGraph) is creating a graph cache with key 3273461422041228023.
(GRAPH:OneflowGraph_0:OneflowGraph) start building graph.
(GRAPH:OneflowGraph_0:OneflowGraph) building graph Done! Cost time: 3.88s.

(GRAPH:OneflowGraph_0:OneflowGraph) start building plan.
                                                                         
(GRAPH:OneflowGraph_0:OneflowGraph) building plan Done! Cost time: 0.04s.

--------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------
DEBUG [2024-07-10 01:21:43] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'test_torch2of_demo.PyTorchModel': <class 'test_torch2of_demo.OneFlowModel'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.Attention': <class 'register_diffusers.attention_processor_oflow.Attention'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.AttnProcessor': <class 'register_diffusers.attention_processor_oflow.AttnProcessor'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.AttnProcessor2_0': <class 'register_diffusers.attention_processor_oflow.AttnProcessor'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.LoRAAttnProcessor2_0': <class 'register_diffusers.attention_processor_oflow.LoRAAttnProcessor2_0'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.resnet.SpatioTemporalResBlock': <class 'register_diffusers.spatio_temporal_oflow.SpatioTemporalResBlock'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.autoencoders.autoencoder_kl_temporal_decoder.TemporalDecoder': <class 'register_diffusers.spatio_temporal_oflow.TemporalDecoder'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.transformer_temporal.TransformerSpatioTemporalModel': <class 'register_diffusers.spatio_temporal_oflow.TransformerSpatioTemporalModel'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention.TemporalBasicTransformerBlock': <class 'register_diffusers.spatio_temporal_oflow.TemporalBasicTransformerBlock'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.unet_spatio_temporal_condition.UNetSpatioTemporalConditionModel': <class 'register_diffusers.spatio_temporal_oflow.UNetSpatioTemporalConditionModel'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.transformer_2d.Transformer2DModel': <class 'register_diffusers.transformer_2d_oflow.Transformer2DModel'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.unet_2d_condition.UNet2DConditionModel': <class 'register_diffusers.unet_2d_condition_oflow.UNet2DConditionModel'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.unet_2d_blocks.AttnUpBlock2D': <class 'register_diffusers.unet_2d_blocks_oflow.AttnUpBlock2D'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.unet_2d_blocks.CrossAttnUpBlock2D': <class 'register_diffusers.unet_2d_blocks_oflow.CrossAttnUpBlock2D'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.unet_2d_blocks.UpBlock2D': <class 'register_diffusers.unet_2d_blocks_oflow.UpBlock2D'>}

DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.upsampling.Upsample2D': <class 'register_diffusers.resnet_oflow.Upsample2D'>}

DEBUG [2024-07-10 01:22:02] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/dual_module.py:29 - Convert <class 'test_torch2of_demo.PyTorchModel'> ...
INFO [2024-07-10 01:22:02] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/builtin_transform.py:51 - instance_name: PyTorchModel transformed to  <class 'test_torch2of_demo.OneFlowModel'>
DEBUG [2024-07-10 01:22:02] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/dual_module.py:31 - Convert <class 'test_torch2of_demo.PyTorchModel'> done!
INFO [2024-07-10 01:22:02] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/graph.py:14 - Building a graph for <class 'test_torch2of_demo.OneFlowModel'> ...
INFO [2024-07-10 01:22:06] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/param_utils.py:170 - generate constant folding info
================================================================= warnings summary ==================================================================
tests/convert_torch_to_of/test_torch2of_demo.py::TestTorch2ofDemo::test_torch2of_demo
  /root/miniforge3/envs/anime/lib/python3.10/site-packages/oneflow/_dynamo/__init__.py:30: UserWarning: The oneflow._dynamo.allow_in_graph interface is just to align the torch._dynamo.allow_in_graph interface and has no practical significance.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================== short test summary info ==============================================================
FAILED test_torch2of_demo.py::TestTorch2ofDemo::test_torch2of_demo - AttributeError: 'oneflow._oneflow_internal.nn.graph.CNNGraph' object has no attribute 'get_runtime_var_states'

**Comment by Shiroha-Key** [comment]
hammmm

**Comment by HrLi97** [comment]
> ### Describe the bug
> 执行test_torch2of_demo报错： FAILED test_torch2of_demo.py::TestTorch2ofDemo::test_torch2of_demo - AttributeError: 'oneflow._oneflow_internal.nn.graph.CNNGraph' object has no attribute 'get_runtime_var_states'
> 
> #### A clear and concise description of what the bug is.
> ### Your environment
> onediff 1.1.0 oneflow 1.0.0.dev20240708+cu118 torch 2.1.2+cu118 torchaudio 2.1.2+cu118 torchdiffeq 0.2.4 torchsde 0.2.6 torchvision 0.16.2+cu118
> 
> #### OS
> 操作系统名称： posix 操作系统详细信息： Linux 操作系统版本： 4.19.127-0419127-generic 操作系统的位数： ('64bit', '') No LSB modules are available. Distributor ID: Ubuntu Description: Ubuntu 18.04.4 LTS Release: 18.04 Codename: bionic
> 
> #### OneDiff git commit id
> #### OneFlow version info if you have installed oneflow
> [5ce6e2a](https://github.com/siliconflow/onediff/commit/5ce6e2a497a0ec050225707c786cdeca5181afee) Run `python -m oneflow --doctor` and paste it here. $ python -m oneflow --doctor libibverbs not available, ibv_fork_init skipped path: ['/root/miniforge3/envs/anime/lib/python3.10/site-packages/oneflow'] version: 1.0.0.dev20240708+cu118 git_commit: 850b4ad cmake_build_type: Release rdma: True mlir: True
> 
> ### How To Reproduce
> Steps to reproduce the behavior(code or script): python -m pytest test_torch2of_demo.py
> 
> ### The complete error message
> ================================================================ test session starts ================================================================ platform linux -- Python 3.10.14, pytest-8.2.2, pluggy-1.5.0 rootdir: /root/picasso/[hld@meitu.com](mailto:hld@meitu.com)/onediff configfile: pyproject.toml plugins: xdist-3.6.1, repeat-0.9.3, anyio-4.4.0 collected 1 item
> 
> test_torch2of_demo.py F [100%]
> 
> ===================================================================== FAILURES ====================================================================== ________________________________________________________ TestTorch2ofDemo.test_torch2of_demo ________________________________________________________
> 
> self = <test_torch2of_demo.TestTorch2ofDemo testMethod=test_torch2of_demo>
> 
> ```
> def test_torch2of_demo(self):
>     # Register PyTorch model to OneDiff
>     cls_key = transform_mgr.get_transformed_entity_name(PyTorchModel)
>     transform_mgr.update_class_proxies({cls_key: OneFlowModel})
> 
>     # Compile PyTorch model to OneFlow
>     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
>     pytorch_model = PyTorchModel().to(device)
>     of_model = oneflow_compile(pytorch_model)
> 
>     # Verify conversion
>     x = torch.randn(4, 4).to(device)
> 
>     #### 1. Use apply_model method
>     y_pt = pytorch_model.apply_model(x)
>     y_of = of_model.apply_model(x)
>     self.judge_tensor_func(y_pt, y_of)
> 
>     #### 2. Use __call__ method
>     y_pt = pytorch_model(x)
> ```
> 
> > ```
> >   y_of = of_model(x)
> > ```
> 
> test_torch2of_demo.py:72:
> 
> /root/miniforge3/envs/anime/lib/python3.10/site-packages/torch/nn/modules/module.py:1518: in _wrapped_call_impl return self._call_impl(*args, **kwargs) /root/miniforge3/envs/anime/lib/python3.10/site-packages/torch/nn/modules/module.py:1581: in _call_impl hook_result = hook(self, args, result) /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/param_utils.py:171: in forward_generate_constant_folding_info_hook generate_constant_folding_info(module)
> 
> deployable_module = MixedOneflowDeployableModule(of PyTorchModel)( (linear): Linear(in_features=4, out_features=4, bias=True) ) torch_module = PyTorchModel( (linear): Linear(in_features=4, out_features=4, bias=True) )
> 
> ```
> def generate_constant_folding_info(
>     deployable_module, torch_module: torch.nn.Module = None
> ) -> Dict[str, flow.Tensor]:
>     removeprefix = lambda ss, prefix: ss[len(prefix) :] if ss.startswith(prefix) else ss
> 
>     # convert str like 'variable_transpose_model.input_blocks.10.0.in_layers.2.weight_239'
>     # to 'input_blocks.10.0.in_layers.2.weight'
>     def convert_var_name(s: str, prefix="variable_transpose_"):
>         s = removeprefix(s, prefix)
>         s = re.sub(r"_[0-9]+$", "", s)
>         s = removeprefix(s, "model.")
>         return s
> 
>     from onediff.infer_compiler import DeployableModule
> 
>     if not isinstance(deployable_module, DeployableModule):
>         raise TypeError(
>             f"deployable_model must be a DeployableModule, got {type(deployable_module)}"
>         )
>     if torch_module is None:
>         torch_module = deployable_module._torch_module
> 
>     graph = deployable_module._deployable_module_dpl_graph
>     if graph is None:
>         raise RuntimeError(f"The graph of deployable_module is not built yet")
> 
>     result = {
>         convert_var_name(k): v
> ```
> 
> > ```
> >       for k, v in zip(*graph._c_nn_graph.get_runtime_var_states())
> > ```
> 
> ```
>         if k.startswith("variable_transpose_") and v.ndim == 4
>     }
> ```
> 
> E AttributeError: 'oneflow._oneflow_internal.nn.graph.CNNGraph' object has no attribute 'get_runtime_var_states'
> 
> /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/param_utils.py:108: AttributeError --------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------- (GRAPH:OneflowGraph_0:OneflowGraph) got a new input shape, is compiling a new graph. (GRAPH:OneflowGraph_0:OneflowGraph) is creating a graph cache with key 3273461422041228023. (GRAPH:OneflowGraph_0:OneflowGraph) start building graph. (GRAPH:OneflowGraph_0:OneflowGraph) building graph Done! Cost time: 3.88s.
> 
> (GRAPH:OneflowGraph_0:OneflowGraph) start building plan.
> 
> (GRAPH:OneflowGraph_0:OneflowGraph) building plan Done! Cost time: 0.04s.
> 
> --------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------- DEBUG [2024-07-10 01:21:43] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'test_torch2of_demo.PyTorchModel': <class 'test_torch2of_demo.OneFlowModel'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.attention_processor.Attention': <class 'register_diffusers.attention_processor_oflow.Attention'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.attention_processor.AttnProcessor': <class 'register_diffusers.attention_processor_oflow.AttnProcessor'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.attention_processor.AttnProcessor2_0': <class 'register_diffusers.attention_processor_oflow.AttnProcessor'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.attention_processor.LoRAAttnProcessor2_0': <class 'register_diffusers.attention_processor_oflow.LoRAAttnProcessor2_0'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.resnet.SpatioTemporalResBlock': <class 'register_diffusers.spatio_temporal_oflow.SpatioTemporalResBlock'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.autoencoders.autoencoder_kl_temporal_decoder.TemporalDecoder': <class 'register_diffusers.spatio_temporal_oflow.TemporalDecoder'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.transformer_temporal.TransformerSpatioTemporalModel': <class 'register_diffusers.spatio_temporal_oflow.TransformerSpatioTemporalModel'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.attention.TemporalBasicTransformerBlock': <class 'register_diffusers.spatio_temporal_oflow.TemporalBasicTransformerBlock'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.unet_spatio_temporal_condition.UNetSpatioTemporalConditionModel': <class 'register_diffusers.spatio_temporal_oflow.UNetSpatioTemporalConditionModel'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.transformer_2d.Transformer2DModel': <class 'register_diffusers.transformer_2d_oflow.Transformer2DModel'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.unet_2d_condition.UNet2DConditionModel': <class 'register_diffusers.unet_2d_condition_oflow.UNet2DConditionModel'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.unet_2d_blocks.AttnUpBlock2D': <class 'register_diffusers.unet_2d_blocks_oflow.AttnUpBlock2D'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.unet_2d_blocks.CrossAttnUpBlock2D': <class 'register_diffusers.unet_2d_blocks_oflow.CrossAttnUpBlock2D'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.unet_2d_blocks.UpBlock2D': <class 'register_diffusers.unet_2d_blocks_oflow.UpBlock2D'>}
> 
> DEBUG [2024-07-10 01:22:01] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/manager.py:56 - Updated class proxies: len(class_proxy_dict)=1 {'diffusers.models.upsampling.Upsample2D': <class 'register_diffusers.resnet_oflow.Upsample2D'>}
> 
> DEBUG [2024-07-10 01:22:02] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/dual_module.py:29 - Convert <class 'test_torch2of_demo.PyTorchModel'> ... INFO [2024-07-10 01:22:02] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/transform/builtin_transform.py:51 - instance_name: PyTorchModel transformed to <class 'test_torch2of_demo.OneFlowModel'> DEBUG [2024-07-10 01:22:02] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/dual_module.py:31 - Convert <class 'test_torch2of_demo.PyTorchModel'> done! INFO [2024-07-10 01:22:02] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/graph.py:14 - Building a graph for <class 'test_torch2of_demo.OneFlowModel'> ... INFO [2024-07-10 01:22:06] /root/miniforge3/envs/anime/lib/python3.10/site-packages/onediff/infer_compiler/backends/oneflow/param_utils.py:170 - generate constant folding info ================================================================= warnings summary ================================================================== tests/convert_torch_to_of/test_torch2of_demo.py::TestTorch2ofDemo::test_torch2of_demo /root/miniforge3/envs/anime/lib/python3.10/site-packages/oneflow/_dynamo/**init**.py:30: UserWarning: The oneflow._dynamo.allow_in_graph interface is just to align the torch._dynamo.allow_in_graph interface and has no practical significance. warnings.warn(
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ============================================================== short test summary info ============================================================== FAILED test_torch2of_demo.py::TestTorch2ofDemo::test_torch2of_demo - AttributeError: 'oneflow._oneflow_internal.nn.graph.CNNGraph' object has no attribute 'get_runtime_var_states'
> 
> ### Additional context
> Add any other context about the problem here.

？？？

**Comment by HrLi97** [comment]
怎么解决的呢请问？
