### ISSUE TITLE
Can I somehow test the enterprise version with my custom SDXL model?

### ISSUE THREAD

**Issue by haritowa** [siliconflow/onediff#1008]
I want to test correctness and inference speed

**Comment by strint** [comment]
Have you successfully run onediff with your custom SDXL model?

> enterprise version with custom model

enterprise version is mainly quantized for the moment, and we found it only suitable for a very static model, which mean you can't do Lora switching or model updating. 

And each model needs a quantized one so enterprise version only suit for a very static model with a lot of traffic.

**Comment by haritowa** [comment]
Got it, thanks. I'll stick to the CE then
