### ISSUE TITLE
custom model(unet) with nexfort

### ISSUE THREAD

**Issue by Shiroha-Key** [siliconflow/onediff#1011]
如何安装支持torch2.1的nexfort版本？又或是还没有推出？
默认pip install支持torch2.3 但我在文档中看到有支持2.4 2.2 2.1三个版本的相关文字

**Comment by strint** [comment]
> 如何安装支持torch2.1的nexfort版本？又或是还没有推出？ 
是没有推出 2.1 的支持。

因为 nexfort 内部使用了 torch 里面比较新的功能，所以和 torch 的 2.3 + 的版本兼容（当前我们测试的主要是 2.3 和 2.4）

@Shiroha-Key

**Comment by Shiroha-Key** [comment]
谢谢你的回答 我还有另一个问题，目前版本如何编译加速自定义SDXL Unet模型？因为我发现没有相关的教程我在尝试编译自定义unet模型时触发了和https://github.com/siliconflow/onediff/issues/824 一模一样的报错，看到你的回答是等待onediff1.1，也就是推荐使用nexfort编译，但我在https://github.com/siliconflow/onediff/issues/1001这篇issue发现nexfort目前还没有测试过SD模型 ，所以暂时也不考虑尝试nexfort，想请教一下824那个报错的产生原因以及是否有相应的解决方案？ @strint

**Comment by strint** [comment]
> 谢谢你的回答 我还有另一个问题，目前版本如何编译加速自定义SDXL Unet模型？因为我发现没有相关的教程我在尝试编译自定义unet模型时触发了和#824 一模一样的报错，看到你的回答是等待onediff1.1，也就是推荐使用nexfort编译，但我在 #1001 这篇issue发现nexfort目前还没有测试过SD模型 ，所以暂时也不考虑尝试nexfort，想请教一下824那个报错的产生原因以及是否有相应的解决方案？ @strint

@Shiroha-Key nexfort + sd 模型（unet结构）已经发布了例子，可以参考 https://github.com/siliconflow/onediff/pull/998

**Comment by Shiroha-Key** [comment]
我的环境是(torch2.1+cuda11.8）暂时还迁移不到支持nexfort编译的环境（torch2.3+cuda12.1）;w;

**Comment by strint** [comment]
> torch2.1

 torch2.1 里面的编译功能对动态 shape 等支持都不好，所以 nexfort 依赖了更高的版本

**Comment by marigoold** [comment]
> 谢谢你的回答 我还有另一个问题，目前版本如何编译加速自定义SDXL Unet模型？因为我发现没有相关的教程我在尝试编译自定义unet模型时触发了和#824 一模一样的报错，看到你的回答是等待onediff1.1，也就是推荐使用nexfort编译，但我在 #1001 这篇issue发现nexfort目前还没有测试过SD模型 ，所以暂时也不考虑尝试nexfort，想请教一下824那个报错的产生原因以及是否有相应的解决方案？ @strint

您这里自定义的 unet 是啥样的？OneDiff 的 oneflow 后段写了一些常见 UNet 的转换，对于其他类型的 UNet 可能得增加一些转换规则

**Comment by strint** [comment]
当前我们计划支持的最低 torch 版本是 2.3 ，因为低于这个版本很多基础编译功能不完善。
