### ISSUE TITLE
Recompile oneflow module ...

### ISSUE THREAD

**Issue by liyandong001** [siliconflow/onediff#1015]
#### A clear and concise description of what the bug is.
warmup指定num_images_per_prompt=1，后面推理num_images_per_prompt=2，会触发重新编译。

#### OS 
ubuntu22.04

####  OneFlow version info if you have installed oneflow
Run `python -m oneflow --doctor` and paste it here.
path: ['/usr/local/lib/python3.10/dist-packages/oneflow']
version: 0.9.1.dev20240515+cu118
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):
self.pipe.unet = oneflow_compile(self.pipe.unet)
self.pipe.controlnet = oneflow_compile(self.pipe.controlnet)
self.pipe.vae = oneflow_compile(self.pipe.vae)
load_and_fuse_lora(self.pipe, self.pcm_path)

self.pipe(
            "xxxxx",
            negative_prompt=self.negative_prompt,
            image=control_image,
            num_inference_steps=4,
            guidance_scale=self.guidance_scale,
            num_images_per_prompt=1,
            width=self.resolution,
            height=self.resolution,
            controlnet_conditioning_scale=self.controlnet_conditioning_scale,
            generator=self.generator
        )

self.pipe(
            "xxxxx",
            negative_prompt=self.negative_prompt,
            image=control_image,
            num_inference_steps=4,
            guidance_scale=self.guidance_scale,
            num_images_per_prompt=2， ########################
            width=self.resolution,
            height=self.resolution,
            controlnet_conditioning_scale=self.controlnet_conditioning_scale,
            generator=self.generator
        )

### The complete error message
[ERROR](GRAPH:OneflowGraph_8:OneflowGraph) building graph got error.
ERROR [2024-07-16 06:30:05] /usr/local/lib/python3.10/dist-packages/onediff/infer_compiler/backends/oneflow/deployable_module.py:38 - Exception in forward: e=Exception('job name: OneflowGraph_8 already exist\n  File "oneflow/core/job/job_build_and_infer_ctx_mgr.cpp", line 32, in OpenJobBuildAndInferCtx\n    CHECK_OR_RETURN(job_name2infer_ctx_.find(job_name) == job_name2infer_ctx_.end())\nError Type: oneflow.ErrorProto.job_name_exist_error')
WARNING [2024-07-16 06:30:05] /usr/local/lib/python3.10/dist-packages/onediff/infer_compiler/backends/oneflow/deployable_module.py:39 - Recompile oneflow module ...

**Comment by strint** [comment]
> num_images_per_prompt=2

保持 num_images_per_prompt=1 不会报错？

**Comment by liyandong001** [comment]
对，不会报错。重新编译之后又不会报错，就是触发重新编译的请求会报错，是不是编译的时候不支持动态shape&nbsp;


闰土
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaoyu ***@***.***&gt;; 
发送时间: 2024年7月16日(星期二) 下午2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siliconflow/onediff] Recompile oneflow module ... (Issue #1015)














  
num_images_per_prompt=2
  
保持 num_images_per_prompt=1 不会报错？

**Comment by strint** [comment]
> 对，不会报错。重新编译之后又不会报错，就是触发重新编译的请求会报错，是不是编译的时候不支持动态shape

这里看起来涉及的动态的 batch size，支持是不太全面

**Comment by liyandong001** [comment]
但是我跑你们官方的demo好像没问题呀，https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/examples/text_to_image_sdxl.py。请问优化用的是MLIR吗

**Comment by liyandong001** [comment]
模型不一样

**Comment by strint** [comment]
> 但是我跑你们官方的demo好像没问题呀，https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/examples/text_to_image_sdxl.py

不同的模型都需要专门适配，为了支持动态分辨率，是需要做针对性的代码改写的

> 请问优化用的是MLIR吗

是有用

**Comment by strint** [comment]
@liyandong001 另外如果是自定义模型，为了减少适配工作，可以使用 nexfort 后端。 参考 https://github.com/siliconflow/onediff/tree/main/onediff_diffusers_extensions/examples/sdxl#run-with-compilation
