### ISSUE TITLE
oneflow update

### ISSUE THREAD

**Issue by lukiod** [siliconflow/onediff#1028]
####  OneFlow version info if you have installed oneflow
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

### Additional context
![image](https://github.com/user-attachments/assets/cce637c1-e3d1-4831-90c9-c055d2eee4f7)

**Comment by strint** [comment]
are you using pip to install oneflow?

Please follow this to update oneflow: https://github.com/siliconflow/onediff?tab=readme-ov-file#oneflow

**Comment by strint** [comment]
@lukiod  Please paste the full error message in text format so we can know more about it.

**Comment by lukiod** [comment]
> @lukiod Please paste the full error message in text format so we can know more about it.

The issue is now solved

**Comment by strint** [comment]
> > @lukiod Please paste the full error message in text format so we can know more about it.
> 
> The issue is now solved

How do you fix this?

**Comment by lukiod** [comment]
No idea it got fixed and i didn't try to configure it due to the moral code "if it works than don't touch it "

**Comment by lukiod** [comment]
@strint  would it be possible to have your discord or other things in the Github So that user can connect with you in urgency or so .

**Comment by strint** [comment]
> @strint would it be possible to have your discord or other things in the Github So that user can connect with you in urgency or so .

discord: https://github.com/siliconflow/onediff?tab=readme-ov-file#community-and-support
