### ISSUE TITLE
diffusers0.29动态分辨率切换报错

### ISSUE THREAD

**Issue by lovemay3** [siliconflow/onediff#1033]
#### OneDiff git commit id 
onediff1.1.0

####  OneFlow version info if you have installed oneflow
Run `python -m oneflow --doctor` and paste it here.
diffusers0.29，oneflow0.9.1.dev20240515+cu118

### How To Reproduce
Steps to reproduce the behavior(code or script):

### Additional context

![image](https://github.com/user-attachments/assets/a5861253-3a82-4494-bbe3-6d60d308bb44)
![image](https://github.com/user-attachments/assets/e017f6d1-cd10-434f-97f1-d0a96c42d99d)

**Comment by strint** [comment]
@lovemay3 Fixed with https://github.com/siliconflow/onediff/pull/1037
