### ISSUE TITLE
[Bug] unet + Controlnet compile fail

### ISSUE THREAD

**Issue by Shiroha-Key** [siliconflow/onediff#1067]
### Your current environment information

python -m onediff.utils.collect_env
/root/miniforge3/envs/py310/bin/python: Error while finding module specification for 'onediff.utils.collect_env' (ModuleNotFoundError: No module named 'onediff.utils')
我使用的是企业版
onediff                   1.0.0.dev1              
onediffx                  1.0.0.dev0              
oneflow                   0.9.1+cu118.git.unknown

### 🐛 Describe the bug

https://gist.github.com/Shiroha-Key/586e2d2312041bbf6c85d1a41b1baa5b
主要是不太明白为什么会oom，我之前量化后的模型也就占用19g左右 添加了这个Controlnet的patch之后就爆了。

**Comment by Shiroha-Key** [comment]
Has anyone seen my issue? :3

**Comment by strint** [comment]
看起来是个自定义的 unet 组合 controlnet？

**Comment by Shiroha-Key** [comment]
> 看起来是个自定义的 unet 组合 controlnet？

是的 顺便我申请了你的qq好友 看到的话能通过一下详聊么

**Comment by strint** [comment]
> > 看起来是个自定义的 unet 组合 controlnet？

自定义模型，我们推荐新的编译接口 nexfort，参考：
- https://github.com/siliconflow/onediff/tree/main/src/onediff/infer_compiler
- https://github.com/siliconflow/onediff/issues/1057

> 是的 顺便我申请了你的qq好友 看到的话能通过一下详聊么

私聊请使用这： contact@siliconflow.com

**Comment by strint** [comment]
> 我试了nexfort的mode:02模式 感觉编译时间太长了 一次要几乎半小时 换一个视频还需要重新编译，有没有办法能够提高编译速度？

https://github.com/siliconflow/onediff/tree/main/src/onediff/infer_compiler#compilation-cache-to-speed-up-recompilation

新增了编译缓存，可以试用下。第一次编译后，后面可以加载编译缓存。

**Comment by Shiroha-Key** [comment]
谢谢 我看一下

**Comment by Shiroha-Key** [comment]
如果我要将"inductor.optimize_linear_epilogue": False和“mode”:"02"结合一起用 是该怎么写配置
像这样？
options = {
        "options": {
            "inductor.optimize_linear_epilogue": False,
        },
        "mode": "max-optimize:max-autotune:low-precision:cache-all",
        "dynamic": True, # 如果你需要动态分辨率，就加上这个
    }

**Comment by strint** [comment]
> 如果我要将"inductor.optimize_linear_epilogue": False和“mode”:"02"结合一起用 是该怎么写配置 像这样？ options = { "options": { "inductor.optimize_linear_epilogue": False, }, "mode": "max-optimize:max-autotune:low-precision:cache-all", "dynamic": True, # 如果你需要动态分辨率，就加上这个 }

没错

**Comment by Shiroha-Key** [comment]
那么关于nexfort 对自定义模型的量化有参考手册吗？

**Comment by strint** [comment]
> 那么关于nexfort 对自定义模型的量化有参考手册吗？ 我只看到使用onediffx对pipeline量化的手册 好像在#919 看到了一些实现，但我的onediff版本好像还没实现 onediff 1.2.1.dev14

量化因为适用的范围还不太宽，比如和 lora 切换的结合还有挑战。所以现在是作为保留功能在内部使用。

**Comment by Shiroha-Key** [comment]
嗯嗯 如果我只想做简单的对linear量化 可以先试用吗？

**Comment by strint** [comment]
> 嗯嗯 如果我只想做简单的对linear量化 可以先试用吗？

量化这块因为需要比较细致的效果调试、评估，所以我们还没释放出来的计划。

**Comment by Shiroha-Key** [comment]
谢谢你的回复，我了解了

**Comment by Shiroha-Key** [comment]
抱歉还有一点问题就是 nexfort首次编译的时间太长了 大概在20～30分钟左右 
我想问的就是 编译后这个状态可以存下来吗？，下次启动就不需要再花那么长的时间编译。

**Comment by Shiroha-Key** [comment]
例如像oneflow后端那样使用save_Graph 进行离线编译在线加载，或是其他可行方法？

**Comment by Shiroha-Key** [comment]
转到https://github.com/siliconflow/onediff/issues/1088 继续

**Comment by Milor123** [comment]
guys, I have this issue, with python 3.12 in manjaro, I am using your custom CUDA 12.1 For NA/EU users
@Shiroha-Key 
```
Traceback (most recent call last):
  File "/home/noe/Documentos/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/noe/Documentos/ComfyUI/custom_nodes/onediff_comfy_nodes/__init__.py", line 2, in <module>
    from onediff.utils.import_utils import is_nexfort_available, is_oneflow_available
ModuleNotFoundError: No module named 'onediff.utils'

Cannot import /home/noe/Documentos/ComfyUI/custom_nodes/onediff_comfy_nodes module for custom nodes: No module named 'onediff.utils'
```
