### ISSUE TITLE
webui首次开启onediff后，Lora不生效

### ISSUE THREAD

**Issue by frc99** [siliconflow/onediff#1141]
1、onediff==1.2.1.dev28 ,oneflow==0.9.1.dev20241019+cu118 目前仍然存在这个问题，首次编译完Lora不生效，添加环境变量export ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION=0仍然不生效。

_Originally posted by @frc99 in https://github.com/siliconflow/onediff/issues/574#issuecomment-2472784089_

2、Lora粘连问题，如果上一次请求使用了lora A，那么下一次请求使用lora B 不生效，仍然是lora A的效果

---
我想1、2都源于一个问题，webui onediff extensions 在使用了controlnet后，lora不再生效

**Comment by frc99** [comment]
是不是因为lora加载发生在unet hook之后...

**Comment by frc99** [comment]
- 能正常切换lora的情况：不加controlnet，此时在Lora插件load_network函数打出的结果 ：
sdmodel type <class 'onediff.infer_compiler.backends.oneflow.deployable_module.get_mixed_deployable_module.<locals>.MixedOneflowDeployableModule'>
- 存在Lora粘连情况： 加controlnet，此时在Lora插件load_network函数打出的结果 ：
sdmodel type <class 'ldm.modules.diffusionmodules.openaimodel.UNetModel'>
是否是因为sd_models此时并没有替换，因此此时lora加载到的是原来的model，但生图时用的是替换过oneflow model。

**Comment by todochenxi** [comment]
Please post your code.

**Comment by frc99** [comment]
我解决了
