### ISSUE TITLE
What is the easiest way to use deep-cache using the OneDiff's SDK?

### ISSUE THREAD

**Issue by isidentical** [siliconflow/onediff#441]
I was trying to update [stable-diffusion-benchmarks](https://github.com/fal-ai/stable-diffusion-benchmarks) repository we have to include a test for OneFlow, but even when using the latest cu121 binaries (v=794a56cc787217f46b21f5cbc84f65295664b82c/oneflow-0.9.1) and the tip of this repo, all I can get is ~12it/s (which is great, but obviously far from the deepcache comfy version of 23it/s).

**Comment by strint** [comment]
> I was trying to update [stable-diffusion-benchmarks](https://github.com/fal-ai/stable-diffusion-benchmarks) repository we have to include a test for OneFlow, but even when using the latest cu121 binaries (v=794a56cc787217f46b21f5cbc84f65295664b82c/oneflow-0.9.1) and the tip of this repo, all I can get is ~12it/s (which is great, but obviously far from the deepcache comfy version of 23it/s).

We only provided deepcache for comfyui for now.  Later we will provide the pipeline.

You can try deepcache pipeline without onediff in https://github.com/horseee/DeepCache

**Comment by hjchen2** [comment]
[stable-diffusion-benchmarks](https://github.com/fal-ai/stable-diffusion-benchmarks) is a very good project. But I found that the speed tested by stable-diffusion-benchmarks is calculated by the end-to-end time and the number of iterations, which is not consistent with the real UNet iteration speed, because the VAE of oneflow has not been compiled. You can try to add the following code to make VAE to be compiled, 
```python
pipe.vae = oneflow_compile(pipe.vae)
```

**Comment by isidentical** [comment]
Thanks @hjchen2, and yes, that's something we are aware of (and mention in the readme) and want to potnetially fix:

> All the timings here are end to end, and reflects the time it takes to go from a single prompt to a decoded image. We are planning to make the benchmarking more granular and provide details and comparisons between each components (text encoder, VAE, and most importantly UNET) in the future, but for now, some of the results might not linearly scale with the number of inference steps since cost of certain components are one-time only.

**Comment by strint** [comment]
> We only provided deepcache for comfyui for now. Later we will provide the pipeline.

@isidentical  The deepcache pipeline merged: https://github.com/siliconflow/onediff/pull/450

**Comment by strint** [comment]
@isidentical has successfully run deepcache pipeline.
