### ISSUE TITLE
How to install on comfyui portable?

### ISSUE THREAD

**Issue by Charuru** [siliconflow/onediff#447]
How to install on comfyui portable? Is a comfyui manager install possible?

**Comment by strint** [comment]
Do you mean  [portable standalone build for Windows](https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#windows)

For using windows please refer to: https://github.com/Oneflow-Inc/onediff/tree/main?tab=readme-ov-file#install-from-source-or-using-in-docker

We only support Linux and NVIDIA GPUs for the moment. If you want to use OneDiff on Windows, please use it under WSL.

**Comment by Charuru** [comment]
Is windows in the plans or won't be a thing for the foreseeable future?

**Comment by strint** [comment]
> Is windows in the plans or won't be a thing for the foreseeable future?

According to the recent feedback, we are thinking about it.
