### ISSUE TITLE
How to add projects to SD

### ISSUE THREAD

**Issue by zsh123abc** [siliconflow/onediff#448]

**Comment by strint** [comment]
Here is the installation guide: https://github.com/siliconflow/onediff?tab=readme-ov-file#install-from-source

**Comment by strint** [comment]
Here is the installation guide: https://github.com/siliconflow/onediff?tab=readme-ov-file#install-from-source

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
