### ISSUE TITLE
image_to_vedio pipeline_stable_video_diffusion.py image_encoder error

### ISSUE THREAD

**Issue by Honey-666** [siliconflow/onediff#466]
我在使用example中的 image_to_video.py 文件时出现了 image_encoder的错误我不知道是少传入了什么

  File "/home/ubuntu/aidazuo/dazuovenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/aidazuo/dazuovenv/lib/python3.10/site-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 421, in __call__
    image_embeddings = self._encode_image(image, device, num_videos_per_prompt, do_classifier_free_guidance)
  File "/home/ubuntu/aidazuo/dazuovenv/lib/python3.10/site-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 140, in _encode_image
    image_embeddings = image_embeddings.unsqueeze(1)
NotImplementedError: Error: <No error message>

**Comment by strint** [comment]
请填下下面的信息以方便我们了解这个问题：


### Your environment
#### OS 

#### OneDiff git commit id

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

### The complete error message

**Comment by Honey-666** [comment]
> 请填下下面的信息以方便我们了解这个问题：
> ### Your environment
> #### OS
> Ubuntu 18.04.4 LTS
diffusers==0.24.0
torch==2.1.0
transformers==4.33.1
 

> #### OneDiff git commit id

> https://github.com/siliconflow/onediff/pull/454

> #### OneFlow version info
> 
> Run `python -m oneflow --doctor` and paste it here.

> path: ['/home/ubuntu/aidazuo/dazuovenv/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20231225+cu121
git_commit: 16189c9
cmake_build_type: Release
rdma: True
mlir: True

> ### How To Reproduce
> Steps to reproduce the behavior(code or script):
python image_to_video.py --model /home/ubuntu/aidazuo/models/Stable-diffusion/stable-video-diffusion-img2vid-xt/ --variant fp16 --input-image /home/ubuntu/aidazuo/ai-painting/20231225-152441.jpg
> ### The complete error message
> Traceback (most recent call last):
  File "/home/ubuntu/aidazuo/onediff/examples/image_to_video.py", line 251, in <module>
    main()
  File "/home/ubuntu/aidazuo/onediff/examples/image_to_video.py", line 224, in main
    model(**get_kwarg_inputs())
  File "/home/ubuntu/aidazuo/dazuovenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/aidazuo/dazuovenv/lib/python3.10/site-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 421, in __call__
    image_embeddings = self._encode_image(image, device, num_videos_per_prompt, do_classifier_free_guidance)
  File "/home/ubuntu/aidazuo/dazuovenv/lib/python3.10/site-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 140, in _encode_image
    image_embeddings = image_embeddings.unsqueeze(1)
NotImplementedError: Error: <No error message>

**Comment by strint** [comment]
@chengzeyi

**Comment by chengzeyi** [comment]
是因为image_encoder输出的dataclass没有被正确解析，需要升级到最新的oneflow代码。

**Comment by Honey-666** [comment]
> 是因为image_encoder输出的dataclass没有被正确解析，需要升级到最新的oneflow代码。

好的非常感觉，但是我执行   python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118命令
或者执行  pip install -U  oneflow  命令都测试不行，我要怎么升级到最近的oneflow库呢？

**Comment by chengzeyi** [comment]
> > 是因为image_encoder输出的dataclass没有被正确解析，需要升级到最新的oneflow代码。
> 
> 好的 非常感谢您的回答，但是我执行 python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118 命令 或者执行 pip install -U oneflow 命令都测试不行，我要怎么升级到最新的oneflow库呢？

这个特性刚刚开发出来，可能还没有发布。

**Comment by chengzeyi** [comment]
如果比较着急的话，可以先把

```python
    model.image_encoder = oneflow_compile(model.image_encoder)
    model.unet = oneflow_compile(model.unet)
    model.vae.decoder = oneflow_compile(model.vae.decoder)
    model.vae.encoder = oneflow_compile(model.vae.encoder)
```

改成

```python
    model.unet = oneflow_compile(model.unet)
```

**Comment by strint** [comment]
@Honey-666 试下更新

```
python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118 
```

可解决这个问题，对应 oneflow 的：

git_commit: 8669462

**Comment by Honey-666** [comment]
> @Honey-666 试下更新
> 
> ```
> python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118 
> ```
> 
> 可解决这个问题，对应 oneflow 的：
> 
> git_commit: 8669462

我已经执行了该命令，oneflow==0.9.1.dev20231225+cu118，这是我执行后oneflow的版本，他还是不能够工作

**Comment by strint** [comment]
> Run `python -m oneflow --doctor` and paste it here.

@Honey-666  把完整信息贴下，看 git_commit 是不是不对

**Comment by Honey-666** [comment]
> Run `python -m oneflow --doctor` and paste it here.
> 
> @Honey-666 把完整信息贴下，看 git_commit 是不是不对

**Comment by strint** [comment]
> > Run `python -m oneflow --doctor` and paste it here.

@Honey-666 这个看起来还是老的 commit

> git_commit: 16189c9

抱歉，这两天 CI 有改动。新版本包的编译有了延迟。

**Comment by Honey-666** [comment]
> > Run `python -m oneflow --doctor` and paste it here.
> 
> @Honey-666 把完整信息贴下，看 git_commit 是不是不对

这是我执行该命令  `python -m oneflow --doctor`    显示的结果
path: ['/home/ubuntu/aidazuo/dazuovenv/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20231225+cu118
git_commit: 16189c9
cmake_build_type: Release
rdma: True
mlir: True

**Comment by Honey-666** [comment]
> > > Run `python -m oneflow --doctor` and paste it here.
> 
> @Honey-666 这个看起来还是老的 commit
> 
> > git_commit: 16189c9
> 
> 抱歉，这两天 CI 有改动。新版本包的编译有了延迟。

好的  那后续更新后我只需要在重新执行 python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118 该命令即可升级吗？   还是我要通过其他方式去升级？


另外我好像误关闭了该问题是否需要重新开启一个问题呢？

**Comment by strint** [comment]
```
pip uninstall oneflow
python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118
```
@Honey-666 我看已经更新到：
```
c407dc4
```
可以试下，按说可以解决问题了

**Comment by Honey-666** [comment]
> ```
> pip uninstall oneflow
> python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118
> ```
> 
> @Honey-666 我看已经更新到：
> 
> ```
> c407dc4
> ```
> 
> 可以试下，按说可以解决问题了

好的，我已经讲oneflow更新到了最新，并且已经能够测试通过了。非常感谢您的解答
