### ISSUE TITLE
TypeError: scaled_dot_product_attention(): argument 'query' (position 1) must be Tensor, not Tensor

### ISSUE THREAD

**Issue by HydrogenQAQ** [siliconflow/onediff#486]
### Describe the bug
跑i2i任务时，Attention好像跑到torch的分支下了，不是onediff的

#### A clear and concise description of what the bug is.
Traceback (most recent call last):
  File "/root/workspace/onediff/examples/image_to_image.py", line 92, in <module>
    images = pipe(
  File "/home/us/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/workspace/diffusers_roberta_v2/diffusers/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py", line 1162, in __call__
    noise_pred = self.unet(
  File "/root/workspace/onediff/src/onediff/infer_compiler/utils/args_tree_util.py", line 34, in wrapper
    output = func(cls, *mapped_args, **mapped_kwargs)
  File "/root/workspace/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 220, in wrapper
    return func(self, *args, **kwargs)
  File "/root/workspace/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 188, in wrapper
    ret = func(self, *args, **kwargs)
  File "/root/workspace/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 296, in __call__
    output = dpl_graph(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 292, in __call__
    return self._dynamic_input_graph_cache(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/cache.py", line 116, in __call__
    return graph(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 295, in __call__
    self._compile(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 863, in _compile
    return self._compile_new(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 882, in _compile_new
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 1424, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 1572, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/root/workspace/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 389, in build
    return self.model(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/root/workspace/diffusers_roberta_v2/diffusers/src/diffusers/models/unet_2d_condition.py", line 1066, in forward
    sample, res_samples = downsample_block(
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/root/workspace/diffusers_roberta_v2/diffusers/src/diffusers/models/unet_2d_blocks.py", line 1162, in forward
    hidden_states = attn(
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/root/workspace/onediff/src/infer_compiler_registry/register_diffusers/transformer_2d_oflow.py", line 737, in forward
    hidden_states = block(
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/root/workspace/diffusers_roberta_v2/diffusers/src/diffusers/models/attention.py", line 258, in forward
    attn_output = self.attn1(
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/us/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/root/workspace/onediff/src/infer_compiler_registry/register_diffusers/attention_processor_oflow.py", line 364, in forward
    return self.processor(
  File "/root/workspace/diffusers_roberta_v2/diffusers/src/diffusers/models/attention_processor.py", line 1231, in __call__
    hidden_states = F.scaled_dot_product_attention(
TypeError: scaled_dot_product_attention(): argument 'query' (position 1) must be Tensor, not Tensor

#### OS
cuda 12.1, torch 2.0.1, diffusers 0.24.0, oneflow 0.9.1

#### OneDiff git commit id
Version: 0.11.0.dev0

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by strint** [comment]
> File "/root/workspace/diffusers_roberta_v2/diffusers/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py", line 1162, in call

这里有对应的 diffusers pipeline 可以复现问题么？

> File "/root/workspace/diffusers_roberta_v2/diffusers/src/diffusers/models/attention_processor.py", line 1231, in call
hidden_states = F.scaled_dot_product_attention(
TypeError: scaled_dot_product_attention(): argument 'query' (position 1) must be Tensor, not Tensor

看起来这里出现了转换问题，我们需要 pipeline 的 demo 来复现下。

@HydrogenQAQ

**Comment by HydrogenQAQ** [comment]
pipeline和原版的区别在于unet和controlnet加入了encoder_attention_mask信息：
down_block_res_samples, mid_block_res_sample = self.controlnet(
    control_model_input,
    t,
    encoder_hidden_states=controlnet_prompt_embeds,
    controlnet_cond=control_image,
    conditioning_scale=cond_scale,
    guess_mode=guess_mode,
    encoder_attention_mask=mask,
    return_dict=False,
)

**Comment by HydrogenQAQ** [comment]
我打开oneflow的debug模式，打印了下：
(MODULE:model.down_blocks.0:<class 'diffusers.models.unet_2d_blocks.CrossAttnDownBlock2D'>())
(INPUT:_model.down_blocks.0_input.1.0_hidden_states:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(INPUT:_model.down_blocks.0_input.1.1_temb:tensor(..., device='cuda:0', is_lazy='True', size=(2, 1280),
       dtype=oneflow.float16))
(INPUT:_model.down_blocks.0_input.1.2_encoder_hidden_states:tensor(..., device='cuda:0', is_lazy='True', size=(2, 128, 1024),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0_input.1.3_attention_mask:<class 'NoneType'>)
[WARNING](INPUT:_model.down_blocks.0_input.1.4_cross_attention_kwargs:<class 'NoneType'>)
[WARNING](INPUT:_model.down_blocks.0_input.1.5_encoder_attention_mask:<class 'NoneType'>)



(MODULE:model.down_blocks.0.resnets.0:<class 'diffusers.models.resnet.ResnetBlock2D'>())
(INPUT:_model.down_blocks.0.resnets.0_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(INPUT:_model.down_blocks.0.resnets.0_input.0.1_3:tensor(..., device='cuda:0', is_lazy='True', size=(2, 1280),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.resnets.0_input.1.0_scale:<class 'float'>)


(MODULE:model.down_blocks.0.resnets.0.norm1:<class 'oneflow.nn.modules.normalization.GroupNorm'>(32, 320, eps=1e-05, affine=True))
(INPUT:_model.down_blocks.0.resnets.0.norm1_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(PARAMETER:model.down_blocks.0.resnets.0.norm1.weight:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(PARAMETER:model.down_blocks.0.resnets.0.norm1.bias:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.resnets.0.norm1_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.resnets.0.nonlinearity:<class 'oneflow.nn.modules.activation.SiLU'>())
(INPUT:_model.down_blocks.0.resnets.0.nonlinearity_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(OUTPUT:_model.down_blocks.0.resnets.0.nonlinearity_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.resnets.0.conv1:<class 'diffusers.models.lora.LoRACompatibleConv'>(320, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)))
(INPUT:_model.down_blocks.0.resnets.0.conv1_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.resnets.0.conv1_input.0.1_3:<class 'float'>)
(PARAMETER:model.down_blocks.0.resnets.0.conv1.weight:tensor(..., device='cuda:0', size=(320, 320, 3, 3), dtype=oneflow.float16,
       requires_grad=True))
(PARAMETER:model.down_blocks.0.resnets.0.conv1.bias:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.resnets.0.conv1_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))



(MODULE:model.down_blocks.0.resnets.0.nonlinearity:<class 'oneflow.nn.modules.activation.SiLU'>())
(INPUT:_model.down_blocks.0.resnets.0.nonlinearity_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 1280),
       dtype=oneflow.float16))
(OUTPUT:_model.down_blocks.0.resnets.0.nonlinearity_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 1280),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.resnets.0.time_emb_proj:<class 'diffusers.models.lora.LoRACompatibleLinear'>(in_features=1280, out_features=320, bias=True))
(INPUT:_model.down_blocks.0.resnets.0.time_emb_proj_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 1280),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.resnets.0.time_emb_proj_input.0.1_3:<class 'float'>)
(PARAMETER:model.down_blocks.0.resnets.0.time_emb_proj.weight:tensor(..., device='cuda:0', size=(320, 1280), dtype=oneflow.float16,
       requires_grad=True))
(PARAMETER:model.down_blocks.0.resnets.0.time_emb_proj.bias:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.resnets.0.time_emb_proj_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.resnets.0.norm2:<class 'oneflow.nn.modules.normalization.GroupNorm'>(32, 320, eps=1e-05, affine=True))
(INPUT:_model.down_blocks.0.resnets.0.norm2_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(PARAMETER:model.down_blocks.0.resnets.0.norm2.weight:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(PARAMETER:model.down_blocks.0.resnets.0.norm2.bias:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.resnets.0.norm2_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.resnets.0.nonlinearity:<class 'oneflow.nn.modules.activation.SiLU'>())
(INPUT:_model.down_blocks.0.resnets.0.nonlinearity_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(OUTPUT:_model.down_blocks.0.resnets.0.nonlinearity_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.resnets.0.dropout:<class 'oneflow.nn.modules.dropout.Dropout'>(p=0.0, inplace=False))
(INPUT:_model.down_blocks.0.resnets.0.dropout_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(OUTPUT:_model.down_blocks.0.resnets.0.dropout_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.resnets.0.conv2:<class 'diffusers.models.lora.LoRACompatibleConv'>(320, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)))
(INPUT:_model.down_blocks.0.resnets.0.conv2_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.resnets.0.conv2_input.0.1_3:<class 'float'>)
(PARAMETER:model.down_blocks.0.resnets.0.conv2.weight:tensor(..., device='cuda:0', size=(320, 320, 3, 3), dtype=oneflow.float16,
       requires_grad=True))
(PARAMETER:model.down_blocks.0.resnets.0.conv2.bias:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.resnets.0.conv2_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(OUTPUT:_model.down_blocks.0.resnets.0_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.attentions.0:<class 'register_diffusers.transformer_2d_oflow.Transformer2DModel'>())
(INPUT:_model.down_blocks.0.attentions.0_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(INPUT:_model.down_blocks.0.attentions.0_input.1.0_encoder_hidden_states:tensor(..., device='cuda:0', is_lazy='True', size=(2, 128, 1024),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.attentions.0_input.1.1_cross_attention_kwargs:<class 'NoneType'>)
[WARNING](INPUT:_model.down_blocks.0.attentions.0_input.1.2_attention_mask:<class 'NoneType'>)
[WARNING](INPUT:_model.down_blocks.0.attentions.0_input.1.3_encoder_attention_mask:<class 'NoneType'>)
[WARNING](INPUT:_model.down_blocks.0.attentions.0_input.1.4_return_dict:<class 'bool'>)


(MODULE:model.down_blocks.0.attentions.0.norm:<class 'oneflow.nn.modules.normalization.GroupNorm'>(32, 320, eps=1e-06, affine=True))
(INPUT:_model.down_blocks.0.attentions.0.norm_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
(PARAMETER:model.down_blocks.0.attentions.0.norm.weight:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(PARAMETER:model.down_blocks.0.attentions.0.norm.bias:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.attentions.0.norm_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.attentions.0.proj_in:<class 'diffusers.models.lora.LoRACompatibleConv'>(320, 320, kernel_size=(1, 1), stride=(1, 1)))
(INPUT:_model.down_blocks.0.attentions.0.proj_in_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.attentions.0.proj_in_input.1.0_scale:<class 'float'>)
(PARAMETER:model.down_blocks.0.attentions.0.proj_in.weight:tensor(..., device='cuda:0', size=(320, 320, 1, 1), dtype=oneflow.float16,
       requires_grad=True))
(PARAMETER:model.down_blocks.0.attentions.0.proj_in.bias:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.attentions.0.proj_in_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 320, 64, 64),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.attentions.0.transformer_blocks.0:<class 'diffusers.models.attention.BasicTransformerBlock'>())
(INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0_input.1.0_attention_mask:<class 'NoneType'>)
(INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0_input.1.1_encoder_hidden_states:tensor(..., device='cuda:0', is_lazy='True', size=(2, 128, 1024),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0_input.1.2_encoder_attention_mask:<class 'NoneType'>)
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0_input.1.3_timestep:<class 'NoneType'>)
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0_input.1.4_cross_attention_kwargs:<class 'NoneType'>)
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0_input.1.5_class_labels:<class 'NoneType'>)


(MODULE:model.down_blocks.0.attentions.0.transformer_blocks.0.norm1:<class 'oneflow.nn.modules.normalization.LayerNorm'>((320,), eps=1e-05, elementwise_affine=True))
(INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.norm1_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))
(PARAMETER:model.down_blocks.0.attentions.0.transformer_blocks.0.norm1.weight:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(PARAMETER:model.down_blocks.0.attentions.0.transformer_blocks.0.norm1.bias:tensor(..., device='cuda:0', size=(320,), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.norm1_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.attentions.0.transformer_blocks.0.attn1:<class 'register_diffusers.attention_processor_oflow.Attention'>())
(INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1_input.1.0_encoder_hidden_states:<class 'NoneType'>)
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1_input.1.1_attention_mask:<class 'NoneType'>)


(MODULE:model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_q:<class 'diffusers.models.lora.LoRACompatibleLinear'>(in_features=320, out_features=320, bias=False))
(INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_q_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_q_input.0.1_3:<class 'float'>)
(PARAMETER:model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_q.weight:tensor(..., device='cuda:0', size=(320, 320), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_q_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))


(MODULE:model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_k:<class 'diffusers.models.lora.LoRACompatibleLinear'>(in_features=320, out_features=320, bias=False))
(INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_k_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_k_input.0.1_3:<class 'float'>)
(PARAMETER:model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_k.weight:tensor(..., device='cuda:0', size=(320, 320), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_k_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))



(MODULE:model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_v:<class 'diffusers.models.lora.LoRACompatibleLinear'>(in_features=320, out_features=320, bias=False))
(INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_v_input.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))
[WARNING](INPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_v_input.0.1_3:<class 'float'>)
(PARAMETER:model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_v.weight:tensor(..., device='cuda:0', size=(320, 320), dtype=oneflow.float16,
       requires_grad=True))
(OUTPUT:_model.down_blocks.0.attentions.0.transformer_blocks.0.attn1.to_v_output.0.0_2:tensor(..., device='cuda:0', is_lazy='True', size=(2, 4096, 320),
       dtype=oneflow.float16))
[ERROR](GRAPH:OneflowGraph_0:OneflowGraph) building graph got error.
ERROR [2024-01-04 10:41:05] - Exception in __call__: e=TypeError("scaled_dot_product_attention(): argument 'query' (position 1) must be Tensor, not Tensor")

**Comment by strint** [comment]
> File "/root/workspace/onediff/src/infer_compiler_registry/register_diffusers/attention_processor_oflow.py", line 364, in forward
return self.processor(

报错位置在这里，https://github.com/siliconflow/onediff/blob/a230e848e482610c004d6e4081b6bd37c042298d/src/infer_compiler_registry/register_diffusers/attention_processor_oflow.py#L364

> File "/root/workspace/diffusers_roberta_v2/diffusers/src/diffusers/models/attention_processor.py", line 1231, in call
hidden_states = F.scaled_dot_product_attention(
TypeError: scaled_dot_product_attention(): argument 'query' (position 1) must be Tensor, not Tensor

看起来是这个 processor 没有被转换成 oneflow。

你帮忙打印下这个  `self.processor` 的类型看看 @HydrogenQAQ

**Comment by HydrogenQAQ** [comment]
加了打印后的输出，走的是diffusers的AttnProcessor：
`OneFlow processor: <diffusers.models.attention_processor.AttnProcessor2_0 object at 0x7f3d302e6a30>
[ERROR](GRAPH:OneflowGraph_0:OneflowGraph) building graph got error.`

![image](https://github.com/siliconflow/onediff/assets/26037094/5ed3c1df-7c78-4921-8992-51e2ac33c442)

相对于原版本主要做的修改点就是更改了text_encoder部分，然后对cnet和unet都输入了encoder_mask，改动了UNetMidBlock2DCrossAttn，CrossAttnDownBlock2D和CrossAttnUpBlock2D的num_layers

**Comment by strint** [comment]
你开下 ONEDIFF_DEBUG=1 这个环境变量，然后执行下，发下日志看看。

估计是你自定义了一些新的 module，导致了一些转换失效。

**Comment by HydrogenQAQ** [comment]
开启后输出：

UserWarning: The oneflow._dynamo.allow_in_graph interface is just to align the torch._dynamo.allow_in_graph interface and has no practical significance.
  warnings.warn(
DEBUG [2024-01-04 13:32:49] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.Attention': <class 'register_diffusers.attention_processor_oflow.Attention'>}

DEBUG [2024-01-04 13:32:49] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.AttnProcessor2_0': <class 'register_diffusers.attention_processor_oflow.AttnProcessor'>}

DEBUG [2024-01-04 13:32:49] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.LoRAAttnProcessor2_0': <class 'register_diffusers.attention_processor_oflow.LoRAAttnProcessor2_0'>}

DEBUG [2024-01-04 13:32:49] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.transformer_2d.Transformer2DModel': <class 'register_diffusers.transformer_2d_oflow.Transformer2DModel'>}

INFO [2024-01-04 13:32:49] - Failed to register_diffusers_quant e=ModuleNotFoundError("No module named 'diffusers_quant'")
Pipe processing:   0%|          | 0/1 [00:00<?, ?i/s]/root/workspace/diffusers_roberta_v2/diffusers/src/diffusers/pipelines/stable_diffusion/util.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  result = torch.tensor(result)
Run

  0%|          | 0/4 [00:00<?, ?it/s]DEBUG [2024-01-04 13:32:50] - Convert <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'> ...
DEBUG [2024-01-04 13:32:52] - Convert id(self._torch_module)=139918089842944 done!

**Comment by HydrogenQAQ** [comment]
我这边注释了diffusers这部分的源码就能转换成功了，啥原因。。。
```
# TODO: add support for attn.scale when we move to Torch 2.1
# hidden_states = F.scaled_dot_product_attention(
#     query, key, value, attn_mask=attention_mask, dropout_p=0.0, is_causal=False
# )
```

**Comment by neiltian-tencent** [comment]
@strint @HydrogenQAQ  遇到了相同的问题。基于pip 21.1.1安装相关库，可以稳定复现。基于pip 24.0.0安装相关库, 问题消失。AttnProcessor2_0比较特殊，不是继承torch.nn.Module类，所以核心在于这个函数有没有被调用到。定位并解决了问题，但是没有理解这里面的机制为什么没有起作用。
```
@singledispatch_proxy
def torch2oflow(mod, *args, **kwargs):
    return default_converter(mod, *args, **kwargs)
```

**Comment by xiwang123** [comment]
> @strint @HydrogenQAQ 遇到了相同的问题。基于pip 21.1.1安装相关库，可以稳定复现。基于pip 24.0.0安装相关库, 问题消失。AttnProcessor2_0比较特殊，不是继承torch.nn.Module类，所以核心下面在于这个函数有没有被调用到。定位并解决了问题，但是没有理解这里面的机制为什么没有起作用。
> 
> ```
> @singledispatch_proxy
> def torch2oflow(mod, *args, **kwargs):
>     return default_converter(mod, *args, **kwargs)
> ```

我换了pip版本也不行

**Comment by bigmover** [comment]
@strint  请问这个问题有解决方法吗？

**Comment by bigmover** [comment]
> @strint @HydrogenQAQ 遇到了相同的问题。基于pip 21.1.1安装相关库，可以稳定复现。基于pip 24.0.0安装相关库, 问题消失。AttnProcessor2_0比较特殊，不是继承torch.nn.Module类，所以核心下面在于这个函数有没有被调用到。定位并解决了问题，但是没有理解这里面的机制为什么没有起作用。
> 
> ```
> @singledispatch_proxy
> def torch2oflow(mod, *args, **kwargs):
>     return default_converter(mod, *args, **kwargs)
> ```

您好！请问具体是哪个库影响的，您介意指导一下吗？

**Comment by neiltian-tencent** [comment]
> > @strint @HydrogenQAQ 遇到了相同的问题。基于pip 21.1.1安装相关库，可以稳定复现。基于pip 24.0.0安装相关库, 问题消失。AttnProcessor2_0比较特殊，不是继承torch.nn.Module类，所以核心下面在于这个函数有没有被调用到。定位并解决了问题，但是没有理解这里面的机制为什么没有起作用。
> > ```
> > @singledispatch_proxy
> > def torch2oflow(mod, *args, **kwargs):
> >     return default_converter(mod, *args, **kwargs)
> > ```
> 
> 您好！请问具体是哪个库影响的，您介意指导一下吗？

@bigmover 把diffusers和onediff相关库都用新的pip安装一下试试
