### ISSUE TITLE
How to support SDXL ControlNet and Inpainting

### ISSUE THREAD

**Issue by hitlmt** [siliconflow/onediff#503]
How to support SDXL ControlNet and Inpainting

**Comment by strint** [comment]
@hitlmt Are you using diffusers?

Here are examples of:
- controlnet:  https://github.com/siliconflow/onediff/blob/main/examples/text_to_image_controlnet.py
- inpainting: https://github.com/siliconflow/onediff/blob/main/examples/reuse_pipeline_components.py

**Comment by strint** [comment]
Too old to follow, and will be closed. Feel free to reopen it.
