### ISSUE TITLE
stable difussion webui插件 和 diffusers框架  支持sdxl controlnet inpainting吗

### ISSUE THREAD

**Issue by jyqjyqjyqjyqjyqjyqjyqjyq** [siliconflow/onediff#504]
stable difussion webui插件 和 diffusers框架  支持sdxl controlnet inpainting吗?

**Comment by strint** [comment]
> diffusers框架 支持sdxl controlnet inpainting吗?

diffusers 是支持的
- controlnet:  https://github.com/siliconflow/onediff/blob/main/examples/text_to_image_controlnet.py
- inpainting: https://github.com/siliconflow/onediff/blob/main/examples/reuse_pipeline_components.py

你可以把需要的 pipeline 发出来我们看看。

stable difussion webui插件的controlnet inpainting在计划中，需要看下需求是否强烈再开发。

**Comment by strint** [comment]
Too old to follow, and will be closed. Feel free to reopen it.
