### ISSUE TITLE
ControlNet speedup node recompiles the model when a prompt changes.

### ISSUE THREAD

**Issue by kvochko** [siliconflow/onediff#551]
### Describe the bug
With the following workflow, controlnet seems to be recompiled whenever I change the prompt.

### Your environment
Debian 11

#### OneDiff git commit id
d387e7e91017051cb1efe6fc801f02ce33fcdd90

####  OneFlow version info
```
version: 0.9.1.dev20240119+cu118
git_commit: 287b806
cmake_build_type: Release
rdma: True
mlir: True
enterprise: True
```
### How To Reproduce
![workflow (29)](https://github.com/siliconflow/onediff/assets/2308830/0df885cc-abe3-43f6-a5c4-fd2b0159999c)

Load the following workflow, run once, change the prompt and run again.

**Comment by ccssu** [comment]
> With the following workflow, controlnet seems to be recompiled whenever I change the prompt.

 Thank you for reaching out, we have reproduced this issue and will fix it today

**Comment by ccssu** [comment]
Hello, @kvochko  ，we have resolved the issue, and you can use the following workflow:
![workflow (73)](https://github.com/siliconflow/onediff/assets/109639975/429135fd-a0de-4f4e-befd-2a9e01c2fd95)

**Comment by kvochko** [comment]
@ccssu thank you, that was quick! I have a few problems after updating.

First of all, it looks like `OneDiffControlNet` was removed, but there is still an import of it in the Controlnet speedup node, which causes this exception with the workflow you gave.

```
  File "/home/akvochko/comfyui_worker_serving/src/comfyui/custom_nodes/onediff_comfy_nodes/_nodes.py", line 312, in apply_controlnet
    from .modules.onediff_controlnet import (
ImportError: cannot import name 'OneDiffControlNet' from 'onediff_comfy_nodes.modules.onediff_controlnet' (/home/akvochko/comfyui_worker_serving/src/comfyui/custom_nodes/onediff_comfy_nodes/modules/onediff_controlnet.py)
```

Another problem happens when I remove the speedup node, on the second run (with the changed prompt), I get this exception:

```
Traceback (most recent call last):
  File "/home/akvochko/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/akvochko/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "./src/comfyui/main.py", line 109, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "/home/akvochko/comfyui_worker_serving/./src/comfyui/execution.py", line 399, in execute
    comfy.model_management.cleanup_models()
  File "/home/akvochko/comfyui_worker_serving/./src/comfyui/comfy/model_management.py", line 430, in cleanup_models
    x.model_unload()
  File "/home/akvochko/comfyui_worker_serving/./src/comfyui/comfy/model_management.py", line 315, in model_unload
    self.model.unpatch_model(self.model.offload_device)
  File "/home/akvochko/comfyui_worker_serving/./src/comfyui/comfy/model_patcher.py", line 353, in unpatch_model
    self.model.to(device_to)
  File "/home/akvochko/comfyui_worker_serving/.venv/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 276, in to
    raise RuntimeError(
RuntimeError: After graph built, the device of graph can't be modified, current device: cuda:0, target device: cpu
```

**Comment by strint** [comment]
>     comfy.model_management.cleanup_models()
>  File "./src/comfyui/comfy/model_management.py", line 430, in cleanup_models
>    x.model_unload()

Yes, the compiled graph can't be offloaded to cpu.

But what makes the model_unload happen? @ccssu @doombeaker @kvochko

**Comment by ccssu** [comment]
> @ccssu thank you, that was quick! I have a few problems after updating.
> RuntimeError: After graph built, the device of graph can't be modified, current device: cuda:0, target device: cpu
> ```
tried by specifying 
the `gpu-only` parameter when starting comfyui, `python main.py  --gpu-only`

**Comment by kvochko** [comment]
Thanks, it it works great now! Closing as resolved.
