### ISSUE TITLE
多分辨率问题

### ISSUE THREAD

**Issue by InuyashaLee** [siliconflow/onediff#555]
请问最新版不是多分辨率“No time cost for most of the cases”吗？为什么我在测试中切换分辨率时，依然需要花费较长时间？下面是我的代码和运行结果。
![1](https://github.com/siliconflow/onediff/assets/114284586/22bda698-f607-400e-8015-7a72b82da37b)
![2](https://github.com/siliconflow/onediff/assets/114284586/aa731599-7935-45d5-b777-dffd2a727105)

**Comment by strint** [comment]
ONEFLOW_RUN_GRAPH_BY_VM 这个设置需要去掉或者打开它

**Comment by InuyashaLee** [comment]
去掉后会报社区版不支持错误
![3](https://github.com/siliconflow/onediff/assets/114284586/7cc61bf1-c152-4099-948a-798b9be9a2e9)

**Comment by strint** [comment]
> 去掉后会报社区版不支持错误 

请参考下这个回答：https://github.com/siliconflow/onediff/issues/543#issuecomment-1903674335

**Comment by InuyashaLee** [comment]
之前的问题更新oneflow后解决了，推理256/512/1024这些常用分辨率没问题。但当我推理其他分辨率时，会出问题。比如，我先推理504*504，再推理512*512，推理512*512时会先报错再推理且第一次会花费较长时间，如下图所示。504和512调换顺序亦然。请问这是为什么呢？
![1](https://github.com/siliconflow/onediff/assets/114284586/8b105581-e2fd-4f14-be9a-ca78ccfac917)

**Comment by strint** [comment]
> 之前的问题更新oneflow后解决了，推理256/512/1024这些常用分辨率没问题。但当我推理其他分辨率时，会出问题。比如，我先推理504_504，再推理512_512，推理512*512时会先报错再推理且第一次会花费较长时间

类似这个 issue，我们后面会看下：https://github.com/siliconflow/onediff/issues/527

**Comment by strint** [comment]
我先关闭这个错误对应的 issue
