### ISSUE TITLE
trying to make it work with segmind/SSD-1B

### ISSUE THREAD

**Issue by menahem121** [siliconflow/onediff#570]
i there im tryng to convert the text_to_image_sdxl_torch_compile.py file in the example folder to make it work with the distilled version of SDXL (SSD-1B) it should work without much modifications because is using the same pipeline as SDXL but im getting an error:

Loading pipeline components...:   0%|                                                                                                  | 0/7 [00:00<?, ?it/s]The config attributes {'reverse_transformer_layers_per_block': [[4, 4, 10], [2, 1, 1], 1]} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...:  14%|████████████▋                                                                            | 1/7 [00:00<00:00, 159.67it/s]
Traceback (most recent call last):
  File "/home/ubuntu/onediff/examples/text_to_image_sdxl.py", line 52, in <module>
    base = StableDiffusionXLPipeline.from_pretrained(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1069, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 468, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 594, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 232, in from_config
    model = cls(**init_dict)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 614, in inner_init
    init(self, *args, **init_kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 434, in __init__
    down_block = get_down_block(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 113, in get_down_block
    return CrossAttnDownBlock2D(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 911, in __init__
    Transformer2DModel(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 614, in inner_init
    init(self, *args, **init_kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 187, in __init__
    for d in range(num_layers)
TypeError: 'list' object cannot be interpreted as an integer

**Comment by hjchen2** [comment]
This error seems to be caused by diffusers when loading the model. You can try to check whether the diffusers version matches. If not, please upgrade to the appropriate diffusers version.

**Comment by menahem121** [comment]
Yeah you right, the modelfor what i understand has to be use with the
diffuser from source
"Pip install git+https://github.com/huggingface/diffusers"

Also randn_tensor moved from diffusers.utils to diffusers.utils.torch_utils



But after fixing those it still not working
I guess you set required=true to unet-module path , text encoder path etc
but i dont understand what should be the path to time-embed-module in
Demo_xl.py this is maybe why im getting this error:

python3 demo_xl.py --unet-module segmind/SSD-1B/unet --text-encoder-module
segmind/SSD-1B/text_encoder --text-encoder-2-module
segmind/SSD-1B/text_encoder_2 --time-embed-module segmind/SSD-1B
--vae-module segmind/SSD-1B/vae
INFO:aitemplate.backend.build_cache_base:Build cache disabled 2024-01-25
19:18:20,343 INFO Set target to CUDA Loading pipeline components...:
100%|██████████████████████████████████████████████████████████████████|
7/7 [01:07<00:00, 9.62s/it] config.json:
100%|██████████████████████████████████████████████████████████████████████████████████|
631/631 [00:00<00:00, 6.60MB/s] diffusion_pytorch_model.safetensors:
100%|█████████████████████████████████████████████████████████| 335M/335M
[00:00<00:00, 392MB/s] Traceback (most recent call last): File
"/home/ubuntu/AITemplate/examples/05_stable_diffusion/scripts/demo_xl.py",
line 125, in run() File
"/home/ubuntu/aitemplateenv/lib/python3.10/site-packages/click/core.py",
line 1157, in call return self.main(*args, **kwargs) File
"/home/ubuntu/aitemplateenv/lib/python3.10/site-packages/click/core.py",
line 1078, in main rv = self.invoke(ctx) File
"/home/ubuntu/aitemplateenv/lib/python3.10/site-packages/click/core.py",
line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File
"/home/ubuntu/aitemplateenv/lib/python3.10/site-packages/click/core.py",
line 783, in invoke return callback(*args, **kwargs) File
"/home/ubuntu/AITemplate/examples/05_stable_diffusion/scripts/demo_xl.py",
line 97, in run pipe = StableDiffusionXLAITPipeline( File
"/home/ubuntu/AITemplate/examples/05_stable_diffusion/src/pipeline_stable_diffusion_xl_ait.py",
line 165, in __init self.timestep_exe = Model(timestep_module_path) File
"/home/ubuntu/aitemplateenv/lib/python3.10/site-packages/aitemplate/compiler/model.py",
line 228, in init self.DLL = self._DLLWrapper(lib_path) File
"/home/ubuntu/aitemplateenv/lib/python3.10/site-packages/aitemplate/compiler/model.py",
line 179, in init self.DLL = ctypes.cdll.LoadLibrary(lib_path) File
"/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary return
self._dlltype(name) File "/usr/lib/python3.10/ctypes/__init__.py", line
374, in init self._handle = _dlopen(self._name, mode) OSError:
segmind/SSD-1B: cannot open shared object file: No such file or directory


Le jeu. 25 janv. 2024 à 05:44, Houjiang Chen ***@***.***> a
écrit :

**Comment by strint** [comment]
Too old to track, will be close. Feel free to reopen it if you still need this.
