### ISSUE TITLE
ERROR! python examples/text_to_image.py

### ISSUE THREAD

**Issue by BoxFishLab** [siliconflow/onediff#571]
RuntimeError: Failed to import diffusers.models.embeddings because of the following error (look up to see its traceback): Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback): oneflow._oneflow_internal.autograd.AutogradFunctionBase.__init__() must be called when overriding __init__
----
os system: ubantu22.04 
oneflow: version: 0.9.1.dev20240122+cu118
git_commit: 16ab196
onediff: 0.12.1.dev0

**Comment by hjchen2** [comment]
What is the version of transformers and diffusers?

**Comment by strint** [comment]
Too old to follow. If still not working, feel free to reopen it.
