### ISSUE TITLE
Stable Diffusion web UI image to image

### ISSUE THREAD

**Issue by HydrogenQAQ** [siliconflow/onediff#572]
#### A clear and concise description of what the bug is.
Hello, when I deploy the web-ui service, onediff can be seen in extensions:

![image](https://github.com/siliconflow/onediff/assets/26037094/a1c20f26-9c45-469b-b71f-91c0c2215602)

But can't find it under script button:

![image](https://github.com/siliconflow/onediff/assets/26037094/987e9a03-adfc-4e0b-bed6-bfea66454ebc)

Does onediff only support t2i tasks?

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

Follow https://github.com/siliconflow/onediff/tree/main/onediff_sd_webui_extensions

**Comment by strint** [comment]
@marigoold @fpzh2011

**Comment by fpzh2011** [comment]
onediff has only been tested under txt2img, and is currently limited to displaying scripts under img2img.

**Comment by HydrogenQAQ** [comment]
ok, when i set is_img2img = True, i found this bug:

![image](https://github.com/siliconflow/onediff/assets/26037094/9bfe3e76-5d0c-443a-b89b-ace50a47d762)

Looking forward to your follow-up support, thank you！

**Comment by strint** [comment]
@HydrogenQAQ Please take a try: https://github.com/siliconflow/onediff/pull/655
