### ISSUE TITLE
webui的插件在使用LoRA的时候不生效

### ISSUE THREAD

**Issue by xiangcp** [siliconflow/onediff#574]
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by strint** [comment]
是支持的：https://github.com/siliconflow/onediff/tree/main/onediff_sd_webui_extensions#lora

cc @marigoold

**Comment by xiangcp** [comment]
> 是支持的：https://github.com/siliconflow/onediff/tree/main/onediff_sd_webui_extensions#lora
> 
> cc @marigoold

为啥我直接开onediff请求基模型加LoRA不生效，但是只有在先请求一遍不开onediff的相同的请求后才生效

**Comment by marigoold** [comment]
@xiangcp 
您好，想请问一下您使用的模型、OneDiff 版本和 LoRA 是什么呢？我来复现一下问题

**Comment by xiangcp** [comment]
> @xiangcp 您好，想请问一下您使用的模型、OneDiff 版本和 LoRA 是什么呢？我来复现一下问题

基模型：deliberate_v2.safetensors [9aba26abdf]
LoRA:  <lora:colorwater_v4: 1>
webui 版本:  version: [1.7.0] python: 3.9.18  •  torch: 2.1.1+cu121

**Comment by marigoold** [comment]
好的，我尝试复现一下。在复现之前我猜测有几个可能的原因：
1. sd-webui 版本和我们适配的没有对齐，您可以查看 https://github.com/siliconflow/onediff/tree/main/onediff_sd_webui_extensions#installation-guide 来安装 OneDiff
2. 目前的优化选项对部分含有 Conv 的 LoRA 不友好。您可以更新到最新的 OneDiff，设置环境变量 ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION 为 0 之后再启动 sd-webui 服务。

我看了一下这个 LoRA，其中有 8% 左右的 Conv 权重，所以方法 2 应该能解决 LoRA 不生效的问题

**Comment by xiangcp** [comment]
> @xiangcp 好的，我尝试复现一下。在复现之前我猜测有几个可能的原因：
> 
> 1. sd-webui 版本和我们适配的没有对齐，您可以查看 https://github.com/siliconflow/onediff/tree/main/onediff_sd_webui_extensions#installation-guide 来安装 OneDiff
> 2. 目前的优化选项对部分含有 Conv 的 LoRA 不友好。您可以更新到最新的 OneDiff，设置环境变量 ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION 为 0 之后再启动 sd-webui 服务。
> 
> 我看了一下这个 LoRA，其中有 8% 左右的 Conv 权重，所以方法 2 应该能解决 LoRA 不生效的问题

我已经使用方法2解决了LoRA不生效的问题，现在主要问题是不是立即生效，要先不使用onediff跑一遍LoRA和基模型才生效。
第一个版本的适配问题我还没试过

**Comment by marigoold** [comment]
我切换了 sd-webui 的版本，使用 deliberate_v2 和 colorwater_v4 直接跑 OneDiff LoRA 也是可以看到 LoRA 效果的。
可能我们之间还有一些环境没对齐，麻烦您把详细的 OneDiff 版本、OneFlow 版本、使用 LoRA 的方法等等内容贴一下，方便我再去复现。

另外“OneDiff 跑 LoRA 不生效，需要先关掉 OneDiff 跑一遍才能生效”这个现象有点像 LoRA weight 没有 fuse 成功导致的，可以在 OneDiff LoRA 生效后关闭 LoRA 或者修改 LoRA strength，看看结果有没有变化，如果没有 fuse 成功，那么应该不会有变化

**Comment by xiangcp** [comment]
> @xiangcp Hi，您好，我切换了 sd-webui 的版本，使用 deliberate_v2 和 colorwater_v4 直接跑 OneDiff LoRA 也是可以看到 LoRA 效果的。 可能我们之间还有一些环境没对齐，麻烦您把详细的 OneDiff 版本、OneFlow 版本、使用 LoRA 的方法等等内容贴一下，方便我再去复现。
> 
> 另外“OneDiff 跑 LoRA 不生效，需要先关掉 OneDiff 跑一遍才能生效”这个现象有点像 LoRA weight 没有 fuse 成功导致的，可以在 OneDiff LoRA 生效后关闭 LoRA 或者修改 LoRA strength，看看结果有没有变化，如果没有 fuse 成功，那么应该不会有变化

1、环境版本
oneflow                   0.9.1.dev20240123+cu121
onediff                   0.12.0.dev0
2、LoRA的使用就直接prompt里面使用 <lora:colorwater_v4: 1>
3、立即使用onediff的话，没加LoRA和加了LoRA效果不一样，但是不是LoRA的效果，也就是和不使用onediff时的LoRA效果对不上。但是在不使用onediff跑一遍以后效果就对上了，很奇怪，怀疑是fuse的时候有问题

**Comment by marigoold** [comment]
> 没加LoRA和加了LoRA效果不一样，但是不是LoRA的效果

这个我也见到过，是常量折叠那个选项没关造成的，不过您这里已经关了。这个现象很奇怪，我始终无法复现，或者可以约个腾讯会议，看一下具体情况，我这边时间都 OK。

**Comment by xiangcp** [comment]
> > 没加LoRA和加了LoRA效果不一样，但是不是LoRA的效果
> 
> 这个我也见到过，是常量折叠那个选项没关造成的，不过您这里已经关了。这个现象很奇怪，我始终无法复现，或者可以约个腾讯会议，看一下具体情况，我这边时间都 OK。

可以贴一下环境的版本详情吗？我看到更换环境后这个LoRA合并的效果问题依旧存在，但是跟原始不使用onediff对不齐，同时有一个警告：
No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 0.9.1.dev20240123+cu121. You might want to consider upgrading. 
ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION不能设置：
-bash: ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION: command not found

我的环境如下：
python -m oneflow --doctor
    path: ['/data/SD/stable-diffusion-webui/venv/lib64/python3.9/site-packages/oneflow']
    version: 0.9.1.dev20240123+cu121
    git_commit: 07940da
    cmake_build_type: Release
    rdma: True
    mlir: True
    enterprise: False
pip list
    onediff                   0.12.0.dev0             /data/xcp/onediff-0.12.0/src
    oneflow                   0.9.1.dev20240123+cu121
pip show torch
    Name: torch
    Version: 2.1.1+cu121
    Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
    Home-page: https://pytorch.org/
    Author: PyTorch Team
    Author-email: packages@pytorch.org
    License: BSD-3
    Location: /data/SD/stable-diffusion-webui/venv/lib/python3.9/site-packages
    Requires: filelock, fsspec, jinja2, networkx, sympy, triton, typing-extensions
    Required-by: accelerate, basicsr, clean-fid, clip, compel, consistencydecoder, facexlib, gfpgan, kornia, lion-pytorch, lpips, onediff, open-clip-torch, pytorch-lightning, realesrgan, timm, tomesd, torcrchdiffeq, torchmetrics, torchsde, torchvision, ultralytics, xformers

**Comment by strint** [comment]
> ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION: command not found

看起来是环境变量的设置方法有问题。你试下：
```
export ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION=0
```
或者 

```
ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION=0 python your_py_script.py
```

**Comment by marigoold** [comment]
@xiangcp  您好，我刚刚复现了这个现象，正在排查问题，感谢反馈！

**Comment by xiangcp** [comment]
> @xiangcp 您好，请问可以分享一下 prompt 以及其他的参数吗？这样我复现起来更方便一些
deliberate_v2.safetensors [9aba26abdf]
Clip skip = 2
1girl <lora:try2:1>
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123, Size: 512x512, Model hash: 9aba26abdf, Model: deliberate_v2, Clip skip: 2, Lora hashes: "try2: 91184b428ad3", Version: 1.7.0

**Comment by marigoold** [comment]
我用这个配置尝试了一下，以下是结果：

PyTorch 结果：
1girl <lora:watercolor:1>
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123, Size: 512x512, Model hash: 9aba26abdf, Model: Deliberate_v2, Clip skip: 2, Lora hashes: "watercolor: 91184b428ad3", Version: v1.7.0
![image](https://github.com/siliconflow/onediff/assets/53533850/78d1cd43-f36d-41ff-b44d-461346d5d629)

OneDiff 结果（启动 sd-webui 之后直接在 Script 中选择 onediff，然后 prompt 中加载 LoRA，没跑 PyTorch）：
1girl <lora:watercolor:1>
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123, Size: 512x512, Model hash: 9aba26abdf, Model: Deliberate_v2, Clip skip: 2, Lora hashes: "watercolor: 91184b428ad3", Version: v1.7.0
![image](https://github.com/siliconflow/onediff/assets/53533850/8d3d4605-980d-4ea0-b7ba-1e1324a2f9bb)

OneDiff 结果（跑 PyTorch 之后再跑 OneDiff）：
1girl <lora:watercolor:1>
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123, Size: 512x512, Model hash: 9aba26abdf, Model: Deliberate_v2, Clip skip: 2, Lora hashes: "watercolor: 91184b428ad3", Version: v1.7.0
![image](https://github.com/siliconflow/onediff/assets/53533850/7a0bafc2-657d-4313-9b4e-527d9444646d)

**Comment by marigoold** [comment]
> @xiangcp 您好，我需要更详细的信息来定位问题
> 
> 1. 您可以提供一下启动 sd-webui 时候的环境变量以及启动 sd-webui 的命令吗？（获取环境变量的方法是在 shell 中输入 env 然后回车，然后把 shell 输出内容贴到这里）
> 2. 加载 LoRA 后，再取消 LoRA，使用 OneDiff 出来的结果和不使用 OneDiff 出来的结果相同吗？
> 3. 换一个不带 Conv 权重的 LoRA 是否能复现问题？

您好，这些信息可以提供一下吗？方便我定位和复现问题。

**Comment by xiangcp** [comment]
> * 您可以提供一下启动 sd-webui 时候的环境变量以及启动 sd-webui 的命令吗？（获取环境变量的方法是在 shell 中输入 env 然后回车，然后把 shell 输出内容贴到这里）

1、环境变量如下：
SHELL=/bin/bash
HISTCONTROL=ignoredups
CONDA_EXE=/home/dbt-aigc-TT/miniconda3/bin/conda
_CE_M=
HISTSIZE=1000
HOSTNAME=localhost
PWD=/data/xcp/stable-diffusion-webui-1.7
LOGNAME=dbt-aigc-TT
XDG_SESSION_TYPE=tty
CONDA_PREFIX=/home/dbt-aigc-TT/miniconda3
MOTD_SHOWN=pam
HOME=/home/dbt-aigc-TT
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:
VIRTUAL_ENV=/data/SD/stable-diffusion-webui/venv
CONDA_PROMPT_MODIFIER=(base)
SSH_CONNECTION=192.168.240.155 5367 192.168.241.98 22
ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION=0
XDG_SESSION_CLASS=user
TERM=xterm
_CE_CONDA=
LESSOPEN=||/usr/bin/lesspipe.sh %s
USER=dbt-aigc-TT
CONDA_SHLVL=1
DISPLAY=localhost:10.0
SHLVL=1
XDG_SESSION_ID=79
CONDA_PYTHON_EXE=/home/dbt-aigc-TT/miniconda3/bin/python
LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64:
XDG_RUNTIME_DIR=/run/user/1001
PS1=(venv) (base) [\u@\h \W]\$
SSH_CLIENT=192.168.240.155 5367 22
CONDA_DEFAULT_ENV=base
DEBUGINFOD_URLS=https://debuginfod.centos.org/
which_declare=declare -f
PATH=/data/SD/stable-diffusion-webui/venv/bin:/home/dbt-aigc-TT/miniconda3/bin:/home/dbt-aigc-TT/miniconda3/condabin:/home/dbt-aigc-TT/.local/bin:/home/dbt-aigc-TT/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
MAIL=/var/spool/mail/dbt-aigc-TT
SSH_TTY=/dev/pts/0
OLDPWD=/data/xcp
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
_=/usr/bin/env
启动命令如下：
python webui.py --listen
2、这两种情况下结果是一致的
![00001-123](https://github.com/siliconflow/onediff/assets/75286791/2fa290b1-064a-4842-8fc0-f6976d93eb4f)
3、能否发我一个我测试下？

**Comment by marigoold** [comment]
@xiangcp 请问您的 onediff 版本是多少呢？我刚刚 git checkout 到  0.12.0 可以复现出来了，升级到最新的 main 就解决了。

**Comment by xiangcp** [comment]
> @xiangcp 请问您的 onediff 版本是多少呢？我刚刚 git checkout 到 0.12.0 可以复现出来了，升级到最新的 main 就解决了。

我的版本是：
onediff                   0.12.1.dev202401310124
oneflow                   0.9.1.dev20240125+cu121
安装方式是按照你们的官方网页上安装的，python3 -m pip install --pre onediff|
我更新到最新的main后，版本是
onediff                   0.12.1.dev1
问题还在

**Comment by xiangcp** [comment]
> @xiangcp 请问您的 onediff 版本是多少呢？我刚刚 git checkout 到 0.12.0 可以复现出来了，升级到最新的 main 就解决了。

想问下你的pytorch和cuda的版本

**Comment by strint** [comment]
> onediff 0.12.1.dev202401310124

onediff 不是最新的。可以参考  https://github.com/siliconflow/onediff?tab=readme-ov-file#3-install-onediff 中的 From source
 的方式来安装下 onediff

**Comment by xiangcp** [comment]
> > onediff 0.12.1.dev202401310124
> 
> onediff 不是最新的。看这里 https://pypi.org/project/onediff/#history 已经更新到了 0.12.1.dev202402180126
> 
> 另外也可以参考 https://github.com/siliconflow/onediff?tab=readme-ov-file#3-install-onediff 中的 From source 的方式来安装下 onediff
我更新到一下版本：
onediff                   0.12.1.dev202402180126
问题还是在。。。

**Comment by marigoold** [comment]
> > @xiangcp 您好，我用这个配置尝试了一下，以下是结果，可以确认一下哪里的结果和您这边的表现不同。
> > PyTorch 结果： 1girl lora:watercolor:1 Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123, Size: 512x512, Model hash: 9aba26abdf, Model: Deliberate_v2, Clip skip: 2, Lora hashes: "watercolor: 91184b428ad3", Version: v1.7.0 ![image](https://private-user-images.githubusercontent.com/53533850/305688169-78d1cd43-f36d-41ff-b44d-461346d5d629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzgxMzcsIm5iZiI6MTcwODIzNzgzNywicGF0aCI6Ii81MzUzMzg1MC8zMDU2ODgxNjktNzhkMWNkNDMtZjM2ZC00MWZmLWI0NGQtNDYxMzQ2ZDVkNjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA2MzAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZmM0Y2NkMzFiZTVmYzViOWY5OWY0ZDQxNTA1ODM5YWMwYWEyZmY5YWQ0ZjgyN2U2NTY0ODMxNDIwZjVlZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s_GRDrMIUkGaaTki8erUBvLsfK7hm9ijgxUp6vux2Yg)
> > OneDiff 结果（启动 sd-webui 之后直接在 Script 中选择 onediff，然后 prompt 中加载 LoRA，没跑 PyTorch）： 1girl lora:watercolor:1 Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123, Size: 512x512, Model hash: 9aba26abdf, Model: Deliberate_v2, Clip skip: 2, Lora hashes: "watercolor: 91184b428ad3", Version: v1.7.0 ![image](https://private-user-images.githubusercontent.com/53533850/305688222-8d3d4605-980d-4ea0-b7ba-1e1324a2f9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzgxMzcsIm5iZiI6MTcwODIzNzgzNywicGF0aCI6Ii81MzUzMzg1MC8zMDU2ODgyMjItOGQzZDQ2MDUtOTgwZC00ZWEwLWI3YmEtMWUxMzI0YTJmOWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA2MzAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwOWE4ZWZhODllNGY4YzI1YTcxNTIwYjFiMWZlYjJkMzcyYzUxZjRkNDBmNmE5MDQ1OGU2MmQ1M2MwZjUzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Xh3VZYNwkCXV-jhxG-yooWwn7Hf2PYVDcn5sxqN794)
> > OneDiff 结果（跑 PyTorch 之后再跑 OneDiff）： 1girl lora:watercolor:1 Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123, Size: 512x512, Model hash: 9aba26abdf, Model: Deliberate_v2, Clip skip: 2, Lora hashes: "watercolor: 91184b428ad3", Version: v1.7.0 ![image](https://private-user-images.githubusercontent.com/53533850/305688263-7a0bafc2-657d-4313-9b4e-527d9444646d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzgxMzcsIm5iZiI6MTcwODIzNzgzNywicGF0aCI6Ii81MzUzMzg1MC8zMDU2ODgyNjMtN2EwYmFmYzItNjU3ZC00MzEzLTliNGUtNTI3ZDk0NDQ2NDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA2MzAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMGY3MTk0MGNhNmI5ODFhMTAyYjQyNDY5MjA1NzMxMDQwZTZkNDIzMjQ1OGMxMGRjZjY1ZDk2YjhhMTU3MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_C1FTjyiPUMOrzndl7wkb7cPxNF3FQvGYFrjO3eEjI)
> 
> 就只有直接使用onediff的结果对不上，以下是我的结果： OneDiff 结果（启动 sd-webui 之后直接在 Script 中选择 onediff，然后 prompt 中加载 LoRA，没跑 PyTorch）： 1girl lora:try2:1 Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123, Size: 512x512, Model hash: 9aba26abdf, Model: deliberate_v2, Clip skip: 2, Lora hashes: "try2: 91184b428ad3", Version: 1.7.0 ![00000-123](https://private-user-images.githubusercontent.com/75286791/305689790-b3c90952-33b6-4c3a-ac80-d5e29716b505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDU2NDMsIm5iZiI6MTcwODI0NTM0MywicGF0aCI6Ii83NTI4Njc5MS8zMDU2ODk3OTAtYjNjOTA5NTItMzNiNi00YzNhLWFjODAtZDVlMjk3MTZiNTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA4MzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOTg0Njg5MTg4YzdlNjQzY2JjNWNiYzBjZWFlZGM5NjNjYzk1Nzk4YWE0YTdlMTk0YjAyMGExNjJmNTMzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dx279b0NZHBUhg8XUqipIdCK57eUS5NRAAjedHDeRWM)

@xiangcp  您好，这个错误的图看起来是 unet 的 LoRA 没加载进去造成的。我手动做了一个 colorwater_te 的 LoRA，只包含了 text encoder 的权重，不包含 unet 的。结果是这样的：
1girl <lora:colorwater_te:1>
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 123, Size: 512x512, Model hash: 9aba26abdf, Model: Deliberate_v2, Clip skip: 2, Lora hashes: "colorwater_te: 064436992316", Version: v1.7.0

![image](https://github.com/siliconflow/onediff/assets/53533850/98d8196d-b954-4deb-9238-d2b7b55bff02)

最初 OneDiff sd-webui 不支持 LoRA 时候，unet 的 LoRA 权重就会加载不进去，会出现这种情况，但是现在已经支持了。所以建议您再检查一下 stable-diffusion-webui/extensions/onediff_sd_webui_extensions/scripts/onediff.py 这个代码文件最后一个 run 函数内容，是否包含 HijackLoraActivate，并在这里打个断点查看是否函数运行是否能进入到这里。

**Comment by xiangcp** [comment]
> HijackLoraActivate

好了，感谢，原因是onediff插件版本不对，没有HijackLoraActivate，重新下载就好了。
顺便问下sd webui controlnet 啥时候可以支持？

**Comment by strint** [comment]
> 顺便问下sd webui controlnet 啥时候可以支持？


这个可以再提个 issue。计划是下个版本加上。

**Comment by frc99** [comment]
onediff==1.2.1.dev28 ,oneflow==0.9.1.dev20241019+cu118 目前仍然存在这个问题，首次编译完Lora不生效，添加环境变量export ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION=0仍然不生效。
