### ISSUE TITLE
stable-diffusion-webui 启用controlnet后会导致生图失败

### ISSUE THREAD

**Issue by ivanszl** [siliconflow/onediff#591]
#### A clear and concise description of what the bug is.
stable-diffusion-webui 启用controlnet后，会导致文生图失败
报错日志为：
A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32"

#### OS 
Ubuntu 22.04.2 LTS
pytorch 2.0.1
cuda 11.8
controlnet  v1.1.426
cn模型： control_v11p_sd15_openpose.fp16

#### OneDiff git commit id
6458a12

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
version: 0.9.1.dev20240129+cu118
git_commit: 6458a12
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):

### The complete error message
A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32"

**Comment by strint** [comment]
感谢反馈，control net  当前我们在 comfyui 和 diffusers 做了支持。

春节后会增加对 webui control net  的支持，到时会再来处理这个 issue。

**Comment by strint** [comment]
controlnet 已经做了有限支持。不过我们后面会偏向优先维护 HF diffusers 和 Comfyui 的版本。
