### ISSUE TITLE
是所有版本的stable diffusion webui 都可以使用吗？

### ISSUE THREAD

**Issue by 1344663783** [siliconflow/onediff#601]
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by strint** [comment]
有指定的版本：https://github.com/siliconflow/onediff/tree/main/onediff_sd_webui_extensions#installation-guide

git checkout 相关的部分指定了版本
