### ISSUE TITLE
[Feature request] DeepCache for image to image

### ISSUE THREAD

**Issue by Amber0130** [siliconflow/onediff#629]
onediff_diffusers_extensions 现在还不支持图生图吗

**Comment by strint** [comment]
这里有个例子：https://github.com/siliconflow/onediff/blob/main/examples/image_to_image.py

看是不是你想要的

**Comment by Amber0130** [comment]
https://github.com/siliconflow/onediff/tree/main/onediff_diffusers_extensions 这里面只有文生图的demo，没有图生图的现在还不支持吗，我看也没有相关的代码。。。

**Comment by strint** [comment]
你是指 compile_pipe 函数是否支持 StableDiffusionImg2ImgPipeline 么？

onediff 中的 oneflow_compile 和 onediffx 中的 compile_pipe 对图生图都是支持的。

**Comment by Amber0130** [comment]
<img width="1294" alt="image" src="https://github.com/siliconflow/onediff/assets/54001386/23da952b-1180-4d01-877d-0f22a4b08302">
这里面好像不支持StableDiffusionImg2ImgPipeline

**Comment by strint** [comment]
DeepCache 是还没提供 image to image 的 pipeline @Amber0130 

cc @clackhan

**Comment by Amber0130** [comment]
> DeepCache 是还没提供 image to image 的 pipeline @Amber0130
> 
> 你那里使用过 text to image 的 DeepCache 么，实用性怎么样呢。 我们在考虑 image to image 的支持，需要看实际需求的情况。
> 
> cc @clackhan

在A10上加速挺明显的，720*1280分辨率，v1.5，从3.8s优化到2.1s

**Comment by strint** [comment]
> > DeepCache 是还没提供 image to image 的 pipeline @Amber0130
> > 你那里使用过 text to image 的 DeepCache 么，实用性怎么样呢。 我们在考虑 image to image 的支持，需要看实际需求的情况。
> > cc @clackhan
> 
> 在A10上加速挺明显的，720*1280分辨率，v1.5，从3.8s优化到2.1s

有明显加速是已知的。你们会用到实际的业务中么，因为出图结果有些微差别。

**Comment by Amber0130** [comment]
> > > DeepCache 是还没提供 image to image 的 pipeline @Amber0130
> > > 你那里使用过 text to image 的 DeepCache 么，实用性怎么样呢。 我们在考虑 image to image 的支持，需要看实际需求的情况。
> > > cc @clackhan
> > 
> > 
> > 在A10上加速挺明显的，720*1280分辨率，v1.5，从3.8s优化到2.1s
> 
> 有明显加速是已知的。你们会用到实际的业务中么，因为出图结果有些微差别。

质量差别还是挺大的，目前这种效果可能不会用到实际业务中

**Comment by strint** [comment]
Too old to track, will be close. Feel free to reopen it if you still need this.
