### ISSUE TITLE
[Feature/Question] OneDiff support for InstantID in comfy?

### ISSUE THREAD

**Issue by banjaminicc** [siliconflow/onediff#648]
As title.
I can't seem to run InstantID in Comfy with Onediff Deep cache, is this expected?

**Comment by strint** [comment]
> run InstantID in Comfy with Onediff

@ccssu is working on this.

**Comment by strint** [comment]
> InstantID  with Onediff Deep cache

We will think about this.

**Comment by ccssu** [comment]
> As title. I can't seem to run InstantID in Comfy with Onediff Deep cache, is this expected?
We have selected an open-source repository for acceleration. Please refer to it. https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/pull/110

**Comment by strint** [comment]
@banjaminicc https://github.com/siliconflow/onediff/tree/main/onediff_comfy_nodes#instantid
