### ISSUE TITLE
I am getting "AttributeError: 'OneflowGraph' object has no attribute '_input_op_names'"

### ISSUE THREAD

**Issue by noah1320** [siliconflow/onediff#653]
I am trying to generate img2img using onediff.

pipe1 = StableDiffusionImg2ImgPipeline.from_pretrained(
    "stabilityai/sdxl-turbo", use_auth_token=True, variant="fp16", torch_dtype=torch.float16,
)

images = pipe1(prompt1, image=img, guidance_scale=0.5, num_inference_steps=2, output_type="np").images[0]

gives me "AttributeError: 'OneflowGraph' object has no attribute '_input_op_names'" and I don't know how to fix it :( Please help

**Comment by noah1320** [comment]
first error i get is: 
"TypeError: argument of type 'NoneType' is not iterable"

**Comment by noah1320** [comment]
![image](https://github.com/siliconflow/onediff/assets/54676274/ceea6c01-a1b1-465a-97f2-5073b222a4fe)

**Comment by strint** [comment]
@noah1320 Does the problem still exists?

**Comment by xyyimian** [comment]
same issue @strint
