### ISSUE TITLE
哪种框架支持img2img inpaint controlnet+lora？

### ISSUE THREAD

**Issue by thinkyang88** [siliconflow/onediff#660]
算法pipeline img2img inpaint +controlnet +lora（可选），请问现在sd-web-ui，diffusers，comfyui哪种框架支持吗？sd模型版本为1.5或者xl。如果现在都不支持，后续有计划支持吗？感谢

**Comment by strint** [comment]
@doombeaker 可以帮忙回答下

**Comment by strint** [comment]
我们是对工作流的中的子模块做加速。
- img2img 中的 unet、vae；
- lora 也支持；
- controlnet 也支持加速；

看用的什么样的工作流，然后使用 onediff 对其中的某个模块做加速即可。

**Comment by doombeaker** [comment]
@thinkyang88 comfyui 有现成的 inpainting、controlnet 和 lora 工作流 example https://comfyanonymous.github.io/ComfyUI_examples/

这些 onediff 都已经支持。

不过可能你想了解的是，三者私有的组合在一起的工作流？这些技术是正交的，一般没有现成的组合在一起的工作流，如果你有已经跑通的私有工作流，但是用 onediff 加速失败了，可以把问题贴一下。

**Comment by doombeaker** [comment]
另外，其实 diffusers、sd-webui 本身也支持这三类工作流/算法。onediff 对 diffusers、webui 这类工作流也是支持的 （sd-wbui 的 controlnet + onediff 还在实现中）。
