### ISSUE TITLE
AttributeError when running InstantID

### ISSUE THREAD

**Issue by xiecon** [siliconflow/onediff#663]
### Error message
```
...
File "XX/InstantID/pipeline_stable_diffusion_xl_instantid_full.py", line 427, in get_weighted_text_embeddings_sdxl
    prompt_embeds_1_hidden_states = prompt_embeds_1.hidden_states[-2]
AttributeError: 'oneflow._oneflow_internal.TensorTuple' object has no attribute 'hidden_states'
```
#### OS
linux
####  OneFlow version info
version: 0.9.1.dev20240208+cu118
git_commit: 206a195
cmake_build_type: Release
rdma: True
mlir: True

**Comment by strint** [comment]
> OneFlow version info version: 0.9.1.dev20240208+cu118 git_commit: 206a195

@xiecon  Your oneflow seem pretty old, please try to update to the latest like this:
https://github.com/siliconflow/onediff?tab=readme-ov-file#onediff-installation

**Comment by strint** [comment]
@xiecon Anything new?

**Comment by xiecon** [comment]
After reinstalling everything, the problem no longer occurred, but I am still not sure which part caused it.
