### ISSUE TITLE
AttributeError("'map' object has no attribute 'chunk'") When using lpw_pipeline

### ISSUE THREAD

**Issue by Metal079** [siliconflow/onediff#674]
### Describe the bug
Is there a way to run a compiled onediff model with the lwp pipeline? I want the extended token lengths and weighted prompts but I get an error when trying to move a compiled model to use the pipeline

AttributeError("'map' object has no attribute 'chunk'")

### Your environment
Windows 11, WSL

#### OneDiff git commit id
git_commit: 6621521

####  OneFlow version info
(venv) metal@DESKTOP-AQ9BALB:~/mobians_api$ python -m oneflow --doctor
libibverbs not available, ibv_fork_init skipped
path: ['/home/metal/mobians_api/venv/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240219+cu121
git_commit: 6621521
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):
Heres where the issue occurs in the attached image of the lpw_pipeline

and heres how im loading in the model

```
def load_model(model_name):
    model = StableDiffusionPipeline.from_pretrained(
        model_name,
        torch_dtype=torch.float16,
        # custom_pipeline="lpw_stable_diffusion",
        safety_checker=None,
    )
    model.to(torch.device("cuda"))
    model = compile_pipe(model)

    stable_diffusion_txt2img  = StableDiffusionLongPromptWeightingPipeline(
        vae = model.vae,
        text_encoder= model.text_encoder,
        tokenizer= model.tokenizer,
        unet = model.unet,
        safety_checker= None,
        scheduler= model.scheduler,
        feature_extractor= model.feature_extractor
    )
    stable_diffusion_txt2img.to(torch.device("cuda"))

    stable_diffusion_txt2img.scheduler = EulerAncestralDiscreteScheduler.from_config(
        model.scheduler.config
    )
```

![image](https://github.com/siliconflow/onediff/assets/7731400/ecdb9b64-d183-41a4-8259-fe5cf5fe8a22)

https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py

### The complete error message
AttributeError("'map' object has no attribute 'chunk'")

**Comment by strint** [comment]
It seems that Unet in `StableDiffusionLongPromptWeightingPipeline` returned a special output. We will try to reproduce this later.

**Comment by strint** [comment]
Too old to track, will be close. Feel free to reopen it if you still need this.
