### ISSUE TITLE
ComfyUI SVD example workflow resolution error

### ISSUE THREAD

**Issue by connorzl** [siliconflow/onediff#683]
When following the example SVD ComfyUI workflow (https://github.com/siliconflow/onediff/blob/main/onediff_comfy_nodes/workflows/text-to-video-speedup.png) I get the following error:

`ERROR [2024-02-28 22:03:14] /mnt/disks/comfy-00/onediff/src/onediff/infer_compiler/with_oneflow_compile.py:187 - Exception in __call__: e=Exception('cannot unflatten input from shape (25,1280) to (2,12,1280)\n  File "oneflow/core/job/job_interpreter.cpp", line 305, in InterpretJob\n    RunViewOp(launch_context, launch_op, inputs)\n  File "oneflow/core/job/job_interpreter.cpp", line 271, in RunViewOp\n    [&]() -> Maybe<const LocalTensorInferResult> { LocalTensorMetaInferArgs ... mut_local_tensor_infer_cache()->GetOrInfer(infer_args)); }()\n  File "oneflow/core/job/job_interpreter.cpp", line 274, in operator()\n    op->mut_local_tensor_infer_cache()->GetOrInfer(infer_args)\n  File "oneflow/core/framework/local_tensor_infer_cache.cpp", line 210, in GetOrInfer\n    Infer(*user_op_expr, infer_args)\n  File "oneflow/core/framework/local_tensor_infer_cache.cpp", line 178, in Infer\n    user_op_expr.InferPhysicalTensorDesc( infer_args.attrs ... ) -> TensorMeta* { return &output_mut_metas.at(i); })\n  File "oneflow/core/framework/op_expr.cpp", line 602, in InferPhysicalTensorDesc\n    physical_tensor_desc_infer_fn_(&infer_ctx)\n  File "oneflow/user/ops/unflatten_op.cpp", line 75, in InferLogicalTensorDesc\n    CHECK_EQ_OR_RETURN(out_shape.elem_cnt(), in_shape.elem_cnt())\nError Type: oneflow.ErrorProto.check_failed_error')
`

However, for 1024x1024 resolution it seems to work fine -- is there a fix for getting this to work at 1024x576 (native SVD resolution)?

**Comment by strint** [comment]
@connorzl Please gull the new main branch and have a try.

**Comment by connorzl** [comment]
It works now -- thanks for the quick fix!
