### ISSUE TITLE
onediff接入到animatediff-cli-prompt-travel的问题

### ISSUE THREAD

**Issue by hihei** [siliconflow/onediff#684]
问题背景: 现在想使用onediff对animatediff-cli-prompt-travel( https://github.com/s9roll7/animatediff-cli-prompt-travel )，
想采用
```
from onediff.infer_compiler import oneflow_compile
pipeline.unet = oneflow_compile(pipeline.unet)
```
这种优化方式，但是其Unet的实现并非diffusers官方实现，而是在src/animatediff/models/unet.py，基于torch和diffusers框架实现的UNet3DConditionModel,因此执行上述代码时出现报错
```
Exception: Cannot find the kernel matching Current OperatorConf.  The Info of OperatorConf are
 op_name: model.up_blocks.0.upsamplers.0-upsample_nearest_3d-1745
 op_type_name: upsample_nearest_3d
 DeviceType_Name: kCUDA
 DataType_Name of x_0: kFloat16
 DataType_Name of y_0: kFloat16
```
现在想了解下，是否有办法可以使用上述方案，或者有什么方式可以使用onediff来进行加速呢?

**Comment by hihei** [comment]
上述问题解决了一部分，原因是代码库中的resnet.py中采用了torch.nn.functional.interpolate函数，而这个oneflow识别不了，所以出现上述报错。

**Comment by hihei** [comment]
上述报错再次解决了一部分，将onediff由之前的dev_comfyui_animatediff_evolved分支换成master分支直接编译的就通了。

**Comment by hihei** [comment]
上述问题已经解决。主要问题点在于：torch.nn.functional.interpolate 的最临近插值这个算子oneflow无法转换，所以需要自己重新写一个。
过程中碰到两个问题点: 
···
def nearest_interpolate(input_tensor, size=None, scale_factor=None):
    """
    最临近插值
    :param input_tensor:
    :param size:
    :param scale_factor:
    :return:
    """
    new_shape = list(input_tensor.shape)
    if size is not None:
        for i in range(2, 2 + len(size)):
            new_shape[i] = size[i - 2]
    if scale_factor is not None:
        for i in range(2, 2 + len(scale_factor)):
            new_shape[i] = int(new_shape[i] * scale_factor[i - 2])
    output_tensor = torch.zeros(new_shape, dtype=input_tensor.dtype, device=input_tensor.device.type)
    index_k = (torch.arange(0, output_tensor.shape[-1]) / output_tensor.shape[-1] * input_tensor.shape[-1]).int()
    index_j = (torch.arange(0, output_tensor.shape[-2]) / output_tensor.shape[-2] * input_tensor.shape[-2]).int()
    index_i = (torch.arange(0, output_tensor.shape[-3]) / output_tensor.shape[-3] * input_tensor.shape[-3]).int()
    output_tensor = input_tensor[:, :, index_i][:, :, :, index_j][:, :, :, :, index_k]
    return output_tensor
···

**Comment by hihei** [comment]
已经解决

**Comment by strint** [comment]
> 通过oneflow_compile对unet和controlnet部分进行加速，流程已跑通

@hihei Nice work!
