### ISSUE TITLE
Can Onediff comfyui node support NVIDIA V100 GPU？

### ISSUE THREAD

**Issue by ywdong** [siliconflow/onediff#685]
Can Onediff comfyui node support NVIDIA V100 GPU？Many thanks!

**Comment by strint** [comment]
> Can Onediff comfyui node support NVIDIA V100 GPU？Many thanks!

Yes. It can run on V100. You can have a try.

**Comment by strint** [comment]
But GPU architecture under 75 can't get good performance by OneDiff, and  V100 is 70: https://en.wikipedia.org/wiki/CUDA#:~:text=DRIVE%C2%A0PX%C2%A02-,7.0,-Volta
