### ISSUE TITLE
Support  DeepCache for Playground v2.5

### ISSUE THREAD

**Issue by strint** [siliconflow/onediff#703]
- https://huggingface.co/playgroundai/playground-v2.5-1024px-aesthetic
- https://www.reddit.com/r/StableDiffusion/comments/1b2zsli/playground_v25_is_actually_the_best_open_model/

**Comment by strint** [comment]
> test "playground v2.5" model with DeepCache SDXL pipeline on the latest diffusers? I see it works for 1024x1024 but then it errros and re-compiles for 512x512 etc.

**Comment by clackhan** [comment]
> > test "playground v2.5" model with DeepCache SDXL pipeline on the latest diffusers? I see it works for 1024x1024 but then it errros and re-compiles for 512x512 etc.

DeepCache SDXL pipeline currently does not support multi-resolution. Onediffx will be refactored and resolve this issue in the near future.

**Comment by strint** [comment]
cc @isidentical

**Comment by strint** [comment]
Related RP: https://github.com/siliconflow/onediff/pull/733

**Comment by clackhan** [comment]
> > > test "playground v2.5" model with DeepCache SDXL pipeline on the latest diffusers? I see it works for 1024x1024 but then it errros and re-compiles for 512x512 etc.
> 
> DeepCache SDXL pipeline currently does not support multi-resolution. Onediffx will be refactored and resolve this issue in the near future.

@isidentical DeepCache SDXL pipeline supports now. Please update oneidff to use this feature.
