### ISSUE TITLE
如何切换回编译前的torch前向过程

### ISSUE THREAD

**Issue by zhangvia** [siliconflow/onediff#707]
在使用webui时，如果使用了类似ipadapter等需要修改模型前向过程的功能时，需要重新编译静态图进行加速。有没有办法可以实现类似这样的过程：正常文生图时使用静态图推理，切换到ipadapater时使用原来的unet的torch代码进行推理。

似乎使用oneflow_compile编译模型后，就无法再调用原有的forward过程了

**Comment by strint** [comment]
@marigoold can join to think about it.

**Comment by strint** [comment]
> 似乎使用oneflow_compile编译模型后，就无法再调用原有的forward过程了

静态图是固定了执行逻辑的。切换到 ipadapater 等特殊逻辑暂时没有考虑支持。

如果需求很强，有更多说明资料的话，我们可以考虑下。你也考虑自己改下这块的执行逻辑试试。
