### ISSUE TITLE
OneDiffCheckpointLoaderSimple cannot apply LoRa

### ISSUE THREAD

**Issue by lackofdream** [siliconflow/onediff#715]
#### A clear and concise description of what the bug is.
OneDiffCheckpointLoaderSimple cannot apply LoRa
#### OS 
Linux
#### OneDiff git commit id
22167094e6aad93ac3d38015d3fd932bccb0554b
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
path: ['/home/ubuntu/comfyui/venv/lib/python3.11/site-packages/oneflow']
version: 0.9.1.dev20240219+cu121
git_commit: 6621521
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
### How To Reproduce
Steps to reproduce the behavior(code or script):
1. Generate an image without LoRA using OneDiffCheckpointLoaderSimple. For example using the workflow below
[workflow_api(1).json](https://github.com/siliconflow/onediff/files/14537352/workflow_api.1.json)
2. Add the LoadLoRa node, do inference again and see the LoRa is not probably applied
[workflow_api(3).json](https://github.com/siliconflow/onediff/files/14537406/workflow_api.3.json)

### The complete error message
NA

**Comment by ccssu** [comment]
> ### Describe the bug
> #### A clear and concise description of what the bug is.
> OneDiffCheckpointLoaderSimple cannot apply LoRa


This problem is caused by some parameters in onediff that do not support to ("CPU"), which is caused by changing the workflow process. The weight parameters have some to ("CPU") operations
Please use the `**-- gpu only**` parameter when starting comfyui to resolve the issue

`python main.py  --gpu-only` @lackofdream

**Comment by lackofdream** [comment]
with `--gpu-only`, lora node can be applied effectively, however after then removing the lora node cannot make the original model weights be restored (style of generated images still look like with lora applied)

**Comment by strint** [comment]
@ccssu @doombeaker

**Comment by strint** [comment]
Too old to follow, please feel free to reopen it if the problem still exists.
