### ISSUE TITLE
ComfyUI InstantID Error

### ISSUE THREAD

**Issue by xiecon** [siliconflow/onediff#719]
#### OS 
Linux

#### OneDiff git commit id
500459f7c0d02d177efad5c898f44c6cf518d0d1

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
path: ['/opt/conda/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240308+cu118
git_commit: 88ece9e
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):
启动ComfyUI：python main.py
按照教程按照环境：https://github.com/siliconflow/onediff/blob/main/onediff_comfy_nodes/workflows/ComfyUI_InstantID_OneDiff.md
load以上链接里的流程图

### The complete error message
W20240311 13:16:28.580902  1556 cuda_stream.cpp:49] Runtime version 8.7 of cuDNN incompatible with compiletime version 8.9.
[ERROR](GRAPH:OneflowGraph_0:OneflowGraph) run got error: <class 'oneflow._oneflow_internal.exception.Exception'> Cannot find the kernel matching Current OperatorConf.  The Info of OperatorConf are
 op_name: model.text_model.encoder.layers.1.self_attn-softmax-62
 op_type_name: softmax
 DeviceType_Name: kCPU
 DataType_Name of in_0: kFloat16
 DataType_Name of out_0: kFloat16
  File "oneflow/core/job/job_interpreter.cpp", line 312, in InterpretJob
    RunNormalOp(launch_context, launch_op, inputs)
  File "oneflow/core/job/job_interpreter.cpp", line 224, in RunNormalOp
    it.Apply(*op, inputs, &outputs, OpExprInterpContext(empty_attr_map, JUST(launch_op.device)))
  File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 155, in NaiveInterpret
    PhysicalRun([&](InstructionsBuilder* builder) -> Maybe ... output_eager_blob_objects), ctx, result->stream()); })
  File "oneflow/core/framework/instructions_builder.h", line 168, in PhysicalRun
    Build(&instructions_builder)
  File "oneflow/core/framework/instructions_builder.cpp", line 400, in Call
    vm::OpCallInstructionPolicy::New( vm_stream, opkernel ... global_tensor_infer_result, ctx, *one::CurrentDevVmDepObjectConsumeMode())
  File "oneflow/core/vm/op_call_instruction_policy.h", line 50, in New
    ptr->Init()
  File "oneflow/user/kernels/stateful_opkernel.cpp", line 920, in ChooseOpKernel
    user_op::UserOpRegistryMgr::Get().GetOpKernelRegistryResult(op_type_name, reg_ctx)
Error Type: oneflow.ErrorProto.op_kernel_not_found_error
Exception in __call__: e=Exception('Cannot find the kernel matching Current OperatorConf.  The Info of OperatorConf are \n op_name: model.text_model.encoder.layers.1.self_attn-softmax-62\n op_type_name: softmax\n DeviceType_Name: kCPU\n DataType_Name of in_0: kFloat16\n DataType_Name of out_0: kFloat16\n  File "oneflow/core/job/job_interpreter.cpp", line 312, in InterpretJob\n    RunNormalOp(launch_context, launch_op, inputs)\n  File "oneflow/core/job/job_interpreter.cpp", line 224, in RunNormalOp\n    it.Apply(*op, inputs, &outputs, OpExprInterpContext(empty_attr_map, JUST(launch_op.device)))\n  File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 155, in NaiveInterpret\n    PhysicalRun([&](InstructionsBuilder* builder) -> Maybe ... output_eager_blob_objects), ctx, result->stream()); })\n  File "oneflow/core/framework/instructions_builder.h", line 168, in PhysicalRun\n    Build(&instructions_builder)\n  File "oneflow/core/framework/instructions_builder.cpp", line 400, in Call\n    vm::OpCallInstructionPolicy::New( vm_stream, opkernel ... global_tensor_infer_result, ctx, *one::CurrentDevVmDepObjectConsumeMode())\n  File "oneflow/core/vm/op_call_instruction_policy.h", line 50, in New\n    ptr->Init()\n  File "oneflow/user/kernels/stateful_opkernel.cpp", line 920, in ChooseOpKernel\n    user_op::UserOpRegistryMgr::Get().GetOpKernelRegistryResult(op_type_name, reg_ctx)\nError Type: oneflow.ErrorProto.op_kernel_not_found_error')

**Comment by strint** [comment]
We have fixed this in oneflow. And the new oneflow version is on the way.

**Comment by xiecon** [comment]
请问有预期发布新版本的时间点吗？

**Comment by strint** [comment]
正在编译发布，好了我 at 你 @xiecon

**Comment by strint** [comment]
@xiecon 

已经发布，请更新 oneflow 到最新版本：https://github.com/siliconflow/onediff?tab=readme-ov-file#1-install-oneflow

**Comment by xiecon** [comment]
非常感谢
