### ISSUE TITLE
LyCORIS cannot be probably unfused

### ISSUE THREAD

**Issue by lackofdream** [siliconflow/onediff#723]
#### A clear and concise description of what the bug is.

in certain condition (see reproduce steps below), lora is still effective for generations afterwards even have the load lora node removed.

#### OS 
Linux
#### OneDiff git commit id
https://github.com/siliconflow/onediff/commit/22167094e6aad93ac3d38015d3fd932bccb0554b
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
path: ['/home/ubuntu/comfyui/venv/lib/python3.11/site-packages/oneflow']
version: 0.9.1.dev20240219+cu121
git_commit: 6621521
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
### How To Reproduce
Steps to reproduce the behavior(code or script):
1. generate images with lora, **make sure there is no cached compiled graph in comfyui/input/graphs directory**
[w1(2).json](https://github.com/siliconflow/onediff/files/14585111/w1.2.json)
![img_v3_028u_3a7e9f79-82e3-42c7-a62e-72edabccfb0h](https://github.com/siliconflow/onediff/assets/8641779/f5ddf549-ed42-467e-b867-891009169614)
2. generate images without lora
[w2(2).json](https://github.com/siliconflow/onediff/files/14585125/w2.2.json)
![img_v3_028u_fedeffc6-6ca9-417c-bc39-600d3e6dc45h](https://github.com/siliconflow/onediff/assets/8641779/b796005f-a48d-4af7-920a-b88914b20eb7)

the output of onediff accelerated model looks like be affected by lora in the previous generation

### The complete error message
NA

**Comment by strint** [comment]
Thanks, get it!

**Comment by strint** [comment]
Set the env var ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION to 0 with
```
export ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION=0
```

Ref: [onediff/onediff_diffusers_extensions at main · siliconflow/onediff](https://github.com/siliconflow/onediff/tree/main/onediff_diffusers_extensions#note)
