### ISSUE TITLE
SDXL Loras fail to load if they contain weights for both text encoders

### ISSUE THREAD

**Issue by jfischoff** [siliconflow/onediff#731]
#### A clear and concise description of what the bug is.

This check (https://github.com/siliconflow/onediff/blob/cf16776063542948e5cec303abb8eef24d80b801/onediff_diffusers_extensions/onediffx/lora/unet.py#L56C1-L59C7)

```
    if all(
        key.startswith(cls.unet_name) or key.startswith(cls.text_encoder_name)
        for key in keys
    ):
```

Fails if the lora has keys for the second text encoder which recent `diffusers` scripts prefix with `text_encoder_2`. 

The `diffusers` `StableDiffusionXLLoraLoaderMixin` has special logic to handle this: https://github.com/huggingface/diffusers/blob/5d848ec07c2011d600ce5e5c1aa02a03152aea9b/src/diffusers/loaders/lora.py#L1250-L1275

```
self.load_lora_into_unet(
            state_dict, network_alphas=network_alphas, unet=self.unet, adapter_name=adapter_name, _pipeline=self
        )
        text_encoder_state_dict = {k: v for k, v in state_dict.items() if "text_encoder." in k}
        if len(text_encoder_state_dict) > 0:
            self.load_lora_into_text_encoder(
                text_encoder_state_dict,
                network_alphas=network_alphas,
                text_encoder=self.text_encoder,
                prefix="text_encoder",
                lora_scale=self.lora_scale,
                adapter_name=adapter_name,
                _pipeline=self,
            )

        text_encoder_2_state_dict = {k: v for k, v in state_dict.items() if "text_encoder_2." in k}
        if len(text_encoder_2_state_dict) > 0:
            self.load_lora_into_text_encoder(
                text_encoder_2_state_dict,
                network_alphas=network_alphas,
                text_encoder=self.text_encoder_2,
                prefix="text_encoder_2",
                lora_scale=self.lora_scale,
                adapter_name=adapter_name,
                _pipeline=self,
            )
```

I think part of the fix is changing the initial check to look for the `text_encoder_2` prefix as well.

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by strint** [comment]
@jfischoff what is your HF diffusers version?

cc @marigoold

**Comment by strint** [comment]
@jfischoff can you provide a case to reproduce this?

**Comment by strint** [comment]
too old to track, feel free to re-open it if you still care about this.
