### ISSUE TITLE
相同结构checkpoint切换支持仅更新权重，不用重新warmup

### ISSUE THREAD

**Issue by philipy1219** [siliconflow/onediff#737]
目前相同结构的checkpoint，例如同样是SDXL模型，如果切换模型，需要再次warmup，切换时间较长。阿里云的AIACC，支持comfyui和webui切换模型时仅更新权重，这样加速模式能更快生效，且转换后模型权重可以导出，之后可随时导入。建议加入切换checkpoint仅更新权重的功能。

**Comment by strint** [comment]
类似功能的 issue：https://github.com/siliconflow/onediff/issues/581

**Comment by strint** [comment]
Related PR: https://github.com/siliconflow/onediff/pull/742

**Comment by strint** [comment]
已经完成了支持。
