### ISSUE TITLE
ModuleNotFoundError: No module named 'onediff_quant'

### ISSUE THREAD

**Issue by GuangyanZhang** [siliconflow/onediff#747]
## 按照reade.md步骤安装，
* 安装版本：
   * onediff                  0.13.0.dev1           
   * onediffx                 0.13.0.dev0   
   * cuda 12.1          
* 执行：
` cd onediff_diffusers_extensions
python3 examples/text_to_image.py` 成功
* 执行:https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/tools/quantization/quantize-svd-fast.py这个脚本出现 ModuleNotFoundError: No module named 'onediff_quant'，
* 求教怎么才能得到onediff_qaunt这个库，是否我的安装步骤哪里不对。

**Comment by strint** [comment]
> ## 按照reade.md步骤安装，
> * 安装版本：
>   
>   * onediff                  0.13.0.dev1
>   * onediffx                 0.13.0.dev0
>   * cuda 12.1
> * 执行：
>   ` cd onediff_diffusers_extensions python3 examples/text_to_image.py` 成功
> * 执行:[https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/tools/quantization/quantize-svd-fast.py这个脚本出现](https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/tools/quantization/quantize-svd-fast.py%E8%BF%99%E4%B8%AA%E8%84%9A%E6%9C%AC%E5%87%BA%E7%8E%B0) ModuleNotFoundError: No module named 'onediff_quant'，
> * 求教怎么才能得到onediff_qaunt这个库，是否我的安装步骤哪里不对。

因为 quantize-svd-fast.py 这个是企业版的功能：https://github.com/siliconflow/onediff?tab=readme-ov-file#onediff-enterprise-edition

**Comment by strint** [comment]
> 企业版的啥时候可以开源呢

所有的功能和通用性能优化都在社区版了。这些通用性能优化在整个性能增益的占比一般是 75%。一般社区版（完全免费）就足够使用了。

还有一部分模型专用的性能优化，在整个性能增益的占比一般是 25%。如果您对这部分性能有极致的需求，可以选择购买企业版。（我们希望通过企业版获取一些正向收入来发展）
