### ISSUE TITLE
关于加速后生成图像质量变差的问题

### ISSUE THREAD

**Issue by lovejing0306** [siliconflow/onediff#752]
# Describe the bug
使用 onediff 加速之后，生成图像质量变差。请问有什么解决的办法吗？详细对比如下：

加速前生成图像
![base-0_0](https://github.com/siliconflow/onediff/assets/14770340/d5235296-907c-4536-b140-4d4c77ba93bc)

加速后生成图像
![base-0_0-onediff](https://github.com/siliconflow/onediff/assets/14770340/34f94863-8a38-4db6-be82-f6c1b3f9cfe7)

生成变差的区域（红色圈中的地方）
![Xnip2024-03-22_16-51-30](https://github.com/siliconflow/onediff/assets/14770340/0622ea67-cdd8-4487-9074-1cd97a1755aa)

**Comment by strint** [comment]
可以提供下复现问题的代码么，这个需要能复现才好办

**Comment by hjchen2** [comment]
可以设置环境变量ONEFLOW_CONV_ALLOW_HALF_PRECISION_ACCUMULATION=0和ONEFLOW_MATMUL_ALLOW_HALF_PRECISION_ACCUMULATION=0再试试，设置之后对于conv和linear，onediff会采用更高精度的计算方式

**Comment by lovejing0306** [comment]
> 可以设置环境变量ONEFLOW_CONV_ALLOW_HALF_PRECISION_ACCUMULATION=0和ONEFLOW_MATMUL_ALLOW_HALF_PRECISION_ACCUMULATION=0再试试，设置之后对于conv和linear，onediff会采用更高精度的计算方式

但这样设置之后，后影响推理速度吗？

**Comment by strint** [comment]
> > 可以设置环境变量ONEFLOW_CONV_ALLOW_HALF_PRECISION_ACCUMULATION=0和ONEFLOW_MATMUL_ALLOW_HALF_PRECISION_ACCUMULATION=0再试试，设置之后对于conv和linear，onediff会采用更高精度的计算方式
> 
> 但这样设置之后，后影响推理速度吗？

预估影响 5% 的性能，
可以试下，看能否解决问题。

**Comment by lovejing0306** [comment]
> > > 可以设置环境变量ONEFLOW_CONV_ALLOW_HALF_PRECISION_ACCUMULATION=0和ONEFLOW_MATMUL_ALLOW_HALF_PRECISION_ACCUMULATION=0再试试，设置之后对于conv和linear，onediff会采用更高精度的计算方式
> > 
> > 
> > 但这样设置之后，后影响推理速度吗？
> 
> 预估影响 5% 的性能，可以试下，看能否解决问题。

试了你说的这种方案，得到了改善，但还会有一些差异。这个还有进一步的提升方案吗？

没有添加环境变量的结果：
![base-0_0-onediff-before](https://github.com/siliconflow/onediff/assets/14770340/ffc3d363-5d4c-4877-b9a1-b6ac1a872ff9)

添加环境变量之后的结果：
![base-0_0-onediff](https://github.com/siliconflow/onediff/assets/14770340/4dd7c99b-c9fd-4e39-9ecd-2e805611fa36)

**Comment by strint** [comment]
确实改善了，现在哪里还有差异呢

**Comment by lovejing0306** [comment]
> 确实改善了，现在哪里还有差异呢

现在就剩下颜色上的差异了，可以把我上传的 “加速前生成图像”图像和 “添加环境变量之后的结果”图像 下载到本地，切换着看下，就能发现差异了。

**Comment by strint** [comment]
https://github.com/siliconflow/OneDiffGenMetrics

**Comment by strint** [comment]
conv  kernel diff: oneflow  vs torch cuda v8 api

**Comment by lovejing0306** [comment]
> conv  kernel diff: oneflow  vs torch cuda v8 api


👌，感谢回复

**Comment by lovejing0306** [comment]
> 另外因为 torch 不同版本的 conv 也会带来写差异，比如 conv kernel cuda v8 api
> 
> pytorch的cudnn_convolution计算函数从v7（调用cudnnConvolutionForward，与oneflow一致）更新到了v8（调用cudnnBackendExecute），默认为v8版本
> 
> ![image](https://github.com/Oneflow-Inc/OneTeam/assets/56420840/a76d7e98-431f-4506-9b7a-fd8567b83a48)
> 
> 设置TORCH_CUDNN_V8_API_DISABLED=1后pytorch和oneflow的计算结果一致
> 
> (https://github.com/Oneflow-Inc/OneTeam/issues/2198)

辛苦再给看下这个问题 https://github.com/siliconflow/onediff/issues/762

**Comment by csdY123** [comment]
![20240412-174323](https://github.com/siliconflow/onediff/assets/104352566/01a60be9-8daf-475a-bcf9-2f09d7a7af44)
求问为什么使用onediff生图效果很模糊

**Comment by lixiang007666** [comment]
> ![20240412-174323](https://private-user-images.githubusercontent.com/104352566/321939938-01a60be9-8daf-475a-bcf9-2f09d7a7af44.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjIyMDcsIm5iZiI6MTcxMjkyMTkwNywicGF0aCI6Ii8xMDQzNTI1NjYvMzIxOTM5OTM4LTAxYTYwYmU5LThkYWYtNDc1YS1iY2Y5LTJmMDlkN2E3YWY0NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxMTM4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWViZWNkN2IzMzM5ODBjMjQzOTBjN2Y0NDVhZmU4ZTU1YTY1NTRjZTlkZDMzZjFjMTIyY2FmMTI1NjgxNGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.495YYr42-Z994PRvHcOvf83sMpoJZX8jnXDLYluCA7I) 求问为什么使用onediff生图效果很模糊

能否提供可以复现的代码以及 prompt（可用于对比）？

**Comment by csdY123** [comment]
> > ![20240412-174323](https://private-user-images.githubusercontent.com/104352566/321939938-01a60be9-8daf-475a-bcf9-2f09d7a7af44.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjIyMDcsIm5iZiI6MTcxMjkyMTkwNywicGF0aCI6Ii8xMDQzNTI1NjYvMzIxOTM5OTM4LTAxYTYwYmU5LThkYWYtNDc1YS1iY2Y5LTJmMDlkN2E3YWY0NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxMTM4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWViZWNkN2IzMzM5ODBjMjQzOTBjN2Y0NDVhZmU4ZTU1YTY1NTRjZTlkZDMzZjFjMTIyY2FmMTI1NjgxNGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.495YYr42-Z994PRvHcOvf83sMpoJZX8jnXDLYluCA7I) 求问为什么使用onediff生图效果很模糊
> 
> 能否提供可以复现的代码以及 prompt（可用于对比）？
from compel import Compel, ReturnedEmbeddingsType
import time
from onediffx import compile_pipe, save_pipe, load_pipe
from onediffx.deep_cache import StableDiffusionXLPipeline

base_model_path = "playground-v2.5-1024px-aesthetic"
base_model_name = base_model_path.split("/")[-1]

pipe = StableDiffusionXLPipeline.from_pretrained(
    base_model_path,
    torch_dtype=torch.float16,
    variant="fp16",
).to("cuda")

compel = Compel(
    tokenizer=[pipe.tokenizer, pipe.tokenizer_2],
    text_encoder=[pipe.text_encoder, pipe.text_encoder_2],
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=[False, True],
    truncate_long_prompts=False,
)

pipe = compile_pipe(pipe)
if os.path.exists(f"cached_pipe_{base_model_name}"):
    load_pipe(pipe, f"cached_pipe_{base_model_name}")
else:
    prompt = "A photo of a cat. Focus light and create sharp, defined edges."
    # Warmup
    for i in range(1):
        deepcache_output = pipe(
            prompt,
            cache_interval=3,
            cache_layer_id=0,
            cache_block_id=0,
            output_type="pil",
        ).images[0]

if not os.path.exists(f"cached_pipe_{base_model_name}"):
    save_pipe(pipe, dir=f"cached_pipe_{base_model_name}")
logger.info("Pipeline compiled successfully.")

**Comment by csdY123** [comment]
> 另外，我尝试了SDXL Base出现了模糊，但是使用playground-v2.5-1024px-aesthetic不会出现模糊。
> 使用的版本是2.2.0+cu118

@strint 您好，方便的话能把pytorch版本、cuda版本等关键配置信息分享一下吗？ 我们希望至少能跑通SDXL Base

**Comment by strint** [comment]
> > 另外，我尝试了SDXL Base出现了模糊，但是使用playground-v2.5-1024px-aesthetic不会出现模糊。
> > 使用的版本是2.2.0+cu118
> 
> @strint 您好，方便的话能把pytorch版本、cuda版本等关键配置信息分享一下吗？ 我们希望至少能跑通SDXL Base

你用的 prompt 和种子是什么，我们看能否复现你这个问题。如果有代码更好

**Comment by strint** [comment]
torch.__version__ '2.1.1'
CUDA Version: 12.2 

@csdY123

**Comment by hjchen2** [comment]
deepcache是有损的，可能导致模糊的问题，请去掉下面这些参数关掉deepcache关掉再试。
```
cache_interval=3,
cache_layer_id=0,
cache_block_id=0,
```

**Comment by csdY123** [comment]
> torch.**version** '2.1.1' CUDA Version: 12.2
> 
> @csdY123

非常感谢！！！另外，请问deepcache是使用了int8推理吗

**Comment by csdY123** [comment]
> 有损的，可能导致模糊的问题，请去掉下面这些参数关掉

非常感谢，deepcache是使用了int8推理吗

**Comment by csdY123** [comment]
> > > 另外，我尝试了SDXL Base出现了模糊，但是使用playground-v2.5-1024px-aesthetic不会出现模糊。
> > > 使用的版本是2.2.0+cu118
> > 
> > 
> > @strint 您好，方便的话能把pytorch版本、cuda版本等关键配置信息分享一下吗？ 我们希望至少能跑通SDXL Base
> 
> 你用的 prompt 和种子是什么，我们看能否复现你这个问题。如果有代码更好





prompt="silhouette style manga style "A cluttered garage with a worn-out couch where a muscular college student, identified as Dante, is seated, strumming an untuned bass guitar. His expression is focused yet frustrated. The side door of the garage is slightly ajar. He seems to have missed noticing a departing figure - suggested by a retreating back view of a character just outside the side door." . vibrant, high-energy, detailed, iconic, Japanese comic style . colorful, high contrast, minimalistic, stark, dramatic 
"
种子是随机的，没记录，但是都挺模糊；
该prompt效果是：
<img width="768" alt="1713418336682" src="https://github.com/siliconflow/onediff/assets/104352566/55b6bc74-950d-4fd9-a323-468808a43ae2">
代码上面已经提到

**Comment by CuddleSabe** [comment]
> > 有损的，可能导致模糊的问题，请去掉下面这些参数关掉
> 
> 非常感谢，deepcache是使用了int8推理吗

deepcache会跳步
