### ISSUE TITLE
SVD multi resolution not working as expected?

### ISSUE THREAD

**Issue by ShaunXZ** [siliconflow/onediff#753]
I'm testing  ./benchmarks/image_to_video.py with --alter-height 1024 --alter-width 1024

the following error occured at the second loop (alt resolution):
![image](https://github.com/siliconflow/onediff/assets/44222184/711bbc12-137d-43a7-8375-45380ac61e78)

I also noticed a warning at the start but I am not sure if that's the reason: 
![image](https://github.com/siliconflow/onediff/assets/44222184/1011029c-2e1e-4ec1-8bcc-6524b8780f9b)

Should i upgrade cuDNN library?

**Comment by clackhan** [comment]
https://github.com/siliconflow/onediff/pull/754

@ShaunXZ problem solved in this PR https://github.com/siliconflow/onediff/pull/754 . you can wait the pr merged and then update the code. Or you can downgrade diffusers to no higher than v0.25.1.
