### ISSUE TITLE
Can't install the nodes for Comfyui

### ISSUE THREAD

**Issue by meer007-cmd** [siliconflow/onediff#765]
I tried the manager and scripts it shows up as red in Comfyui, I've done the steps and downloaded Onediff but still won't work.

Windows, cuda= 12.4, pip= 3.12

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "D:\Lib\site-packages\oneflow\__init__.py", line 21, in <module>
    raise RuntimeError("This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow")
RuntimeError: This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow
![Screenshot 2024-03-27 040607](https://github.com/siliconflow/onediff/assets/154732481/2c8cb644-f912-4309-a3b1-8897d4f081d1)

**Comment by strint** [comment]
What python version are you using? We only support 3.8~3.11 for now. @meer007-cmd
