### ISSUE TITLE
There is no acceleration after compiling

### ISSUE THREAD

**Issue by HuiZhang0812** [siliconflow/onediff#767]
####  OneFlow version info
path: ['/root/anaconda3/envs/onediff/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240322+cu122
git_commit: 0523481
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
`self.pipe.unet = compile_pipe(self.pipe.unet)`
`self.pipe.controlnet = compile_pipe(self.pipe.controlnet)`
`self.pipe.vae = compile_pipe(self.pipe.vae)`

### The complete error message
N/A
### Additional context
Could it be related to this reason?
`W20240327 10:21:25.513151   715 cuda_stream.cpp:49] Runtime version 12.1 of cuBLAS incompatible with compiletime version 12.2.`
`W20240327 10:21:25.517294   715 cuda_stream.cpp:49] Runtime version 8.5 of cuDNN incompatible with compiletime version 8.9.`

**Comment by balusch** [comment]
Hello! I'm faced with the same error and I wonder whether you have solved it or not, or have any progress to share.

```txt
W20240401 15:49:59.943140 180046 cuda_stream.cpp:49] Runtime version 11.10 of cuBLAS incompatible with compiletime version 11.11.
W20240401 15:50:00.209537 180046 cuda_stream.cpp:49] Runtime version 8.5 of cuDNN incompatible with compiletime version 8.9.
```

I use transformers-4.27.1 and diffusers-0.26.2 to run [stabilityai/stable-diffusion-xl-base-1.0](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0) on a  machine with a T4 card and with CUDA-12.0 installed. Here is my onediff version:

```shell
$ python -m oneflow --doctor
path: ['/path/to/.venv/lib64/python3.9/site-packages/oneflow']
version: 0.9.1.dev20240329+cu118
git_commit: 4ed3138
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```

P.S. I tried to install cu120, which should have been conformed to my CUDA, but failed to run the program:

```txt
    from oneflow.mock_torch import DynamicMockModule
ImportError: cannot import name 'DynamicMockModule' from 'oneflow.mock_torch' (/path/to/.venv/lib64/python3.9/site-packages/oneflow/mock_torch/__init__.py)
```

So I installed cu118 instead. Don't know whether it is related to this issue.

**Comment by strint** [comment]
architecture under 8.0 will not get much performance gain. onediff support acceleration for architecture >= 8.0(RTX 3090, RTX 4090, A10, A100).

![img_v3_029e_cd3e3fef-a411-412c-aa4d-21e17cb1df0g](https://github.com/siliconflow/onediff/assets/3468789/1c4a099c-5b23-47c7-9a2f-c8ece24c6f96)

@balusch

**Comment by strint** [comment]
@HuiZhang0812 What GPU type are you testing on ?

**Comment by strint** [comment]
Too old to track. Feel free to re-open this issue.

**Comment by liho00** [comment]
ImportError: cannot import name 'DynamicMockModule'
same issue here, im using CUDA 12.4
GPU RTX A6000

**Comment by strint** [comment]
> ImportError: cannot import name 'DynamicMockModule' same issue here, im using CUDA 12.4 GPU RTX A6000

@liho00 what command are you using to install oneflow

and please use `python -m oneflow --doctor` to get the version info here
