### ISSUE TITLE
input tensor count changed from 5 to 15, will compile again.

### ISSUE THREAD

**Issue by onefish51** [siliconflow/onediff#769]
### Describe the bug
When trying to accelerate ControlNet inference based on Stable Diffusion XL using OneDiff in ComfyUI, I found that modifying the end_percent parameter of the ControlNet module to a value other than 1 would result in the warning `input tensor count changed from 5 to 15, will compile again`, which in turn caused the inference time to increase several times.

### Your environment
```bash
Ubuntu 20.04.6 LTS
```

#### OneDiff git commit id
```bash
Building wheels for collected packages: onediff
  Building editable for onediff (pyproject.toml) ... done
  Created wheel for onediff: filename=onediff-0.13.0.dev1-0.editable-py3-none-any.whl size=4787 sha256=da96d22b3584c066b08cb27f6b0848deac7b1ed6762599ec2dca11fb586c6cfa
  Stored in directory: /tmp/pip-ephem-wheel-cache-imdef35k/wheels/dc/92/1a/af52ecdd4b6e7016f14cbfb5e19f730049e3acf1f65ba7a776
Successfully built onediff
Installing collected packages: onediff
  Attempting uninstall: onediff
    Found existing installation: onediff 0.13.0.dev1
    Uninstalling onediff-0.13.0.dev1:
      Successfully uninstalled onediff-0.13.0.dev1
Successfully installed onediff-0.13.0.dev1
```
####  OneFlow version info
```bash
libibverbs not available, ibv_fork_init skipped
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
path: ['/opt/conda/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240125+cu121
git_commit: 6458a12
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```
### How To Reproduce
comfyui workflow:
[workflow_xl_controlnet_onediff_end.json](https://github.com/siliconflow/onediff/files/14769150/workflow_xl_controlnet_onediff_end.json)

### The complete error message
```bash
Module <class 'onediff.infer_compiler.transform.builtin_transform.<class 'register_comfy.openaimodel.UNetModel'>'> input tensor count changed from 15 to 5, will compile again.
```

**Comment by strint** [comment]
> input tensor count changed from 5 to 15, will compile again

Yes. This is as expected. This means the computation logic is changed (input tensor number changed), so the optimized graph can't be reused.

This is not tensor shape change (dynamic resolution), but tensor number change, which is really hard to reuse the graph for now.

**Comment by onefish51** [comment]
OK，Thank you for your prompt response.

**Comment by onefish51** [comment]
I tried it, and modifying the strength value of ControlNet does not cause recompilation. So if the end_percent value is 0.5, and the steps for the KSampler is 20, then the KSampler can be split into two parts. For the first 10 steps, the ControlNet strength value is 1, and for the last 10 steps, the ControlNet strength value is 0.

**Comment by strint** [comment]
We have noticed that the ControlNet strength value are 1 and 0 will cause different input numbers of the contronet.

**Comment by strint** [comment]
Can this issue be worked around in your workflow?

**Comment by onefish51** [comment]
> We have noticed that the ControlNet strength value are 1 and 0 will cause different input numbers of the contronet.

yes，When the ControlNet strength value is changed from 1 to 0, the UNetModel will compile again.
```bash
ot prompt
100%|████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.20it/s]
Prompt executed in 3.29 seconds
got prompt
  0%|                                                                                                     | 0/20 [00:00<?, ?it/s]Module <class 'onediff.infer_compiler.transform.builtin_transform.<class 'register_comfy.openaimodel.UNetModel'>'> input tensor count changed from 5 to 15, will compile again.
Building a graph for <class 'register_comfy.openaimodel.UNetModel'> ...
Loaded graph file: ComfyUI/input/graphs/sdxl.safetensors/SDXL_197b3748b9_15_d49b38b94f4fed9182c93c794e730e2a108f7a2b7b8d89f1e2adceb7d1033381_0.9.1.dev20240125+cu121.graph
100%|████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.34it/s]
Prompt executed in 7.08 seconds
```
The solution to fix this problem is to comment out the section of 
https://github.com/siliconflow/onediff/blob/ef732fa7db27a7c729c38274a83a37e4a10dc289/onediff_comfy_nodes/modules/hijack_nodes.py#L44

from
```python
if strength == 0:
        return (positive, negative)
    control_hint = image.movedim(-1, 1)
    cnets = {}
```
to
```python
# if strength == 0:
    #     return (positive, negative)
    control_hint = image.movedim(-1, 1)
    cnets = {}
```
Of course, this will introduce a new problem. When `strength == 0`, the generated results will have slight differences, with other parameters fixed.
![image](https://github.com/siliconflow/onediff/assets/21029719/02b5f096-f46b-4bfc-88a4-90e1664244df)
![image](https://github.com/siliconflow/onediff/assets/21029719/e97d780a-1d42-48f7-afe3-31d55373a124)

**Comment by strint** [comment]
If your model is sensitive to optimization, you can try to follow this issue to disable some optimization: https://github.com/siliconflow/onediff/issues/752
