### ISSUE TITLE
how to install onediff for cuda11.7

### ISSUE THREAD

**Issue by liuchenbaidu** [siliconflow/onediff#776]
#### OS 
unbuntu 22.04

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

### Additional context

when i want use for cuda11.7 
i don't get how to intall 

when i run it for accelerated inference for InstantID
1、python3 -m pip install -U --pre oneflow -f https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu118
2、from source installing

it all give error :
    import oneflow._oneflow_internal
ImportError: libcudnn_cnn_infer.so.8: cannot open shared object file: No such file or directory

**Comment by jackalcooper** [comment]
```
nvidia-cudnn-cu11
nvidia-cublas-cu11
nvidia-nccl-cu11
nvidia-cusparse-cu11
nvidia-cufft-cu11
```
- make sure these pip packages are installed (they should be automatically installed as oneflow's dependency when oneflow is installed)
- make sure the shared libraries of these packages can be found by current environment

**Comment by strint** [comment]
> ImportError: libcudnn_cnn_infer.so.8: cannot open shared object file: No such file or directory

Please try
```
pip install nvidia-cudnn-cu11
```
or
```
sudo apt-get install libcudnn8
```
