### ISSUE TITLE
from onediffx import compile_pipe ModuleNotFoundError: No module named 'onediffx'

### ISSUE THREAD

**Issue by liuchenbaidu** [siliconflow/onediff#783]
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by clackhan** [comment]
@liuchenbaidu You need to install onediffx separately.

#### from pypi
```
python3 -m pip install --pre onediffx
```

#### from source
```
git clone https://github.com/siliconflow/onediff.git
cd onediff/onediff_diffusers_extensions && python3 -m pip install -e . 
```
