### ISSUE TITLE
compared the output results of acceleration schemes from both the deepcache and onediff versions

### ISSUE THREAD

**Issue by onefish51** [siliconflow/onediff#789]
### Describe the bug
I compared the output results of acceleration schemes from both the deepcache and onediff versions, and found that typically, the deepcache version produces lower quality images, with a greater tendency to exhibit malformed hands and legs, as well as peculiar color blocks displaying abrupt transitions. These issues are particularly pronounced when the generated images have an aspect ratio other than 1:1, specifically in the case of a 9:21 ratio.

### Your environment
```bash
Ubuntu 20.04.6 LTS
```

#### OneDiff git commit id
```bash
Building wheels for collected packages: onediff
  Building editable for onediff (pyproject.toml) ... done
  Created wheel for onediff: filename=onediff-0.13.0.dev1-0.editable-py3-none-any.whl size=5365 sha256=672b46d89c4cde6bd23e818a3694e9c3f8e9bc3593beb1f7c1bc7671638697c2
  Stored in directory: /tmp/pip-ephem-wheel-cache-sup957_q/wheels/01/30/ea/6d3fee7612e410bc7ccd7c32f1cd929ab8930caa0fec1c256b
Successfully built onediff
Installing collected packages: onediff
  Attempting uninstall: onediff
    Found existing installation: onediff 0.13.0.dev1
    Uninstalling onediff-0.13.0.dev1:
      Successfully uninstalled onediff-0.13.0.dev1
Successfully installed onediff-0.13.0.dev1
```
####  OneFlow version info
```bash
libibverbs not available, ibv_fork_init skipped
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
path: ['/opt/conda/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240125+cu121
git_commit: 6458a12
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```
### How To Reproduce
[workflow_compare.json](https://github.com/siliconflow/onediff/files/14896460/workflow_compare.json)

### The output results of acceleration schemes from both the deepcache and onediff versions
![image](https://github.com/siliconflow/onediff/assets/21029719/99ce7b2c-7fad-4732-88e6-3b88024ca81e)
![image](https://github.com/siliconflow/onediff/assets/21029719/f3c707c6-cc04-48bd-85f8-670645eef015)
![image](https://github.com/siliconflow/onediff/assets/21029719/24ace124-7919-4f8a-ac2d-184e76e30edf)
![image](https://github.com/siliconflow/onediff/assets/21029719/d01cd958-bc41-4cbd-9443-26f24a17ef89)
![image](https://github.com/siliconflow/onediff/assets/21029719/3767068b-7164-49f4-9092-fa999f38a3a1)
![image](https://github.com/siliconflow/onediff/assets/21029719/7ff3ec95-f128-4814-b8ef-80ca9ac77d37)
![image](https://github.com/siliconflow/onediff/assets/21029719/f6de021c-440a-43a5-b44c-c490dd652e94)
![image](https://github.com/siliconflow/onediff/assets/21029719/104f1047-1586-4d45-85b2-6587eb475121)

### add several examples of anomalies for the deepcache
![6121712480753_ pic](https://github.com/siliconflow/onediff/assets/21029719/7d356f91-f6bf-4fe7-9759-21eeb6fea688)@w=200h=100
![6101712480750_ pic](https://github.com/siliconflow/onediff/assets/21029719/d5140396-c103-4b51-9d5e-469efae80d72)
![promeai_00017_](https://github.com/siliconflow/onediff/assets/21029719/8c17e131-037b-45c3-b8f2-69e9a5968cec)
![6111712480753_ pic](https://github.com/siliconflow/onediff/assets/21029719/6058fd0b-2b07-4551-b267-2441cb22af6b)
![promeai_00018_](https://github.com/siliconflow/onediff/assets/21029719/9f1403aa-a2bc-4406-ac52-deaad304d972)

**Comment by strint** [comment]
Thanks @onefish51 

How many steps are you using? Seems that  deepcache is not woking well with little steps( less than 30)

**Comment by clackhan** [comment]
@onefish51  Deepcache is a lossy algorithm. If you want to be close to the original algorithm, you can adjust cache_interval to a smaller value, or adjust cache_layer_id and cache_block_id to larger values.

**Comment by onefish51** [comment]
> Thanks @onefish51
> 
> How many steps are you using? Seems that deepcache is not woking well with little steps( less than 30)

as the workflow shown "20 steps"
[workflow_compare.json](https://github.com/siliconflow/onediff/files/14994799/workflow_compare.json)
