### ISSUE TITLE
 convert <class 'function'> failed: Transform failed of <class 'function'>: 'function' object has no attribute '<locals>'

### ISSUE THREAD

**Issue by neiltian-tencent** [siliconflow/onediff#797]
debug info:
1. singledispatch_proxy wrapper first_param:  <function ProxySubmodule.__getattribute__.\<locals\>.\<lambda\> at 0x7fedb8479ab0>
2. MockEntityNameFormatter _format_full_class_name: onediff.infer_compiler.transform.builtin_transform.ProxySubmodule.__getattribute__.\<locals\>.\<lambda\>

error info:
onediff/src/onediff/infer_compiler/transform/builtin_transform.py:233 - convert <class 'function'> failed: Transform failed of <class 'function'>: 'function' object has no attribute '<locals>'

funciton info:  
<function ProxySubmodule.__getattribute__ at 0x7fedb847fe20>

**Comment by doombeaker** [comment]
could you tell me, which model are you trying to convert by onediff?

it may be caused some closure feature of python

**Comment by neiltian-tencent** [comment]
@doombeaker I try to find an open source demo. Error related codes:
def __getattribute__(self, attribute) (onediff/src/onediff/infer_compiler/transform/builtin_transform.py)
       elif attribute in ["forward", "_conv_forward"]:
            replacement = proxy_class(type(self._oflow_proxy_submod))
            return lambda *args, **kwargs: getattr(replacement, attribute)(
                self, *args, **kwargs
            )

**Comment by neiltian-tencent** [comment]
@doombeaker https://github.com/MooreThreads/Moore-AnimateAnyone demo has similar errors.

**Comment by neiltian-tencent** [comment]
@doombeaker could you tell me, how to fix this issue?  first of all,  do i need to redefine the corresponding oneflow class and register it based on the register interface? （https://github.com/MooreThreads/Moore-AnimateAnyone/tree/master/src/models）

**Comment by neiltian-tencent** [comment]
error info:  TemporalBasicTransformerBlock module's forward interface is hijacked by hacked_basic_transformer_inner_forward.(https://github.com/MooreThreads/Moore-AnimateAnyone/blob/master/src/models/mutual_self_attention.py)  
does oneflow support this situation？ @strint @doombeaker

**Comment by neiltian-tencent** [comment]
TemporalBasicTransformerBlock module's forward is not hijacked(reference_attn is False), 
oneflow can execute the compile process despite the following error.  (https://github.com/MooreThreads/Moore-AnimateAnyone/blob/master/src/models/mutual_self_attention.py)
[ERROR](GRAPH:OneflowGraph_1:OneflowGraph) run got error: <class 'oneflow._oneflow_internal.exception.Exception'> Cannot find the kernel matching Current OperatorConf.  The Info of OperatorConf are 
 op_name: model.up_blocks.0.upsamplers.0-upsample_nearest_3d-1965
 op_type_name: upsample_nearest_3d
 DeviceType_Name: kCUDA
 DataType_Name of x_0: kFloat16
 DataType_Name of y_0: kFloat16
  File "oneflow/core/job/job_interpreter.cpp", line 326, in InterpretJob
    RunNormalOp(launch_context, launch_op, inputs)
  File "oneflow/core/job/job_interpreter.cpp", line 238, in RunNormalOp
    it.Apply(*op, inputs, &outputs, OpExprInterpContext(empty_attr_map, JUST(launch_op.device)))
  File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 155, in NaiveInterpret
    PhysicalRun([&](InstructionsBuilder* builder) -> Maybe ... output_eager_blob_objects), ctx, result->stream()); })
  File "oneflow/core/framework/instructions_builder.h", line 168, in PhysicalRun
    Build(&instructions_builder)
  File "oneflow/core/framework/instructions_builder.cpp", line 400, in Call
    vm::OpCallInstructionPolicy::New( vm_stream, opkernel ... global_tensor_infer_result, ctx, *one::CurrentDevVmDepObjectConsumeMode())
  File "oneflow/core/vm/op_call_instruction_policy.h", line 50, in New
    ptr->Init()
  File "oneflow/user/kernels/stateful_opkernel.cpp", line 920, in ChooseOpKernel
    user_op::UserOpRegistryMgr::Get().GetOpKernelRegistryResult(op_type_name, reg_ctx)
Error Type: oneflow.ErrorProto.op_kernel_not_found_error

**Comment by doombeaker** [comment]
@wangerlie is working on it, and will let you know if there is any progress

**Comment by zhangvia** [comment]
hey,are you trying to use the onediff to accelerate the animate anyone? i'm also working on it. and i find that the torch2.2.0 + torch.compile + cudnn8.6 will speed up animate anyone about 30%. but it is really weird that if i run the pipeline consecutively twice，the second result is completely the same as the first result even if i change the reference image of second execution.

so i try to use onediff, and ```Transform failed of <class 'function'>: 'function' object has no attribute '<locals>'``` error happens

**Comment by neiltian-tencent** [comment]
> hey,are you trying to use the onediff to accelerate the animate anyone? i'm also working on it. and i find that the torch2.2.0 + torch.compile + cudnn8.6 will speed up animate anyone about 30%. but it is really weird that if i run the pipeline consecutively twice，the second result is completely the same as the first result even if i change the reference image of second execution.
> 
> so i try to use onediff, and `Transform failed of <class 'function'>: 'function' object has no attribute '<locals>'` error happens

@zhangvia torch.compile  dynamic=True?

**Comment by zhangvia** [comment]
my denoising unet takes fixed shape latent as input, and i don't use torch.compile to compile the referencenet,because the pipeline only run referencenet once when generate video.

**Comment by zhangvia** [comment]
sorry the bug is still here when set dynamic=true. but if i set os.environ['TORCH_LOGS']="recompiles", the bug disappear

**Comment by neiltian-tencent** [comment]
> @strint @doombeaker TemporalBasicTransformerBlock module's forward is not hijacked(reference_attn is False), oneflow can execute the compile process despite the following error. (https://github.com/MooreThreads/Moore-AnimateAnyone/blob/master/src/models/mutual_self_attention.py) ERROR run got error: <class 'oneflow._oneflow_internal.exception.Exception'> Cannot find the kernel matching Current OperatorConf. The Info of OperatorConf are op_name: model.up_blocks.0.upsamplers.0-upsample_nearest_3d-1965 op_type_name: upsample_nearest_3d DeviceType_Name: kCUDA DataType_Name of x_0: kFloat16 DataType_Name of y_0: kFloat16 File "oneflow/core/job/job_interpreter.cpp", line 326, in InterpretJob RunNormalOp(launch_context, launch_op, inputs) File "oneflow/core/job/job_interpreter.cpp", line 238, in RunNormalOp it.Apply(_op, inputs, &outputs, OpExprInterpContext(empty_attr_map, JUST(launch_op.device))) File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 155, in NaiveInterpret PhysicalRun([&](InstructionsBuilder_ builder) -> Maybe ... output_eager_blob_objects), ctx, result->stream()); }) File "oneflow/core/framework/instructions_builder.h", line 168, in PhysicalRun Build(&instructions_builder) File "oneflow/core/framework/instructions_builder.cpp", line 400, in Call vm::OpCallInstructionPolicy::New( vm_stream, opkernel ... global_tensor_infer_result, ctx, *one::CurrentDevVmDepObjectConsumeMode()) File "oneflow/core/vm/op_call_instruction_policy.h", line 50, in New ptr->Init() File "oneflow/user/kernels/stateful_opkernel.cpp", line 920, in ChooseOpKernel user_op::UserOpRegistryMgr::Get().GetOpKernelRegistryResult(op_type_name, reg_ctx) Error Type: oneflow.ErrorProto.op_kernel_not_found_error

@doombeaker @wangerlie  copying the hijacked code to the original forward solves this problem first.
The upsample_nearest_3d error is due to missing registration of the half implementation. 
After adding relevant implementations,  Error: CUDA out of memory. 
  File "/data2/workspace/neiltian/onediff/src/onediff/infer_compiler/oneflow/utils.py", line 21, in wrapper
    return func(self, *args, **kwargs)
  File "/data2/workspace/neiltian/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 91, in wrapper
    ret = func(self, *args, **kwargs)
  File "/data2/workspace/neiltian/onediff/src/onediff/infer_compiler/oneflow/deployable_module.py", line 99, in forward
    output = dpl_graph(*args, **kwargs)
  File "/data2/workspace/neiltian/oneflow/python/oneflow/nn/graph/graph.py", line 281, in __call__
    return self._dynamic_input_graph_cache(*args, **kwargs)
  File "/data2/workspace/neiltian/oneflow/python/oneflow/nn/graph/cache.py", line 115, in __call__
    return graph(*args, **kwargs)
  File "/data2/workspace/neiltian/oneflow/python/oneflow/nn/graph/graph.py", line 284, in __call__
    self._compile(*args, **kwargs)
  File "/data2/workspace/neiltian/oneflow/python/oneflow/nn/graph/graph.py", line 852, in _compile
    return self._compile_new(*args, **kwargs)
  File "/data2/workspace/neiltian/oneflow/python/oneflow/nn/graph/graph.py", line 876, in _compile_new
    self.finish_compile_and_init_runtime()
  File "/data2/workspace/neiltian/oneflow/python/oneflow/nn/graph/graph.py", line 1428, in finish_compile_and_init_runtime
    self._c_nn_graph.init_runtime()
oneflow._oneflow_internal.exception.RuntimeError: Error: CUDA out of memory. Tried to allocate 292.4 GB

**Comment by neiltian-tencent** [comment]
copying the hijacked code to the original forward, following error:
Traceback (most recent call last):
  File "/data2/workspace/neiltian/onediff/src/onediff/infer_compiler/oneflow/utils.py", line 21, in wrapper
    return func(self, *args, **kwargs)
  File "/data2/workspace/neiltian/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 91, in wrapper
    ret = func(self, *args, **kwargs)
  File "/data2/workspace/neiltian/onediff/src/onediff/infer_compiler/oneflow/deployable_module.py", line 99, in forward
    output = dpl_graph(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 295, in __call__
    self._compile(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 861, in _compile
    return self._dynamic_input_graph_cache._compile(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/cache.py", line 121, in _compile
    return graph._compile(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 865, in _compile
    return self._compile_new(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 884, in _compile_new
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 1429, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 1577, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/data2/workspace/neiltian/onediff/src/onediff/infer_compiler/oneflow/graph.py", line 19, in build
    return self.model(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data2/workspace/neiltian/YT-AnimateAnyone/src/models/unet_3d_oflow.py", line 506, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data2/workspace/neiltian/YT-AnimateAnyone/src/models/unet_3d_blocks_oflow.py", line 445, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data2/workspace/neiltian/YT-AnimateAnyone/src/models/transformer_3d_oflow.py", line 142, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data2/workspace/neiltian/YT-AnimateAnyone/src/models/attention_oflow.py", line 457, in forward
    norm_hidden_states[_uc_mask],
RuntimeError: Error: Advanced indexing by boolean(mask) tensor only valid in eager mode.

**Comment by wangerlie** [comment]
@neiltian-tencent  hi, I have used onediff to accelerate Moore-AnimateAnyone demo: /MooreAnimateAnyone/scripts/pose2vid.py  
![image](https://github.com/siliconflow/onediff/assets/91201762/79b7a0a4-6fd3-4e1b-8141-896d4aeea7ee)
and it doesn't seem to have any problem  
![image](https://github.com/siliconflow/onediff/assets/91201762/5a366682-c0cc-49e8-8209-295cc1d77069)
 could you tell me exactlly how do you use onediff to accelerate MooreAnimateAnyone, which model are you trying to accelerate?  
it would be greate if you can provide me with your code.

**Comment by neiltian-tencent** [comment]
convert <class 'function'> failed: Transform failed of <class 'function'>: 'function' object has no attribute '<locals>' @wangerlie I compile denoising_unet by oneflow_compile. compile_pipe has no acceleration effect, although 
the above error is not report. What is the acceleration ratio you tested here?

**Comment by neiltian-tencent** [comment]
@wangerlie AnimateAnyone pipeline has two unets(denoising_unet and reference_unet). compile_pipe may filter the two unets, this is the onediff filter _PARTS info.
_PARTS = [
    "text_encoder",
    "text_encoder_2",
    "image_encoder",
    "unet", 
    "controlnet",
    "fast_unet",  # for deepcache
    "prior",  # for StableCascadePriorPipeline
    "decoder",  # for StableCascadeDecoderPipeline
    "vqgan.down_blocks",  # for StableCascadeDecoderPipeline
    "vqgan.up_blocks",  # for StableCascadeDecoderPipeline
    "vae.decoder",
    "vae.encoder",
]

**Comment by neiltian-tencent** [comment]
adding denoising_unet to the _PARTS, the above error is report.

**Comment by wangerlie** [comment]
> convert <class 'function'> failed: Transform failed of <class 'function'>: 'function' object has no attribute '' @wangerlie I compile denoising_unet by oneflow_compile. compile_pipe has no acceleration effect, although the above error is not report. What is the acceleration ratio you tested here?

I use `compile_pipe` to accelerate the `Pose2VideoPipeline` and find the same problem that it has no acceleration effect.

**Comment by wangerlie** [comment]
> @wangerlie AnimateAnyone pipeline has two unets(denoising_unet and reference_unet). compile_pipe may filter the two unets, this is the onediff filter _PARTS info. _PARTS = [ "text_encoder", "text_encoder_2", "image_encoder", "unet", "controlnet", "fast_unet", # for deepcache "prior", # for StableCascadePriorPipeline "decoder", # for StableCascadeDecoderPipeline "vqgan.down_blocks", # for StableCascadeDecoderPipeline "vqgan.up_blocks", # for StableCascadeDecoderPipeline "vae.decoder", "vae.encoder", ]

@neiltian-tencent  Following your tips I reproduced the reported error and I am working on the problem. Thanks for your patience.

**Comment by neiltian-tencent** [comment]
> @doombeaker I try to find an open source demo. Error related codes: def **getattribute**(self, attribute) (onediff/src/onediff/infer_compiler/transform/builtin_transform.py) elif attribute in ["forward", "_conv_forward"]: replacement = proxy_class(type(self._oflow_proxy_submod)) return lambda *args, **kwargs: getattr(replacement, attribute)( self, *args, **kwargs )

@wangerlie Previous debugging records

**Comment by strint** [comment]
Thanks for your feedback.

We will move to nexfort backend to avoid convert problems. Please take a look: https://github.com/siliconflow/onediff/tree/main/onediff_diffusers_extensions/examples/sdxl

@neiltian-tencent
