### ISSUE TITLE
使用了onediff checkpoint、onediff controlnet，LoraLoaderModelOnly节点不可用

### ISSUE THREAD

**Issue by LuckyIvan** [siliconflow/onediff#800]
一下是的我的工作流
[onediff_test.json](https://github.com/siliconflow/onediff/files/14932122/onediff_test.json)
openpose图片
![POSE2](https://github.com/siliconflow/onediff/assets/15135343/5ba14923-4c7f-4075-9139-ebd04a2c7482)
LoraLoaderModelOnly把这个节点拆掉会运行成功

**Comment by LuckyIvan** [comment]
![image](https://github.com/siliconflow/onediff/assets/15135343/6eb833b9-e11b-4fcd-995b-c0ad6309d997)
环境使用的这个

**Comment by LuckyIvan** [comment]
![image](https://github.com/siliconflow/onediff/assets/15135343/c3d56748-08e6-4fc6-8f27-fa60a2d80cc5)
这是报错信息，之后会重启comfyui，comfyui启动方式是--gpu-only

**Comment by wangerlie** [comment]
@LuckyIvan 
## 环境对齐
本地复现环境：  
ComfyUI_IPAdapter_Plus:
![image](https://github.com/siliconflow/onediff/assets/91201762/a099280c-bb09-4d05-8b83-75fbadbaef31)
ComfyUI:  
![image](https://github.com/siliconflow/onediff/assets/91201762/6213b9e6-a456-43e8-a9c2-e09cf89f1730)
## 问题复现
### 准备工作
1. 首先验证OneDiff Node能在ComfyUI中正常使用：
![image](https://github.com/siliconflow/onediff/assets/91201762/1bb2387d-415e-4f60-9c2c-913c7402408f)
2. 下载相应的safetensors文件
https://hf-mirror.com/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors  
https://hf-mirror.com/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sd15_lora.safetensors  
https://hf-mirror.com/creatorbest/myposes/resolve/main/OpenPoseXL2.safetensors  
https://hf-mirror.com/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sdxl_lora.safetensors  
https://hf-mirror.com/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus-face_sdxl_vit-h.safetensors  
https://hf-mirror.com/stabilityai/sdxl-vae/resolve/main/sdxl_vae.safetensors  
3. 用户没有提供POSE2的图片，所以在本流程中使用随便选取了一张图片做为POSE2
### 本地运行复现
本地流程截图
![image](https://github.com/siliconflow/onediff/assets/91201762/ffd13653-56ab-4f05-bf59-e0766653d11f)
运行指令截图  
![image](https://github.com/siliconflow/onediff/assets/91201762/024338c1-2f56-4c0a-85d9-fd65b3be8f51)

**运行会在KSampler节点中止，出现与用户一样的`lora key not loaded`报错**
![image](https://github.com/siliconflow/onediff/assets/91201762/6ac7cc43-0130-443a-b9a6-f45589f6285b)
**但是并未出现后续关于`oneflow`的报错，也没有重启ComfyUI**   
本地实现出现的报错情况如下： 
![image](https://github.com/siliconflow/onediff/assets/91201762/344cc25a-0a0a-4a0b-992f-a50e38669702)
![image](https://github.com/siliconflow/onediff/assets/91201762/397841c2-9da0-4a28-a0c9-349542a532d5)
### 删除LoraLoaderModelOnly节点后报错信息与未删除节点时一样
![image](https://github.com/siliconflow/onediff/assets/91201762/97b09f2f-6cd6-4510-818d-781f445521c1)

## 我的报错和您不一致，以下是我的版本信息
```
onediff                   0.13.0.dev1
oneflow                   0.9.1.dev20240331+cu118
```
麻烦您核对一下版本信息

**Comment by wangerlie** [comment]
更新环境后完成问题复现
```
oneflow                   0.9.1.dev20240411+cu121
onediff                   0.13.0.dev1
```
完成问题复现
![image](https://github.com/siliconflow/onediff/assets/91201762/642fe22b-6090-474e-930b-d21fb122ecf8)
![image](https://github.com/siliconflow/onediff/assets/91201762/c245f283-1bc1-448a-a1d6-0ad84843ed6a)

删除sd15的lora后能够正常运行
![image](https://github.com/siliconflow/onediff/assets/91201762/3af3f993-55ed-4346-b1ec-85bc44d9c3e6)
![image](https://github.com/siliconflow/onediff/assets/91201762/33ecf405-ac80-4e18-ac11-4dcc214e1c94)
尝试将下面lora换为sdxl与基底模型对齐
![image](https://github.com/siliconflow/onediff/assets/91201762/ef4e08b4-b107-45e5-92a8-a1b5e930e75e)
报错
![image](https://github.com/siliconflow/onediff/assets/91201762/4d2da3ce-5a34-433e-a10f-fc23345f30fe)

**Comment by wangerlie** [comment]
@LuckyIvan 问题已解决，请您更新至最新版本ComfyUI，onediff请使用[该分支](https://github.com/siliconflow/onediff/tree/dev_ipa%2Bisntantid)。
在本地验证结果如下：LoraLoaderModelOnly节点能够正常使用
![workflow (11)](https://github.com/siliconflow/onediff/assets/91201762/75a0ae47-45d0-45a0-a6d0-85bc14448bd6)
![img_v3_02a0_cfa422a7-b61f-4b98-8f8c-b30dba002e7g](https://github.com/siliconflow/onediff/assets/91201762/513ad4fb-fd91-4ab0-8b34-0c7f15353e5d)
