### ISSUE TITLE
使用onediff后Comfyui Ip-adapter没生效

### ISSUE THREAD

**Issue by HydrogenQAQ** [siliconflow/onediff#804]
#### A clear and concise description of what the bug is.

同时跑了不加onediff和加了onediff的，seed一样，模型一样，加了onediff的ip-adapter并没有生效
![image](https://github.com/siliconflow/onediff/assets/26037094/af4305b9-cd34-492d-8c09-b3d6c1910f81)

#### OneDiff git commit id

onediff：b89dd4980aeab85b8f9c
comfyui：f81dbe26e2e363c28ad043
[ip-adapter](https://github.com/cubiq/ComfyUI_IPAdapter_plus)：d87b7ce1c1b3c22

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

version: 0.9.1.dev20240124+cu121
git_commit: 6458a12
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):
[test.json](https://github.com/siliconflow/onediff/files/14943037/test.json)

**Comment by strint** [comment]
请更新一下到最新版本，这块已经做了更新。

**Comment by strint** [comment]
It's too old to follow, please feel free to reopen it.
