### ISSUE TITLE
AttributeError: 'LatentDiffusion' object has no attribute 'is_ssd'

### ISSUE THREAD

**Issue by huohuohong** [siliconflow/onediff#813]
### Describe the bug
集成在webui上，选择了onediff插件，点击生成图片，提示报错
AttributeError: 'LatentDiffusion' object has no attribute 'is_ssd'
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

### Additional context
![image](https://github.com/siliconflow/onediff/assets/52687338/68209194-8ee2-49e1-8a67-9b61f8c2f356)

**Comment by marigoold** [comment]
@huohuohong 您用的是什么模型呢？

**Comment by huohuohong** [comment]
sd模型是v1-5-pruned-emaonly这个，安装步骤是这个截图
![image](https://github.com/siliconflow/onediff/assets/52687338/334ae642-fcf9-4fc4-93ad-09f3b63dfe11)

**Comment by marigoold** [comment]
> sd模型是v1-5-pruned-emaonly这个，安装步骤是这个截图 ![image](https://private-user-images.githubusercontent.com/52687338/322738853-334ae642-fcf9-4fc4-93ad-09f3b63dfe11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTE5NjUsIm5iZiI6MTcxMzI1MTY2NSwicGF0aCI6Ii81MjY4NzMzOC8zMjI3Mzg4NTMtMzM0YWU2NDItZmNmOS00ZmM0LTkzYWQtMDlmM2I2M2RmZTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA3MTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYzYyYmZiYThkMjUyNzA1MjYzZGNkNWZhYjg0MTMxZTEzODI2MTdiZjY5ZjNkYzdkNjU2M2EyMjhmM2ZjODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wwoidjWZoVu_xotqx7SYoSLAtAw6bE03jTrmn3iUEJo)

麻烦您发一下 webui、onediff 的版本，这个问题之前没有遇到过，比较奇怪。

**Comment by huohuohong** [comment]
webui version: [v1.6.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)    
python: 3.10.14  
torch: 2.0.1+cu118   
gradio: 3.41.2
onediff                   0.13.0.dev1 
oneflow                   0.9.1.dev20240412+cu122
看看这几个版本对应有问题吗

**Comment by marigoold** [comment]
> webui version: [v1.6.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)   python: 3.10.14   torch: 2.0.1+cu118   gradio: 3.41.2 onediff 0.13.0.dev1 oneflow 0.9.1.dev20240412+cu122 看看这几个版本对应有问题吗

您可以把 sd-webui 升级到最新版本再试一下。文档里面有些错误，我们会马上改正

**Comment by huohuohong** [comment]
webui升级到最新就可以用了，但是没有这个Quantization（int8）speed up 功能选择
![image](https://github.com/siliconflow/onediff/assets/52687338/63a0aef3-e99e-4755-a0c8-6e54dc205d79)
这个怎么配置界面上才会有这个功能

**Comment by marigoold** [comment]
> webui升级到最新就可以用了，但是没有这个Quantization（int8）speed up 功能选择 ![image](https://private-user-images.githubusercontent.com/52687338/323100454-63a0aef3-e99e-4755-a0c8-6e54dc205d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDM0NTEsIm5iZiI6MTcxMzM0MzE1MSwicGF0aCI6Ii81MjY4NzMzOC8zMjMxMDA0NTQtNjNhMGFlZjMtZTk5ZS00NzU1LWEwYzgtNmU1NGRjMjA1ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA4MzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMmYyMjZlNjJlYTk1YTgzNjdmZDIyMWFiN2JjZWJiZWE1M2U1NDBiOGVlNThlZWQ5OWNmMTBhOTVjYWQzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ls135nQwmr3ybfJqUbbzLGUTwWp6tQDCTkv9y8OGbYc) 这个怎么配置界面上才会有这个功能

这个是企业版的功能，您购买了license之后，我们会给您一个key，再启动webui就可以用量化功能了
