### ISSUE TITLE
TypeError: CrossAttentionPatch.__init__() got an unexpected keyword argument 'cond_alt'

### ISSUE THREAD

**Issue by onefish51** [siliconflow/onediff#822]
### Describe the bug
When testing onediff's support for IP-Adapter according to the [ISS28](https://github.com/siliconflow/onediff/issues/609#issuecomment-2044253164) example, the following errors occurred.

### Your environment
```bash
Ubuntu 20.04.6 LTS
```

#### OneDiff git commit id
Building wheels for collected packages: onediff
  Building editable for onediff (pyproject.toml) ... done
  Created wheel for onediff: filename=onediff-1.0.0.dev1-0.editable-py3-none-any.whl size=5368 sha256=9d5b11e5259595075e60637f6dc01ee04d02c2f4fcebd68ba19db717f900926b
  Stored in directory: /tmp/pip-ephem-wheel-cache-mjsjrc1_/wheels/e3/1f/46/7e28df7965c1502bbf6700596e510603fed568676453a80f22
Successfully built onediff
Installing collected packages: onediff
  Attempting uninstall: onediff
    Found existing installation: onediff 1.0.0.dev1
    Uninstalling onediff-1.0.0.dev1:
      Successfully uninstalled onediff-1.0.0.dev1
Successfully installed onediff-1.0.0.dev1
```
####  OneFlow version info
```bash
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
path: ['/usr/local/lib/python3.10/dist-packages/oneflow']
version: 0.9.1.dev20240315+cu122
git_commit: f29b051
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```
### How To Reproduce
comfyui workflow:
[workflow_ipadapter_onediff.json](https://github.com/siliconflow/onediff/files/14995019/workflow_ipadapter_onediff.json)

### The complete error message
```bash
got prompt
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/app/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/app/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/app/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/app/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 673, in apply_ipadapter
    return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
  File "/app/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 373, in ipadapter_execute
    set_model_patch_replace(model, patch_kwargs, ("input", id))
  File "/app/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 41, in <lambda>
    lambda *args, **kwargs: self(*args, **kwargs),
  File "/app/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 57, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/app/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/hijack_ipadapter_plus/IPAdapterPlus.py", line 38, in set_model_patch_replace_fn_of
    patch = CrossAttentionPatch_OF(**patch_kwargs)
TypeError: CrossAttentionPatch.__init__() got an unexpected keyword argument 'cond_alt'
```

@ccssu @strint

**Comment by ccssu** [comment]
> ### Describe the bug
> When testing onediff's support for IP-Adapter according to the [ISS28](https://github.com/siliconflow/onediff/issues/609#issuecomment-2044253164) example, the following errors occurred.

### an unexpected keyword argument 'cond_alt' 
  CrossAttentionPatch.__init__() got an unexpected keyword argument 'cond_alt'   This error is due to a modification made to the CrossAttentionPatch of the plugin, specifically in:https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/0d0a7b3693baf8903fe2028ff218b557d619a93d/CrossAttentionPatch.py#L9

### solve
@onefish51 
This has been addressed in pull request https://github.com/siliconflow/onediff/pull/814 and is currently being progressed for merging.
You can try it out using https://github.com/siliconflow/onediff/pull/814
```shell
 ## Install
### 1. onediff 
git clone https://github.com/siliconflow/onediff.git
cd onediff 
git checkout -b dev_ipa+isntantid
pip install -e .

### 2. onediff_comfy_nodes
cp -r onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
```

**Comment by onefish51** [comment]
> merging

@ccssu The code has not been merged yet, still waiting! 

Following your instructions, I just tested it and found a new bug:
```bash
got prompt
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
 OneDiffCheckpointLoaderSimple load_checkpoint file_path /data2/home/tyu/stable_diffusion/comfyUI/ComfyUI_simple/input/graphs/realisticVisionV51_v51VAE.safetensors/BaseModel_88f69f8acb
Requested to load CLIPVisionModelProjection
Loading 1 new model
!!! Exception during processing !!!
Traceback (most recent call last):
  File "ComfyUI_simple/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "ComfyUI_simple/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "ComfyUI_simple/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "ComfyUI_simple/custom_nodes/onediff_comfy_nodes/_nodes.py", line 738, in set_cache_filename
    file_dir = os.path.dirname(file_path)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
workflow:
[workflow_onediff_ipadapter.json](https://github.com/siliconflow/onediff/files/15258487/workflow_onediff_ipadapter.json)

**Comment by strint** [comment]
@onefish51 Please update to the newest version. It's should have been fixed.
