### ISSUE TITLE
Could not find a version that satisfies the requirement onediff-quant (from versions: none)

### ISSUE THREAD

**Issue by ziQzav** [siliconflow/onediff#828]
Hello i have a error in comfyui venv

Looking in links: https://github.com/siliconflow/onediff_releases/releases/expanded_assets/enterprise
ERROR: Could not find a version that satisfies the requirement onediff-quant (from versions: none)
ERROR: No matching distribution found for onediff-quant

python v3.10.11

When I tried to install the .whl file manually, it gave an error again.

**Comment by strint** [comment]
onediff-quant is only for the enterprise edition user for the moment.
