### ISSUE TITLE
Compilation: AttributeError: 'str' object has no attribute 'removeprefix'

### ISSUE THREAD

**Issue by karlbernard2** [siliconflow/onediff#831]
### Describe the bug

I get the following error when compilation starts

  ```
File "/opt/venv/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 971, in __call__
    noise_pred = self.unet(
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1574, in _call_impl
    hook_result = hook(self, args, result)
  File "/app/onediff/infer_compiler/utils/param_utils.py", line 166, in forward_generate_constant_folding_info_hook
    generate_constant_folding_info(module)
  File "/app/onediff/infer_compiler/utils/param_utils.py", line 102, in generate_constant_folding_info
    result = {
  File "/app/onediff/infer_compiler/utils/param_utils.py", line 103, in <dictcomp>
    convert_var_name(k): v
  File "/app/onediff/infer_compiler/utils/param_utils.py", line 86, in convert_var_name
    s = re.sub(r"_[0-9]+$", "", s.removeprefix(prefix)).removeprefix("model.")
AttributeError: 'str' object has no attribute 'removeprefix'

```
### Your environment
docker

### How To Reproduce
Steps to reproduce the behavior(code or script):
```
 pipe = DiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16, use_safetensors=True)
    pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, final_sigmas_type="sigma_min")
    pipe.to("cuda")
    pipe.unet = oneflow_compile(pipe.unet)

    resolutions = ([(640,832),])
    # Warmup with chosen resolutions
    for resolution in resolutions:
        for i in range(1):
            image = pipe(
                prompt="test prompt",
                height=resolution[0],
                width=resolution[1],
                num_inference_steps=30,
            ).images
    #pipe = compile_pipe(pipe)
```

### The complete error message
AttributeError: 'str' object has no attribute 'removeprefix'

### Additional context
dockerfile
`FROM nvidia/cuda:12.1.0-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y bash \
    build-essential \
    git \
    git-lfs \
    curl \
    ca-certificates \
    libsndfile1-dev \
    libgl1 \
    python3.8 \
    python3-pip \
    python3.8-venv && \
    rm -rf /var/lib/apt/lists

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app

COPY requirements.txt requirements.txt
RUN --mount=type=cache,mode=0755,target=/root/.cache/pip pip install -r requirements.txt

RUN python3 -m pip install -U --pre oneflow -f https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu121
#RUN python3 -m pip install "torch" "transformers==4.27.1" "diffusers[torch]==0.19.3" "oneflow"

RUN python3 -m pip install --pre onediff
RUN git clone https://github.com/siliconflow/onediff.git
RUN cp -R onediff/onediff_diffusers_extensions/onediffx .
ADD onediff /src/onediff
RUN python3 -m pip install -e /src/onediff
RUN python3 -m pip install -e /src/onediff/onediff_diffusers_extensions
RUN cp -R /src/onediff/src/onediff .
RUN cp -R /src/onediff/src/infer_compiler_registry .
```

Requirements:
`torch==2.2.1
transformers==4.27.1
diffusers[torch]==0.19.3`

**Comment by marigoold** [comment]
@karlbernard2  Hi, thanks for your feedback and sorry for replying so late. The `removeprefix` of class str only exists at Python >= 3.9, and your Python version is 3.8, in which str doesn't have a member function `removeprefix`, we will fix it :)

**Comment by marigoold** [comment]
@karlbernard2 Hi, the bug is fixed in https://github.com/siliconflow/onediff/pull/856 , please pull the newest onediff and have a try :)
