### ISSUE TITLE
Compilation optimization issue

### ISSUE THREAD

**Issue by chuck-ma** [siliconflow/onediff#835]
I am currently using onediff, and the total time for compile_pipe and load_pipe is about 30 seconds (even after the first compilation and save_pipe). This duration is too exaggerated in a serverless scenario. Is there a way to utilize multi-core CPUs to reduce the time for compilation and loading?

**Comment by strint** [comment]
> I am currently using onediff, and the total time for compile_pipe and load_pipe is about 30 seconds (even after the first compilation and save_pipe). This duration is too exaggerated in a serverless scenario. Is there a way to utilize multi-core CPUs to reduce the time for compilation and loading?

Currently, the compilation needs to be a single thread run.

We will do some optimization later for the compilation/loading time in later version.

**Comment by chuck-ma** [comment]
I am more than happy to provide some assistance, if there is anything I can do.

**Comment by strint** [comment]
> I am more than happy to provide some assistance, if there is anything I can do.

Thanks! We are making a prototype for this, and it's expected to be released at the end of May. It should need help, stay tuned.
