### ISSUE TITLE
让  ComfyUI Manager 安装 Onediff 更丝滑

### ISSUE THREAD

**Issue by nono-Sang** [siliconflow/onediff#838]
## 问题描述
节点是 ComfyUI 构建工作流的基础组件。除了原生节点，ComfyUI 允许用户自定义节点（需要放置在 `xxx/ComfyUI/custom_nodes/` 目录下），而 ComfyUI Manager 是一个用于管理自定义节点的插件（其本身也是一个自定义节点）。因此，在 ComfyUI 中，我们通过使用 Onediff 提供的自定义节点来加速推理过程。

ComfyUI Manager 提供了两种使用方式，一是 UI 操作，二是命令行（CLI）模式，二者的功能是相同的。这里，通过 UI 安装 Onediff Nodes 后会发现 `xxx/ComfyUI/custom_nodes/` 目录下新增了 `onediff_comfy_nodes` 文件夹，但是会显示 import 失败的问题（如下图），并且 `Try fix` 并不能解决问题。

![image](https://github.com/siliconflow/onediff/assets/43398136/40eb99c6-eeb0-491a-8fcb-c4eb79419db6)

事实上，Onediff 目前所推荐的使用方式是手动安装（即仓库主页介绍的）。这里，改用手动安装，即 `cp -r onediff_comfy_nodes xxx/ComfyUI/custom_nodes/`，会发现不再有问题（如下图）。

![image](https://github.com/siliconflow/onediff/assets/43398136/3342867f-c4d7-47b5-be8b-2ed248558147)

进一步，在 ComfyUI 中添加节点就能看到 Onediff 所提供的一系列自定义节点。使用 `Load Checkpoint - OneDiff` 节点进行测试，发现推理没有问题。

![image](https://github.com/siliconflow/onediff/assets/43398136/f902d684-f09f-49fd-9c54-2ec59d800d67)
![image](https://github.com/siliconflow/onediff/assets/43398136/173c8007-5716-4b5c-a0d2-739196f39121)

## 问题分析
事实上，ComfyUI Manager 使用的是 `siliconflow/onediff_comfy_nodes` 仓库，而手动安装使用的是 `siliconflow/onediff` 仓库下的`onediff_comfy_nodes` 目录。目前来看，二者并不相同。ComfyUI Manager 下载时的目标 URL 地址记录在 
`xxx/ComfyUI/custom_nodes/ComfyUI-Manager/custom-node-list.json` 中，下图是 Onediff 的具体信息。

![image](https://github.com/siliconflow/onediff/assets/43398136/ad0c6197-0e49-44b4-92b2-fc127e49c3f0)

为了更方便地 debug，改用 CLI 模式来安装，即执行 `python cm-cli.py install onediff_comfy_nodes`，主要过程如下。

```text
[1/1] Install: ['https://github.com/siliconflow/onediff_comfy_nodes']

Download: git clone 'https://github.com/siliconflow/onediff_comfy_nodes'
NOTE：下载后文件同样保存在 xxx/ComfyUI/custom_nodes 目录下

Install: pip packages
## ComfyUI-Manager: EXECUTE => ['xxx/miniconda3/envs/onediff/bin/python', '-m', 'pip', 'install', 'onediff']
NOTE：即在 onediff_comfy_nodes 目录下执行 pip install -r requirements.txt

Install: install script
## ComfyUI-Manager: EXECUTE => ['xxx/miniconda3/envs/onediff/bin/python', 'install.py']
NOTE：即在 onediff_comfy_nodes 目录下执行 python install.py
```

事实上，上一步能够看到安装成功的 log，但是用 `python main.py` 启动 ComfyUI 时会报错：`No module named 'onediff.infer_compiler.with oneflow_compile'`。

**Comment by doombeaker** [comment]
`siliconflow/onediff_comfy_nodes` 仓库是个临时解决方案。而且是手工同步的。所以会因为更新不及时导致这样那样的问题。

这次更新，最好直接使用 `onediff` 仓库作为 ComfyUI Manager 的源。ComfyUI Manager 之前说未来会支持 sub folder 的插件，不知道现在已经有了没。

如果不支持，就需要自己编写下 py 脚本（ComfyUI Manager 有约定，会运行插件目录下的 install.py 等文件），这个可以参考下 ComfyUI Manager 的文档，或者其它的插件仓库。

**Comment by nono-Sang** [comment]
目前来看，把 `onediff` 仓库作为源似乎不太好处理。那如果继续把 `siliconflow/onediff_comfy_nodes` 仓库作为源呢？一个 “算是能用” 的方法是：在 `install.py` 中去克隆 `onediff` 仓库并用其内部的 `onediff_comfy_nodes/` 来取代掉旧的。

最初，ComfyUI Manager 下载 `siliconflow/onediff_comfy_nodes` 仓库，文件结构为：
```text
ComfyUI/
    custom_nodes/
        ComfyUI Manager/
        (old) onediff_comfy_nodes/
            install.py
            requirements.txt
```

执行 `install.py` 时，首先下载 `siliconflow/onediff` 仓库到 `custom_nodes/` 下，文件结构为：
```text
ComfyUI/
    custom_nodes/
        ComfyUI Manager/
        onediff/
            (new) onediff_comfy_nodes/
        (old) onediff_comfy_nodes/
            install.py
            requirements.txt
```

然后通过一些文件移动与删除，将文件结构调整为：
```text
ComfyUI/
    custom_nodes/
        ComfyUI Manager/
        (new) onediff_comfy_nodes/
```

之后，Onediff Nodes 便可以被正确地使用起来。事实上，对于这个方法，`siliconflow/onediff` 仓库仅仅提供了 `requirements.txt` 以及 `install.py` 两个文件，再没有其他作用。

**Comment by doombeaker** [comment]
> 目前来看，把 `onediff` 仓库作为源似乎不太好处理。那如果继续把 `siliconflow/onediff_comfy_nodes` 仓库作为源呢？一个 “算是能用” 的方法是：在 `install.py` 中去克隆 `onediff` 仓库并用其内部的 `onediff_comfy_nodes/` 来取代掉旧的。
> ...
> 之后，Onediff Nodes 便可以被正确地使用起来。事实上，对于这个方法，`siliconflow/onediff` 仓库仅仅提供了 `requirements.txt` 以及 `install.py` 两个文件，再没有其他作用。

那就先按这个方法做吧，这个方法还不需要去给 ComfyUI Manager 提交 PR，只需要改我们自己有权限的东西，还比较方便。

**Comment by nono-Sang** [comment]
存在一个不太好的问题，如果用户下载时因网络不好而下载 `onediff` 失败，那么用户仍然能够看到 `onediff_comfy_nodes` 是已安装的（旧的那个，没法使用），这个时候需要用户去卸载重新安装下。
