### ISSUE TITLE
Can not use 'nsys profile'  for onediff diffusers

### ISSUE THREAD

**Issue by chenly15** [siliconflow/onediff#850]
### Describe the bug
If I use 'nsys profile' to run the script https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/examples/text_to_image.py, the segmentation fauls happends.

### Your environment
ubuntu 20.04，torch==2.0.1+cu118，diffusers==0.27.2, transformers==4.40.1， GPU A10 

#### OneDiff git commit id
b9d0ae82445ac858206bc12a8fe8dfd765e75d65
####  OneFlow version info
version: 0.9.1.dev20240427+cu118
git_commit: 665bcf8
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Run the command 'nsys profile python text_to_image.py', the script is https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/examples/text_to_image.py 

### The complete error message
<img width="947" alt="image" src="https://github.com/siliconflow/onediff/assets/33417982/1d542d5e-fc95-4cc2-b7d9-951e628a98e4">

### Additional context
I'm confused how to profile oneflow inference and how to catch nvtx range.

**Comment by strint** [comment]
too old to follow, please feel free to reopen it.
