### ISSUE TITLE
After using onediff to speed up, it slows down in sd-webui

### ISSUE THREAD

**Issue by lijunliangTG** [siliconflow/onediff#851]
#### A clear and concise description of what the bug is.
After using onediff to accelerate, it is slower than before torch

#### OS 
Ubuntu 20.04.4 LTS

#### OneDiff git commit id
6077d115

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
path: ['/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240505+cu122
git_commit: 665bcf8
cmake_build_type: Release
rdma: True
mlir: True

### How To Reproduce
Steps to reproduce the behavior(code or script):
When I tried to test it with a 3090 graphics card
with onediff
![image](https://github.com/siliconflow/onediff/assets/117806079/2f2c97ed-a17d-4df8-9557-c65d4b07e400)
without onediff
![image](https://github.com/siliconflow/onediff/assets/117806079/1111a362-1b93-48ff-a3d8-7090a25c2f6d)

### The complete error message
![80635b0335c8801f25e0ced7e6f2d002](https://github.com/siliconflow/onediff/assets/117806079/42380958-da97-47d5-9ce3-2d57e840d73f)

**Comment by marigoold** [comment]
https://github.com/siliconflow/onediff/pull/858
