### ISSUE TITLE
runtime and compiletime cudu is not match

### ISSUE THREAD

**Issue by SmallStom** [siliconflow/onediff#852]
this is my code:

import torch
import datetime
from diffusers import StableDiffusionXLPipeline
from onediffx import compile_pipe, save_pipe

pipe = StableDiffusionXLPipeline.from_single_file("../../../ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", use_safetensors=True)
pipe.to("cuda")
pipe = compile_pipe(pipe)
# run once to trigger compilation
image = pipe(
        prompt="street style, detailed, raw photo, woman, face, shot on CineStill 800T",
        height=512,
        width=512,
        num_inference_steps=30,
        output_type="pil",
    ).images
end = datetime.datetime.now()
save_pipe(pipe, dir="cached_pipe")

and i got this mistake:

W20240507 03:27:18.496176  2366 cuda_stream.cpp:49] Runtime version 12.1 of cuBLAS incompatible with compiletime version 12.2.
  0%|                                                                                                  | 0/30 [00:00<?, ?it/s]
Killed

CUDA Version: 12.2 
python3 -m pip install -U --pre oneflow -f https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu122

please help me, tks

**Comment by strint** [comment]
> W20240507 03:27:18.496176 2366 cuda_stream.cpp:49] Runtime version 12.1 of cuBLAS incompatible with compiletime version 12.2.

This is just a warning.

Is there more error info.

**Comment by strint** [comment]
It's too old to follow, please feel free to reopen it.
