### ISSUE TITLE
A10 性能下降

### ISSUE THREAD

**Issue by maidabu** [siliconflow/onediff#854]
onediff从0.12.1开始相比于0.12.0有10%以上的性能下降，是怎么回事。

**Comment by strint** [comment]
> onediff从0.12.1开始相比于0.12.0有10%以上的性能下降，是怎么回事。

请问是什么模型，什么设备。能否说明下复现方式。

**Comment by maidabu** [comment]
> > onediff从0.12.1开始相比于0.12.0有10%以上的性能下降，是怎么回事。
> 
> 请问是什么模型，什么设备。能否说明下复现方式。

A10上，SD1.5。就跑https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/examples/text_to_image.py

**Comment by strint** [comment]
> > > onediff从0.12.1开始相比于0.12.0有10%以上的性能下降，是怎么回事。
> > 
> > 
> > 请问是什么模型，什么设备。能否说明下复现方式。
> 
> A10上，SD1.5。就跑https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/examples/text_to_image.py

好的，我们已经在复现和定位问题

**Comment by lijunliangTG** [comment]
您提到的情况确实存在，为了支持动态分辨率，所以性能多了10%的开销。
https://github.com/siliconflow/onediff/pull/552/files

**Comment by maidabu** [comment]
> 您提到的情况确实存在，为了支持动态分辨率，所以性能多了10%的开销。 https://github.com/siliconflow/onediff/pull/552/files

为什么支持动态分辨率性能会下降这么多，底层跑的kernel应该都一样吧

**Comment by strint** [comment]
> > 您提到的情况确实存在，为了支持动态分辨率，所以性能多了10%的开销。 https://github.com/siliconflow/onediff/pull/552/files
> 
> 为什么支持动态分辨率性能会下降这么多，底层跑的kernel应该都一样吧

是不一样的，一些不支持动态 shape 的 op 被替换掉了。我们在做一些技术栈重构，会在新技术栈来改进这块。
