### ISSUE TITLE
module 'oneflow._C' has no attribute 'broadcast_dim_like'

### ISSUE THREAD

**Issue by songh11** [siliconflow/onediff#855]
### Describe the bug

error is: module 'oneflow._C' has no attribute 'broadcast_dim_like'

### Your environment
ubuntu 20.04 v100

#### OneDiff git commit id
425be50e7a14ef3cb4b9245246483e1e40bd6edf

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
<img width="487" alt="image" src="https://github.com/siliconflow/onediff/assets/75419275/4e781e2b-f001-4bf0-a0f1-b5d3fb4bec12">

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by haritowa** [comment]
How you solved it?

**Comment by strint** [comment]
> How you solved it?

Please run `python -m oneflow --doctor`

**Comment by songh11** [comment]
> How you solved it?

Follow this to install oneflow. https://github.com/siliconflow/onediff?tab=readme-ov-file#optional-install-oneflow

**Comment by bigmover** [comment]
> > How you solved it?
> 
> Please run `python -m oneflow --doctor` and paste oneflow version info here.
> 
> `broadcast_dim_like` is in the latest oneflow. Maybe you need to update oneflow: https://github.com/siliconflow/onediff?tab=readme-ov-file#optional-install-oneflow

I build from sorce and came across the same issue? 
commit is like below:
![image](https://github.com/user-attachments/assets/f19410b5-4c79-44d4-b8c5-5f531b75f781)

Would you mind to give some advice?
