### ISSUE TITLE
Source code of oneflow

### ISSUE THREAD

**Issue by rfan-debug** [siliconflow/onediff#861]
Hey, I am trying to fetch the source code of oneflow from your release page: https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu118 

There is a file called `Source Code (zip)` on this page but it contains the readme only. Is there still a way to access oneflow's source code? Thanks!

**Comment by strint** [comment]
> oneflow's source code

We have customized an inner version of oneflow for the Diffusion model. Some of the optimization is not that general for general-purpose dl tasks, so it's free to use but not open source.

**Comment by wywywywy** [comment]
> We have customized an inner version of oneflow for the Diffusion model. Some of the optimization is not that general for general-purpose DL tasks, so it's free to use but not open source.

I assume the optimization is for your enterprise offering?

Is it possible to have a separate library package that's truly open source without the enterprise optimization please?

**Comment by strint** [comment]
> > We have customized an inner version of oneflow for the Diffusion model. Some of the optimization is not that general for general-purpose DL tasks, so it's free to use but not open source.
> 
> I assume the optimization is for your enterprise offering?
> 
> Is it possible to have a separate library package that's truly open source without the enterprise optimization please?

Not in plan for the moment, but we will think about it. Thanks for you advice.
