### ISSUE TITLE
comfyui切换模型报错

### ISSUE THREAD

**Issue by r970707452c** [siliconflow/onediff#865]
父镜像:pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
GPU: A10 
COMFYUI:commit d14bdb18967f7413852a364747c49599de537eec
onediff: commit  8ceeae4bb6d1ee9ae27d3ecde25b759d0cd75e64
启动容器后第一次使用load checkpoint onediff 节点可以跑通，切换模型以后在执行容器会重启，报错如下
FETCH DATA from: /home/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
Stack trace (most recent call last) in thread 125:
   Object "/opt/conda/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-1f624b73.so", at 0x7c89faa56ce7, in 
   Object "/opt/conda/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-1f624b73.so", at 0x7c89faa56547, in 
   Object "/opt/conda/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-1f624b73.so", at 0x7c89faa51dd8, in vm::ThreadCtx::TryReceiveAndRun()
   Object "/opt/conda/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-1f624b73.so", at 0x7c89fa9f4574, in vm::EpStreamPolicyBase::Run(vm::Instruction*) const
   Object "/opt/conda/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-1f624b73.so", at 0x7c89fa9f7877, in vm::Instruction::Compute()
   Object "/opt/conda/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-1f624b73.so", at 0x7c89fa9fec58, in vm::OpCallInstructionPolicy::Compute(vm::Instruction*)
   Object "/opt/conda/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-1f624b73.so", at 0x7c89fa9fe929, in 
   Object "/opt/conda/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-1f624b73.so", at 0x7c89fa9f9a7a, in 
   Object "/opt/conda/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-1f624b73.so", at 0x7c89f21ddd3c, in 

Aborted (Signal sent by tkill() 1 0)

**Comment by doombeaker** [comment]
麻烦补充下 oneflow 版本信息

> Run `python -m oneflow --doctor` and paste it here.


以及监控下显存使用信息

```
watch -n 1 nvidia-smi
```

**Comment by r970707452c** [comment]
oneflow                      0.9.1.dev20240507+cu118

**Comment by ccssu** [comment]
OneDiff 版本不正常，main 分支目前只兼容有一个ipa节点情况。
使用请参考如下指令重新安装 onediff: @r970707452c 

```shell
git clone https://github.com/siliconflow/onediff.git
cd onediff 
git checkout -b dev_ipa+isntantid
pip install -e .

### 2. onediff_comfy_nodes
ln -s $(pwd)/onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
# or
#. cp -r onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
```

ipa插件安装参考 https://github.com/siliconflow/onediff/pull/814#issue-2242547294 

## 测试工作流如下：
下图是测试工作流，可以直接下载在comfyui 加载，（预计占用显存 10100MiB）
![workflow (25)](https://github.com/siliconflow/onediff/assets/109639975/195425a6-51b7-4da0-b10e-cc2fa08524ae)
[workflow (4).json](https://github.com/siliconflow/onediff/files/15263235/workflow.4.json)

**Comment by ccssu** [comment]
OneDiff 版本不正常，main 分支目前只兼容有一个ipa节点并且ipa后只能接ksampler的情况， （目前 https://github.com/siliconflow/onediff/commit/8ceeae4bb6d1ee9ae27d3ecde25b759d0cd75e64 使用 多个 ipa节点会导致显存异常 这个问题是已知 对应 https://github.com/siliconflow/onediff/issues/800#issuecomment-2058155206  ，解决在 `dev_ipa+isntantid` 分支）

## Solution

使用请参考如下指令重新安装 onediff: @r970707452c 

```shell
git clone https://github.com/siliconflow/onediff.git
cd onediff 
git checkout -b dev_ipa+isntantid
pip install -e .

### 2. onediff_comfy_nodes
ln -s $(pwd)/onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
# or
#. cp -r onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
```

ipa插件安装参考 https://github.com/siliconflow/onediff/pull/814#issue-2242547294

**Comment by strint** [comment]
Too old to follow, free to reopen this.
