### ISSUE TITLE
请问一下，我现在想要加速sdxl版本的图生图，输入图像的分辨率是任意的，这样情况可以用oneflow加速吗？

### ISSUE THREAD

**Issue by cjt222** [siliconflow/onediff#866]

**Comment by strint** [comment]
可以试下这个多分辨率支持的例子，把它改成图生图的： https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/examples/text_to_image_sdxl.py#L101

参考图生图的 pipeline：https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/examples/image_to_image.py#L26

应该是支持的。
