### ISSUE TITLE
ComfyUI IPA: Failed to save graph file & Increased Time Consumption

### ISSUE THREAD

**Issue by xiecon** [siliconflow/onediff#869]
#### OneDiff git commit id
dev_ipa+isntantid
ef682691d55aa3963c4a06b64554e3292e8d95aa
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
version: 0.9.1.dev20240220+cu118
git_commit: 6621521
### The complete error message
20240510 20:10:37.106271 111212 cuda_stream.cpp:49] Runtime version 8.7 of cuDNN incompatible with compiletime version 8.9.
Failed to save graph file: ...ComfyUI/input/graphs/anyloraCheckpoint_bakedvaeBlessedFp16.safetensors_BaseModel/bs=1_UNetModel_fbe34f3e3f_3_f1f8a7f1ca61b188044db654a526065b05d40d2524e0d31165e22847fc11c900_0.9.1.dev20240220+cu118.graph! Can't pickle <class 'onediff.infer_compiler.transform.builtin_transform.<class 'register_comfy.CrossAttentionPatch.CrossAttentionPatch'>'>: attribute lookup <class 'register_comfy.CrossAttentionPatch.CrossAttentionPatch'> on onediff.infer_compiler.transform.builtin_transform failed

**Comment by xiecon** [comment]
Update version information:
- oneflow 0.9.1.dev20240509+cu118
- onediff commit accc466f68bafa376557b87959123fbd29c1a6d0
- ComfyUI_IPAdapter_plus commit d76bdbd2b59cb4164adb662359dc59b5aa213548

Same error message:
Building a graph for <class 'register_comfy.openaimodel.UNetModel'> ...
W20240513 11:36:00.435367 71267 cuda_stream.cpp:49] Runtime version 8.7 of cuDNN incompatible with compiletime version 8.9.
Failed to save graph file: /ComfyUI/input/graphs/anyloraCheckpoint_bakedvaeBlessedFp16.safetensors_BaseModel/UNetModel_304c305b00_3_f1f8a7f1ca61b188044db654a526065b05d40d2524e0d31165e22847fc11c900_0.9.1.dev20240509+cu118.graph! Can't pickle <class 'onediff.infer_compiler.transform.builtin_transform.<class 'register_comfy.CrossAttentionPatch.CrossAttentionPatch'>'>: attribute lookup <class 'register_comfy.CrossAttentionPatch.CrossAttentionPatch'> on onediff.infer_compiler.transform.builtin_transform failed

**Comment by xiecon** [comment]
在显卡A30上测试发现，在set_model_patch_replace这个函数运行时，onediff重写后的运行时间比原本长，原本的时间为：0.0009s，使用onediff后运行时间为：1.04s，耗时增加了很多。

**Comment by strint** [comment]
> Update version information:
> 
> * oneflow 0.9.1.dev20240509+cu118
> * onediff commit [accc466](https://github.com/siliconflow/onediff/commit/accc466f68bafa376557b87959123fbd29c1a6d0)
> * ComfyUI_IPAdapter_plus commit d76bdbd2b59cb4164adb662359dc59b5aa213548
> 
> Same error message: Building a graph for <class 'register_comfy.openaimodel.UNetModel'> ... W20240513 11:36:00.435367 71267 cuda_stream.cpp:49] Runtime version 8.7 of cuDNN incompatible with compiletime version 8.9. Failed to save graph file: /ComfyUI/input/graphs/anyloraCheckpoint_bakedvaeBlessedFp16.safetensors_BaseModel/UNetModel_304c305b00_3_f1f8a7f1ca61b188044db654a526065b05d40d2524e0d31165e22847fc11c900_0.9.1.dev20240509+cu118.graph! Can't pickle <class 'onediff.infer_compiler.transform.builtin_transform.<class 'register_comfy.CrossAttentionPatch.CrossAttentionPatch'>'>: attribute lookup <class 'register_comfy.CrossAttentionPatch.CrossAttentionPatch'> on onediff.infer_compiler.transform.builtin_transform failed

Save and load is fixed in https://github.com/siliconflow/onediff/pull/872

**Comment by xiecon** [comment]
The issue with ‘Failed to save graph file’ has indeed been fixed, but the problem of runtime duration has not been resolved, which is 1.95s.

**Comment by strint** [comment]
> The issue with ‘Failed to save graph file’ has indeed been fixed, but the problem of runtime duration has not been resolved, which is 1.95s.

Have you tried other device other than A30? We have no A30 at hand.

https://github.com/siliconflow/onediff/wiki/Compatibility-with-Nvidia-GPUs

**Comment by xiecon** [comment]
Time this code on the **A100**:
```
if not is_sdxl:
        start_time = time.perf_counter()
        for id in [1, 2, 4, 5, 7, 8]:  # id of input_blocks that have cross attention
            set_model_patch_replace(model, patch_kwargs, ("input", id))
            patch_kwargs["number"] += 1
        for id in [
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
        ]:  # id of output_blocks that have cross attention
            set_model_patch_replace(model, patch_kwargs, ("output", id))
            patch_kwargs["number"] += 1
        set_model_patch_replace(model, patch_kwargs, ("middle", 0))
        end_time = time.perf_counter()
        print(f"time:{end_time - start_time} s")
```
**with onediff: 1.2s
without onediff: 0.0009s**
Specifically, I am using ip-adapter-faceid-plusv2_sdxl.bin, with the insightface module.

**Comment by strint** [comment]
https://github.com/search?q=repo%3Asiliconflow%2Fonediff%20set_model_patch_replace&type=code

@ccssu  Is set_model_patch_replace cost a lot as expected?

**Comment by strint** [comment]
> I am using the latest onediff v1.1.0

Are you using the main branch of onediff?

And there is a  new update on ipadaptor is on the way: https://github.com/siliconflow/onediff/pull/879

**Comment by BradVidler** [comment]
Can confirm the graph is now being saved and working properly, however the "No module named x" errors still appear in the terminal.

**Comment by zhangyongyu** [comment]
> Can confirm the graph is now being saved and working properly, however the "No module named x" errors still appear in the terminal.

I have the same issue

**Comment by strint** [comment]
> Can confirm the graph is now being saved and working properly, however the "No module named x" errors still appear in the terminal.

@BradVidler @zhangyongyu Please paste the full error stack here to help debug
