### ISSUE TITLE
Incompatibility with PerturbedAtttentionGuidance (PAG)

### ISSUE THREAD

**Issue by wywywywy** [siliconflow/onediff#881]
### Describe the bug
Oneflow is not currently compatible with PerturbedAtttentionGuidance (PAG).

### Your environment
WSL2

#### OneDiff git commit id
0819aa41c8a910add96400265f3165f9d8d3634c

####  OneFlow version info
libibverbs not available, ibv_fork_init skipped
path: ['/home/user1/ai/ComfyUI/venv/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240510+cu118
git_commit: 7b5fa68
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Use the official PAG node in ComfyUI together with OneDiff's Load Checkpoint node

### The complete error message
```
!!! Exception during processing!!! Error: Sizes of tensors must match except in dimension 1. Got 8 and 16 is expected in dimension 0.

...

RuntimeError: Error: Sizes of tensors must match except in dimension 1. Got 8 and 16 is expected in dimension 0.
```

**Comment by nono-Sang** [comment]
Hi, can you provide your comfyui workflow (image or json)?

**Comment by wywywywy** [comment]
My apologies. Actually this seems to be a DeepCache issue, not a OneDiff issue. I typically use the "Load Checkpoint - OneDiff DeepCache" node so I'd assumed it's OneDiff related.

I'll close this now raise with DeepCache instead.
