### ISSUE TITLE
No module named 'onediff.infer_compiler.register'

### ISSUE THREAD

**Issue by Ralphhtt** [siliconflow/onediff#884]
### Describe the bug
Failed to load onediff_sd_webui_extentions
*** Error loading script: onediff.py
ImportError: cannot import name 'register' from 'onediff.infer_compiler' 

### Your environment
Ubuntu 22.04.4 LTS

#### OneDiff git commit id
d8a6a90

####  OneFlow version info
version: 0.9.1.dev20240515+cu118
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
cd onediff
python3 -m pip install -e .
python
\>\>\> from onediff.infer_compiler import oneflow_compile, register

### The complete error message
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'register' from 'onediff.infer_compiler' (/workspace/onediff/src/onediff/infer_compiler/__init__.py)

**Comment by strint** [comment]
got it, will fix it shortly

**Comment by strint** [comment]
@Ralphhtt Fixed in https://github.com/siliconflow/onediff/pull/885

**Comment by Ralphhtt** [comment]
It works, thx!
