### ISSUE TITLE
Cannot update ipadapter weight after compiling the graph in ComfyUI

### ISSUE THREAD

**Issue by Gutianpei** [siliconflow/onediff#892]
### Describe the bug
The workflow contains animatediff node and ipadapter node. After compiling the graph, changing the ipadapter weight will not work (the video is still generated with the weight when the graph first get compiled)

### Your environment
Ubuntu 20.04

#### OneDiff git commit id
2249010

####  OneFlow version info
libibverbs not available, ibv_fork_init skipped
path: ['/home/ubuntu/miniconda3/envs/comfy/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240420+cu121
git_commit: 665bcf8
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
[weight_ipadapter.json](https://github.com/siliconflow/onediff/files/15384254/weight_ipadapter.json)
After running the workflow, changing the weight in the node "Batch Value Schedule". It's expected to generate video according to the new weights but instead the video is never updated. One extreme case is set a weight to 100 after compiling, we should observe very unreasonable result.

### The complete error message
No error message noted.

### Additional context
Dependency version is followed this pr: https://github.com/siliconflow/onediff/pull/879
ComfyUI-AnimateDiff-Evolved commit id: f9e0343f4c4606ee6365a9af4a7e16118f1c45e1

**Comment by ccssu** [comment]
please try it test case @Gutianpei https://github.com/siliconflow/onediff/tree/3aad30db09d13a22c75fee1f11230fcb8562de6a/onediff_comfy_nodes/modules/oneflow/hijack_ipadapter_plus#ipadapter_weights
<img width="1041" alt="image" src="https://github.com/siliconflow/onediff/assets/109639975/9f05eef3-15a7-4053-a88b-e9a61d50d0c0">

**Comment by Gutianpei** [comment]
> please try it test case @Gutianpei https://github.com/siliconflow/onediff/tree/3aad30db09d13a22c75fee1f11230fcb8562de6a/onediff_comfy_nodes/modules/oneflow/hijack_ipadapter_plus#ipadapter_weights <img alt="image" width="1041" src="https://private-user-images.githubusercontent.com/109639975/333275462-9f05eef3-15a7-4053-a88b-e9a61d50d0c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODk3MTgsIm5iZiI6MTcxNjQ4OTQxOCwicGF0aCI6Ii8xMDk2Mzk5NzUvMzMzMjc1NDYyLTlmMDVlZWYzLTE1YTctNDA1My1hODhiLWU5YTYxZDUwZDBjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxODM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTEyZjFlYzU1ZTIyNGNlOGMzYzYwMjdmZTQ1ZjQyNjAyODNiYTU3MDdlMjliMWRmMDc5MGJmOTAzNTU1NmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QF323jpn-ECfXgPK4q1oD_1oQRI7aRPpxBPUxLlYJeg">

The link for the workflow is in the private repo, would you mind to share a public link? Thanks!

**Comment by Gutianpei** [comment]
I've tested that changing weights is working, thanks for the help! closing this issue
