### ISSUE TITLE
Found a small problem with the calculation

### ISSUE THREAD

**Issue by songh11** [siliconflow/onediff#893]
#### A clear and concise description of what the bug is.
我在看代码的时候，发现这里在求 scale 的时候，权重最大值并未取绝对值最大值，这里不考虑负数可能会导致负数超出的地方被截断吧，另外想请问下 weight_acc 是什么作用呢，一般不是只要 weight_scale 和 zero_point 就足够了

https://github.com/siliconflow/onediff/blob/2249010f8cfdbf2229bdf84134b5398541b2d6fe/onediff_comfy_nodes/modules/oneflow/utils/model_patcher.py#L470

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by hjchen2** [comment]
这里确实应该先计算weight的abs再计算max，此处确实存在bug。

weight_acc的作用是为了方便将输出的反量化操作与int8 matmul或者int8 conv进行融合，因为对于activation是非对称量化来说，最终需要的输出为 

<img width="644" alt="截屏2024-05-21 22 22 23" src="https://github.com/siliconflow/onediff/assets/13991173/8281c070-8571-46b2-89fa-b3a1bf49f7a3">

weight_acc即weight按k维累加的结果，可以提前计算得到。

**Comment by songh11** [comment]
> 这里确实应该先计算weight的abs再计算max，此处确实存在bug。
> 
> weight_acc的作用是为了方便将输出的反量化操作与int8 matmul或者int8 conv进行融合，因为对于activation是非对称量化来说，最终需要的输出为
> 
> <img alt="截屏2024-05-21 22 22 23" width="644" src="https://private-user-images.githubusercontent.com/13991173/332462689-8281c070-8571-46b2-89fa-b3a1bf49f7a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDA2ODgsIm5iZiI6MTcxNjM0MDM4OCwicGF0aCI6Ii8xMzk5MTE3My8zMzI0NjI2ODktODI4MWMwNzAtODU3MS00NmIyLTg5ZmEtYjNhMWJmNDlmN2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAxMTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYTE0YmQ4ZjQzNjg5M2MzZWEwNWUzZWE3NWMyNDBiYmIxMGMyMDA0ODQ4MjkyYzVhZjU5OWI3MzEzN2MyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a1-USxyexLnCYUcDgcGl1seB7vsXs33CEtiz9rC88OQ">
> weight_acc即weight按k维累加的结果，可以提前计算得到。



> 这里确实应该先计算weight的abs再计算max，此处确实存在bug。
> 
> weight_acc的作用是为了方便将输出的反量化操作与int8 matmul或者int8 conv进行融合，因为对于activation是非对称量化来说，最终需要的输出为
> 
> <img alt="截屏2024-05-21 22 22 23" width="644" src="https://private-user-images.githubusercontent.com/13991173/332462689-8281c070-8571-46b2-89fa-b3a1bf49f7a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDA2ODgsIm5iZiI6MTcxNjM0MDM4OCwicGF0aCI6Ii8xMzk5MTE3My8zMzI0NjI2ODktODI4MWMwNzAtODU3MS00NmIyLTg5ZmEtYjNhMWJmNDlmN2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAxMTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYTE0YmQ4ZjQzNjg5M2MzZWEwNWUzZWE3NWMyNDBiYmIxMGMyMDA0ODQ4MjkyYzVhZjU5OWI3MzEzN2MyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a1-USxyexLnCYUcDgcGl1seB7vsXs33CEtiz9rC88OQ">
> weight_acc即weight按k维累加的结果，可以提前计算得到。

感谢答复～
