### ISSUE TITLE
有计划支持ComfyUI的PuLID吗？

### ISSUE THREAD

**Issue by huan085128** [siliconflow/onediff#901]
ComfyUI-PuLID: https://github.com/cubiq/PuLID_ComfyUI
PuLID相比于InstantID效果更好 更自然，希望onediff后续可以支持

**Comment by strint** [comment]
好的，我们后面会考虑的。

如果社区有朋友感兴趣，也欢迎参考 InstantID 的加速来贡献 PuLID 的加速。

**Comment by ccssu** [comment]
> ComfyUI-PuLID: https://github.com/cubiq/PuLID_ComfyUI PuLID相比于InstantID效果更好 更自然，希望onediff后续可以支持

有个支持分支： 请 `git checkout -b dev_support_pulid_comfyui `

**Comment by strint** [comment]
PuLID support is merged. https://github.com/siliconflow/onediff/pull/965
