### ISSUE TITLE
"LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by liuchenbaidu** [siliconflow/onediff#903]
File "/usr/local/lib/python3.9/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

onediff Version: 1.1.0.dev202405220128

**Comment by CuddleSabe** [comment]
Maybe you should update your PyTorch edition.

**Comment by strint** [comment]
The problem seems in torch. Please follow @CuddleSabe 's suggestion.
