### ISSUE TITLE
是否支持Nvidia T4或者L4 GPU？

### ISSUE THREAD

**Issue by dawei03896** [siliconflow/onediff#906]
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by strint** [comment]
Tesla T4 is not  Ampere and Ada Lovelace architecture, so not much acceleration on it. 

Reference: 
- https://github.com/siliconflow/onediff/wiki/Compatibility-with-Nvidia-GPUs
- https://en.wikipedia.org/wiki/CUDA#:~:text=Compute%20Capability%2C%20GPU%20semiconductors%20and%20Nvidia%20GPU%20board%20products
