### ISSUE TITLE
[Feature request] image_to_image+contorlNet with onediff & deepcache

### ISSUE THREAD

**Issue by moonsunstars39** [siliconflow/onediff#910]
Hello,

It seems like there's no deepcache version of image to image in the examples.
Here's the text_to_image version:
onediff_diffusers_extensions/examples/text_to_image_deep_cache_sd.py

Is that possible to provide a image to image with ContorlNet example?

Thank you in advance.

**Comment by strint** [comment]
> there's no deepcache version of image to image in the examples.

Yes. deepcache is an experimental feature so we only put it in the text to image.

**Comment by strint** [comment]
> image to image with ContorlNet example

https://github.com/siliconflow/onediff/blob/main/onediff_diffusers_extensions/examples/image_to_image_controlnet.py
