### ISSUE TITLE
在析构函数中出现     AttributeError: 'NoneType' object has no attribute 'remove'

### ISSUE THREAD

**Issue by CuddleSabe** [siliconflow/onediff#913]
### How To Reproduce
1. Implement a kind of new unet's.   UpBlock.
2. transform_mgr.update_class_proxies({cls_key: UNet2D_SUPIROflow})
3. pipeline = compile_pipe(pipeline)

### The complete error message

Exception ignored in: <function Library.__del__ at 0x7f0f974a0280>
Traceback (most recent call last):
  File "/opt/conda/envs/tensorrt/lib/python3.10/site-packages/torch/library.py", line 136, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'

**Comment by CuddleSabe** [comment]
运算正常，结果也正常。就是在主程序都运行结束，进行析构的时候（一直到最后一行都是正常执行的）会报这个错误

**Comment by strint** [comment]
自定义模型的话，可以试下我们的新编译后端：
- 使用说明：https://github.com/siliconflow/onediff/tree/main/src/onediff/infer_compiler/backends/nexfort
- 例子： https://github.com/siliconflow/onediff/tree/main/onediff_diffusers_extensions/examples/pixart_alpha

不需要使用 transform_mgr.update_class_proxies({cls_key: UNet2D_SUPIROflow}) 这些替换代码的操作了
