### ISSUE TITLE
可以加速 ipadapter 吗？

### ISSUE THREAD

**Issue by zhangyongyu** [siliconflow/onediff#918]
### Describe the bug
workflow 加入 ipadapter 后加速时效

#### OneDiff git commit id
1.1.0.dev202405230127

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
path: ['/home/ubuntu/miniconda3/envs/cf/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240520+cu121
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):
[workflow.json](https://github.com/siliconflow/onediff/files/15470918/workflow.json)

测试发现无法加速带 ipadater 的 workflow

**Comment by strint** [comment]
这里有关于  ipadapter 的用例可以参考下：https://github.com/siliconflow/onediff/tree/main/onediff_comfy_nodes#ipadapter

**Comment by ccssu** [comment]
👋 Hello @zhangyongyu  Thanks for providing detailed information about the issue you're encountering.
Fixed onediff bug,  https://github.com/siliconflow/onediff/pull/887 Test installation , please try it as follows：
```shell
# install onediff
git clone https://github.com/siliconflow/onediff.git
cd onediff && git chekout add_model_graph_cache_patch
pip install -e .
​
# install onediff_comfy_nodes
ln -s $(pwd)/onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
# or
# cp -r onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
``
