### ISSUE TITLE
why is getting me IMPORT FAILED node error in comfyui

### ISSUE THREAD

**Issue by nanaj96** [siliconflow/onediff#928]
![image](https://github.com/siliconflow/onediff/assets/120275578/6901ce9f-9c05-4249-aceb-a326b4792239)

**Comment by nanaj96** [comment]
![image](https://github.com/siliconflow/onediff/assets/120275578/ee2e3d45-c3b0-4fb4-88c2-093c7d2edbd2)

**Comment by nanaj96** [comment]
i follow your all installation instructions but it is not working 
![image](https://github.com/siliconflow/onediff/assets/120275578/5d47886c-f900-4146-a750-16c106862d57)

**Comment by nanaj96** [comment]
can you please tell me what i missing here?

**Comment by nanaj96** [comment]
can you please help me with this issue?

**Comment by al-swaiti** [comment]
i have two eniourenemnt one using python 3.10 and the other 3.12
its work on 3.10 but failed to import on 3.12 , !!!
try to downgrade to 3.10

**Comment by strint** [comment]
why are you using `torch compile` here?

**Comment by strint** [comment]
@nanaj96 Are you trying to set up the enterprise edition?


enterprise edition needs a license key. Maybe you can only run with the community Edition.
