### ISSUE TITLE
套壳LLM网站无法接入siliconflow.

### ISSUE THREAD

**Issue by onlyhuman028** [siliconflow/onediff#929]
套壳LLM网站无法接入siliconflow.

一、以下网站可以

https://openrouter.ai/api/
sk-XXX
qwen/qwen-110b-chat

注：兼容openai协议

二、siliconflow.网站不可以

两个都试了

https://api.siliconflow.cn/v1
https://api.siliconflow.cn/v1/chat/completions

alibaba/Qwen1.5-110B-Chat

**Comment by strint** [comment]
> 套壳LLM网站无法接入siliconflow.
> 
> 一、以下网站可以
> 
> https://openrouter.ai/api/ sk-XXX qwen/qwen-110b-chat
> 
> 注：兼容openai协议
> 
> 二、siliconflow.网站不可以
> 
> 两个都试了
> 
> https://api.siliconflow.cn/v1 https://api.siliconflow.cn/v1/chat/completions
> 
> alibaba/Qwen1.5-110B-Chat

收到，这是 cloud 相关的，已经转给相关同事。
