### ISSUE TITLE
Import Failed on ComfyUI Load

### ISSUE THREAD

**Issue by mike-rowley** [siliconflow/onediff#934]
#### A clear and concise description of what the bug is.
I am receiving this error on ComfyUI startup preventing the import of OneDiff
Traceback (most recent call last):
  File "/mnt/wf/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/wf/ComfyUI/custom_nodes/onediff_comfy_nodes/__init__.py", line 3, in <module>
    from ._nodes import (ModelSpeedup, OneDiffApplyModelBooster,
  File "/mnt/wf/ComfyUI/custom_nodes/onediff_comfy_nodes/_nodes.py", line 10, in <module>
    from .modules.oneflow import BasicOneFlowBoosterExecutor
  File "/mnt/wf/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/__init__.py", line 1, in <module>
    from .config import _USE_UNET_INT8, ONEDIFF_QUANTIZED_OPTIMIZED_MODELS
  File "/mnt/wf/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/config.py", line 6, in <module>
    from onediff.infer_compiler.utils import is_community_version
ModuleNotFoundError: No module named 'onediff.infer_compiler.utils'

Cannot import /mnt/wf/ComfyUI/custom_nodes/onediff_comfy_nodes module for custom nodes: No module named 'onediff.infer_compiler.utils'

### Your environment
Ubuntu 22.04.4 LTS

#### OneDiff git commit id
f3f7e4e5e1f464ad1ccab61d7498f895012fb84a

####  OneFlow version info
path: ['/mnt/wf/ComfyUI/venv/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240604+cu118
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Occurs on regular load of ComfyUI after installing OneDiff Nodes

### The complete error message
Message is above

### Additional context
I have tried the install instructions and searched existing issues, mine seems to be the same as https://github.com/siliconflow/onediff/issues/884 except in ComfyUI

**Comment by ReyJ94** [comment]
me too. Cannot find a way to fix it. I followed all intructions. I'm on windows.

**Comment by mp3pintyo** [comment]
You have to use WSL under windows and then it works.

**Comment by ReyJ94** [comment]
> You have to use WSL under windows and then it works.

Yeah but wsl is bothersome, since it takes out ram. If i'm running everything on windows and only onediff on wsl, i'm wasting precious RAM. Also now that i'm thinking about it would i even need to run the entire comfy in wsl too ?

**Comment by mp3pintyo** [comment]
Yes, it should be run there.

**Comment by mike-rowley** [comment]
I am on Ubuntu, any suggestions?

**Comment by lijunliangTG** [comment]
您可以尝试将OneDiff版本更新到最新版本，然后运行 
 ``` 
cd path/to/onediff
pip install -e . 
cp -r onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
```

**Comment by strint** [comment]
@mike-rowley a copy is needed here, please follow @lijunliangTG 's solution and have a try.
