### ISSUE TITLE
comfyui seems like not use onediff

### ISSUE THREAD

**Issue by songh11** [siliconflow/onediff#935]
### Describe the bug
我按照 cumfyui 装好环境并创建软链接后，运行 comfyui 的 main.py 后打开页面 load checkpoint 时未显示 onediff，测速也和之前一样，感觉没有用到 onediff

### Your environment
Ubuntu 18.04

#### OneDiff git commit id
a604cfb2ec6607bc2c89868a9cde8921471883a3

####  OneFlow version info
path: ['/opt/conda/envs/onediff/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240604+cu118
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
在最新的 Comfyui 上运行即可

### Additional context

<img width="816" alt="image" src="https://github.com/siliconflow/onediff/assets/75419275/b4827410-8af1-4900-8e69-6ed84f0711bd">
<img width="426" alt="image" src="https://github.com/siliconflow/onediff/assets/75419275/da33f489-8d6b-4762-8d9d-f9a217a4b9c6">

**Comment by BradVidler** [comment]
You need to use the OneDiff load checkpoint nodes, not comfyui node.

**Comment by songh11** [comment]
> You need to use the OneDiff load checkpoint nodes, not comfyui node.

感谢，已经可以了，我以为是自动替换的
