### ISSUE TITLE
ComfyUI中Lora未生效

### ISSUE THREAD

**Issue by Dylanooo** [siliconflow/onediff#936]
复现步骤：
1.首次工作流中使用OneDiffCheckpointLoaderSimple加载ckpt,且不加载任何Lora
2.修改工作流，增加LoRALoader节点，加载任一Lora
3.LoRA未生效

**Comment by CuddleSabe** [comment]
编译后应该就没法fuse lora了，应该在编译前把lora的权重融合进unet

**Comment by Dylanooo** [comment]
> 编译后应该就没法fuse lora了，应该在编译前把lora的权重融合进unet

我试过，也可以，只不过需要先切换一下ckpt，然后再切回来，lora就生效了

**Comment by ccssu** [comment]
> 复现步骤： 1.首次工作流中使用OneDiffCheckpointLoaderSimple加载ckpt,且不加载任何Lora 2.修改工作流，增加LoRALoader节点，加载任一Lora 3.LoRA未生效

Hello, 👋感谢反馈， 这个问题已经修复（pr:https://github.com/siliconflow/onediff/pull/967) @Dylanooo @CuddleSabe 

下面video是根据反馈修复后的结果：

https://github.com/siliconflow/onediff/assets/109639975/9bee93d5-9f27-48d0-b28b-fc8b064e2575
