### ISSUE TITLE
StableVideoDiffusionPipeline 加速 V100 能执行成功，A30 执行报错

### ISSUE THREAD

**Issue by lss15151161** [siliconflow/onediff#955]
环境：
python3.9 
torch2.1.0+cu121
onediff 1.2.0.dev202406150129
onediffx 1.2.0.dev202406150129
oneflow 0.9.1.dev20240615+cu121
说明：V100上测试观察，现存最大需要16G，不超过A30的24G现存。应该不是显存不够
报错：
<img width="1726" alt="image" src="https://github.com/siliconflow/onediff/assets/34617721/707c6ec0-ba4f-42ac-9a06-636bb1717920">

**Comment by lijunliangTG** [comment]
能否说明下复现方式，以及采用的模型

**Comment by lijunliangTG** [comment]
您使用的权重是什么？我没有在HF上找到```cm_rotation_v1``` 权重

**Comment by lss15151161** [comment]
> 您使用的权重是什么？我没有在HF上找到`cm_rotation_v1` 权重

是的，权重是我自己重新微调的。不过没有优化的模型用fp16是没问题的，V100上也没有问题。所以应该不是权重的原因。您可以直接用hf上的开源权重就行。目前已定位到是 UNetSpatioTemporalConditionModel 模型导致的溢出

**Comment by lijunliangTG** [comment]
![image](https://github.com/siliconflow/onediff/assets/117806079/c2d94c61-a349-4cda-9a25-61cb86dc0f13)
我采用这个 ``` stabilityai/stable-video-diffusion-img2vid-xt ``` 模型权重可以在3090上正常运行，峰值显存占用接近24G。

torch 版本 2.3.0+cu121
python 3.10
onediff 1.2.0.dev1

**Comment by lss15151161** [comment]
> ![image](https://private-user-images.githubusercontent.com/117806079/340656230-c2d94c61-a349-4cda-9a25-61cb86dc0f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzgyNDEsIm5iZiI6MTcxODc3Nzk0MSwicGF0aCI6Ii8xMTc4MDYwNzkvMzQwNjU2MjMwLWMyZDk0YzYxLWEzNDktNGNkYS05YTI1LTYxY2I4NmRjMGYxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwNjE5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTk2MTJhOWYzYmE3OGY2Y2RjMTI1MzIyNGUzZjYwZTZiMjEyZjViNzU4NGU3ZGU1YmY5OTIyNTUyOWU5MDU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lbedcCrHmO6vKeyENVCz-cojQjUnfPE_Xn7do_bHSMQ) 我采用这个 `stabilityai/stable-video-diffusion-img2vid-xt` 模型权重可以在3090上正常运行，峰值显存占用接近24G。
> 
> torch 版本 2.3.0+cu121 python 3.10 onediff 1.2.0.dev1

版本应该没问题，就是在A100， A30上会有问题，V100测试也可以

**Comment by lijunliangTG** [comment]
![image](https://github.com/siliconflow/onediff/assets/117806079/46df953c-c785-48fa-a06e-c6cb77c7add0)
我在A100上可以正常运行，可以重装一下OneDiff和OneFlow  https://github.com/siliconflow/onediff/blob/main/README.md#optional-install-oneflow

**Comment by lss15151161** [comment]
> ![image](https://private-user-images.githubusercontent.com/117806079/341242868-46df953c-c785-48fa-a06e-c6cb77c7add0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTAzMTUsIm5iZiI6MTcxODg1MDAxNSwicGF0aCI6Ii8xMTc4MDYwNzkvMzQxMjQyODY4LTQ2ZGY5NTNjLWM3ODUtNDhmYS1hMDZlLWM2Y2I3N2M3YWRkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwMjIwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWQ3NzMzZjA2ZTI3NTA1MTI5Y2Y1ZmNiODhlZTFkMDU1NDhhNGNiZjFhYmU2YjY5NTU3NmI4NjM2YmFiNTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bEyjsnj0U92kMEtEKkzDHnKUzbqHHU3QlPGCgVvCJ5E) 我在A100上可以正常运行，可以重装一下OneDiff和OneFlow https://github.com/siliconflow/onediff/blob/main/README.md#optional-install-oneflow

生成结果是对的吗

**Comment by lss15151161** [comment]
> ![image](https://private-user-images.githubusercontent.com/117806079/341242868-46df953c-c785-48fa-a06e-c6cb77c7add0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjkzMzYsIm5iZiI6MTcxODg2OTAzNiwicGF0aCI6Ii8xMTc4MDYwNzkvMzQxMjQyODY4LTQ2ZGY5NTNjLWM3ODUtNDhmYS1hMDZlLWM2Y2I3N2M3YWRkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwNzM3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGZkMDAzOTczZWZiMjc1YTliNzRiNmQ2OTQwZGZmZTFjNDYzY2Y3OWNlN2VkOWM3MTg2MWIyZmE4MjhlZGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O7D9eHo1EAw4eddjbcreZR8DkegtcF_RWxfXidU-SW8) 我在A100上可以正常运行，可以重装一下OneDiff和OneFlow https://github.com/siliconflow/onediff/blob/main/README.md#optional-install-oneflow

我也可以执行成功，但是生成的视频是全黑的图片

**Comment by lijunliangTG** [comment]
我也遇到了这个问题，现在还在排查中

**Comment by lss15151161** [comment]
> 我也遇到了这个问题，现在还在排查中

原因应该是unet结果全为nan导致的。但是奇怪的是在V100上是正常。可以见这条issue：https://github.com/siliconflow/onediff/issues

**Comment by lss15151161** [comment]
> 我也遇到了这个问题，现在还在排查中

您好，请问有排查出问题吗

**Comment by lijunliangTG** [comment]
您好，目前已经成功复现，还在排查问题中

**Comment by lijunliangTG** [comment]
``` export ONEFLOW_ATTENTION_ALLOW_HALF_PRECISION_ACCUMULATION=False  ```您可以通过设置这个环境变量来正常出图

**Comment by lijunliangTG** [comment]
您可以先尝试 
``` export ONEFLOW_ATTENTION_ALLOW_HALF_PRECISION_ACCUMULATION=False  ```
这样设置之后可以正常出图，具体原因还在排查中
