### ISSUE TITLE
开启onediff优化后，A100上unet执行结果为nan，但是V100上unet计算结果正常

### ISSUE THREAD

**Issue by lss15151161** [siliconflow/onediff#958]
### Describe the bug
StableVideoDiffusionPipeline 开启onediff优化后，A100上unet执行结果为nan，V100上unet计算结果正常

### Your environment
debian

#### OneDiff git commit id
onediff                    0.13.0.dev202403280124
onediffx                   0.13.0.dev202403280124

####  OneFlow version info
oneflow                    0.9.1.dev20240615+cu118

### How To Reproduce
Steps to reproduce the behavior(code or script):

### The complete error message
![Uploading image.png…]()

**Comment by lijunliangTG** [comment]
请您提供一下复现该行为的代码。您可以尝试先更新OneDiff版本到最新版本。

**Comment by lss15151161** [comment]
> 请您提供一下复现该行为的代码。您可以尝试先更新OneDiff版本到最新版本。
您好，感谢回复，升级到最新版测试仍然有同样问题，复现代码如下。但是模型权重太大不好上传，您用开源权重应该也可以复现

import os
import torch
import torch.nn as nn
import json
import numpy as np
from diffusers.models import UNetSpatioTemporalConditionModel
import json
from onediff.infer_compiler import oneflow_compile

if __name__ == "__main__":
    unet_model_path = './xxx/unet'
    
    device = "cuda"
    m_torch = UNetSpatioTemporalConditionModel.from_pretrained(unet_model_path, torch_dtype=torch.float16).cuda().eval()

    m_oneflow = oneflow_compile(m_torch)

    # 创建输入
    with open("./mock_unet_input_a100.txt", 'r') as f:
        mock_input = json.load(f)
        latent_model_input = torch.tensor(mock_input['latent_model_input']).half().cuda()
        t = torch.tensor(mock_input['t']).cuda()
        image_embeddings = torch.tensor(mock_input["image_embeddings"]).half().cuda()
        added_time_ids = torch.tensor(mock_input["added_time_ids"]).half().cuda()

    with torch.no_grad():
        out = m_torch(latent_model_input, t, image_embeddings, added_time_ids, return_dict=False)
    print(out[0][0,0,0,0,:5])

    with torch.no_grad():
        out = m_oneflow(latent_model_input, t, image_embeddings, added_time_ids, return_dict=False)
    print(out[0][0,0,0,0,:5])

[mock_unet_input_a100.txt](https://github.com/user-attachments/files/15895226/mock_unet_input_a100.txt)

**Comment by lijunliangTG** [comment]
您可以提供huggingface的模型名来帮助我复现您的错误

**Comment by lss15151161** [comment]
> 您可以提供huggingface的模型名来帮助我复现您的错误

这个模型，用的这里的模型，试了fp16和fp32两种权重，加载权重的时候都使用fp16加载。 结果都是nan，https://huggingface.co/stabilityai/stable-video-diffusion-img2vid/tree/main/unet

<img width="863" alt="image" src="https://github.com/siliconflow/onediff/assets/34617721/a0d5acee-ad0f-41b7-a5d4-134c0573315f">
<img width="863" alt="image" src="https://github.com/siliconflow/onediff/assets/34617721/a0d5acee-ad0f-41b7-a5d4-134c0573315f">
![Uploading image.png…]()

**Comment by lss15151161** [comment]
> > 您可以提供huggingface的模型名来帮助我复现您的错误
> 
> 这个模型，用的这里的模型，试了fp16和fp32两种权重，加载权重的时候都使用fp16加载。 结果都是nan，https://huggingface.co/stabilityai/stable-video-diffusion-img2vid/tree/main/unet
> 
> <img alt="image" width="863" src="https://private-user-images.githubusercontent.com/34617721/341300014-a0d5acee-ad0f-41b7-a5d4-134c0573315f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjYwODAsIm5iZiI6MTcxODg2NTc4MCwicGF0aCI6Ii8zNDYxNzcyMS8zNDEzMDAwMTQtYTBkNWFjZWUtYWQwZi00MWI3LWE1ZDQtMTM0YzA1NzMzMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA2NDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YTVhM2NkOWJjMzNmM2QyMmM3Nzk4NjU5ZjkyYmZlYjBhMjg1OWM2ZTNjODEzODdlZTVkNjIyNmJhNzczZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B3jdKj84mR9Elhmx394UD3yAwD87IfZzMNTUseBWbuQ"> ![Uploading image.png…]()



> > 您可以提供huggingface的模型名来帮助我复现您的错误
> 
> 这个模型，用的这里的模型，试了fp16和fp32两种权重，加载权重的时候都使用fp16加载。 结果都是nan，https://huggingface.co/stabilityai/stable-video-diffusion-img2vid/tree/main/unet
> 
> <img alt="image" width="863" src="https://private-user-images.githubusercontent.com/34617721/341300014-a0d5acee-ad0f-41b7-a5d4-134c0573315f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjYwODAsIm5iZiI6MTcxODg2NTc4MCwicGF0aCI6Ii8zNDYxNzcyMS8zNDEzMDAwMTQtYTBkNWFjZWUtYWQwZi00MWI3LWE1ZDQtMTM0YzA1NzMzMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA2NDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YTVhM2NkOWJjMzNmM2QyMmM3Nzk4NjU5ZjkyYmZlYjBhMjg1OWM2ZTNjODEzODdlZTVkNjIyNmJhNzczZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B3jdKj84mR9Elhmx394UD3yAwD87IfZzMNTUseBWbuQ"> ![Uploading image.png…]()

A10，A30，A100都有同样的问题

**Comment by strint** [comment]
@lss15151161 

Try this:

```
export ONEFLOW_ATTENTION_ALLOW_HALF_PRECISION_ACCUMULATION=False
```

**Comment by strint** [comment]
@lss15151161 Please have a try.

**Comment by lss15151161** [comment]
> @lss15151161 Please have a try.

thx，this solved my problem~
