### ISSUE TITLE
Enterprise quant has problem

### ISSUE THREAD

**Issue by CuddleSabe** [siliconflow/onediff#969]
InferDataType Failed. Expected kFloat16, but got kInt8

ERROR [2024-06-20 17:46:58] /root/picasso/韩昊天/onediff/src/onediff/infer_compiler/oneflow/utils.py:23 - Exception in forward: e=RuntimeError('InferDataType Failed. Expected kFloat16, but got kInt8\n  File "oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 144, in Dispatch<oneflow::one::Tensor>\n    Dispatch<TensorTuple>(op_expr, inputs, ctx)\n  File "oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 135, in Dispatch<oneflow::one::TensorTuple>\n    Dispatch(op_expr, inputs, outputs.get(), ctx)\n  File "oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 103, in Apply\n    internal_->Apply(op_expr, inputs, outputs, ctx)\n  File "oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp", line 856, in ApplyImpl\n    infer_ctx->AddAndInferGlobalOp(*op_conf)\n  File "oneflow/core/job/job_build_and_infer_ctx.cpp", line 573, in AddAndInferOp\n    op->InferLogicalOutBlobDescsIf()\n  File "oneflow/core/operator/operator.cpp", line 329, in InferLogicalOutBlobDescsIf\n    InferLogicalOutBlobDescs(BlobDesc4BnInOp, *JUST(GetOpParallelDesc()))\n  File "oneflow/core/operator/user_op.cpp", line 772, in InferLogicalOutBlobDescs\n    val_->data_type_infer_fn(&infer_ctx)\n  File "oneflow/user/ops/fused_matmul_bias_op.cpp", line 66, in InferDataType4MatmulBias\n    CHECK_EQ_OR_RETURN(in_desc.data_type(), first_in_desc.data_type())\nError Type: oneflow.ErrorProto.check_failed_error')

**Comment by strint** [comment]
What example are you running with?

It seems a fp16 pipeline is running with int8.

**Comment by strint** [comment]
@CuddleSabe

**Comment by strint** [comment]
too old to follow, feel free to reopen it.
