### ISSUE TITLE
It's weird if both instant_id and ip_adapter are enabled in comfyui

### ISSUE THREAD

**Issue by Remember2015** [siliconflow/onediff#970]
#### Only InstantID
![img_v3_02c2_ca543abf-64f0-48b5-b3d3-375178f9185g](https://github.com/siliconflow/onediff/assets/575884/9c3fb9a7-5d90-4543-8891-24465f0708d8)

#### Only IPAdapter
![img_v3_02c2_138273e7-d112-4928-b80a-41c58406286g](https://github.com/siliconflow/onediff/assets/575884/8ad15994-df56-4cda-8ca4-c4aebdc25b65)

#### Both
![img_v3_02c2_461958be-809a-4992-82b6-674c56167f3g](https://github.com/siliconflow/onediff/assets/575884/c658fa75-8b6d-420f-957f-2fe9627c05a4)
The image is blurry and the girl looks like fake ones

### Both with onediff disabled
![image](https://github.com/siliconflow/onediff/assets/575884/27c405ba-24e3-4614-82f1-67282d283b1c)

#### OS
* Ubuntu 22.04

#### OneDiff git commit id
* latest version

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
```
libibverbs not available, ibv_fork_init skipped
path: ['/root/test/venv/lib/python3.11/site-packages/oneflow']
version: 0.9.1.dev20240616+cu121
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```
### How To Reproduce
Steps to reproduce the behavior(code or script):
download sample json from [onediff](https://github.com/cubiq/ComfyUI_InstantID/blob/main/examples/InstantID_IPAdapter.json)
then:
1. load model by onediff
2. load controlnet - canny
3. enable InstantID
4. enable IPAdapter Advanced (params: linear, average, V Only)
5. set IPAdapter Model: plus(high strength)

**Comment by lijunliangTG** [comment]
Could you please provide the git commit and comfyui versions of the corresponding software and the flow chart of comfyui? So that I can reproduce your error reporting process.

**Comment by strint** [comment]
too old to follow, feel free to reopen it @Remember2015
