### ISSUE TITLE
How to use int8 for onediff Controlnet

### ISSUE THREAD

**Issue by cchen-reese** [siliconflow/onediff#979]

**Comment by cchen-reese** [comment]
> only enterprise edition can use int8
ok, thanks.

**Comment by strint** [comment]
int8 is not good to be compatible with Lora switching,  and quantization is model related. It is not easy to use for most of the users.

If you have a lot of traffic on a single stable model, you are fit for int8. So we put it into the enterprise edition.

**Comment by cchen-reese** [comment]
> int8 is not good to be compatible with Lora switching, and quantization is model related. It is not easy to use for most of the users.
> 
> If you have a lot of traffic on a single stable model, you are fit for int8. So we put it into the enterprise edition.
Thank you for your reply. By the way, do you see any degradation in the quality of image generation, under the usage of int8?

**Comment by strint** [comment]
> > int8 is not good to be compatible with Lora switching, and quantization is model related. It is not easy to use for most of the users.
> > If you have a lot of traffic on a single stable model, you are fit for int8. So we put it into the enterprise edition.
> 
> Thank you for your reply. By the way, do you see any degradation in the quality of image generation, under the usage of int8?

https://github.com/siliconflow/onediff?tab=readme-ov-file#onediff-quality-evaluation
