### ISSUE TITLE
How to TRAIN the int8 quant model?

### ISSUE THREAD

**Issue by CuddleSabe** [siliconflow/onediff#983]
![企业微信截图_17191961315895](https://github.com/siliconflow/onediff/assets/61224076/884dc711-2a71-4ee9-b9f2-dd90e4f87833)
测试int8量化发现效果会有一些损失，请问我们后续如何在int8上进行微调以弥补损失？

**Comment by CuddleSabe** [comment]
@strint

**Comment by strint** [comment]
@CuddleSabe 你在试用企业版么

**Comment by CuddleSabe** [comment]
> @CuddleSabe 你在试用企业版么

不是试用，公司用了比较久了

**Comment by strint** [comment]
> > @CuddleSabe 你在试用企业版么
> 
> 不是试用，公司用了比较久了

@CuddleSabe 有微信之内的联系方式我们看看怎么样。直接看这个 issue 没有完全明白

**Comment by strint** [comment]
int8 这块当前只支持了推理，是没有支持训练的
