### ISSUE TITLE
oneflow_compile(unet) failed

### ISSUE THREAD

**Issue by liyandong001** [siliconflow/onediff#995]
#### OS 
ubuntu20.04

####  OneFlow version info if you have installed oneflow
Run `python -m oneflow --doctor` and paste it here.

path: ['/usr/local/lib/python3.10/dist-packages/oneflow']
version: 0.9.1.dev20240515+cu118
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):

### Additional context

ERROR [2024-07-03 07:01:29] /usr/local/lib/python3.10/dist-packages/onediff/infer_compiler/backends/oneflow/deployable_module.py:38 - Exception in forward: e=KeyError(oneflow.float16)

**Comment by strint** [comment]
What example are you running?

**Comment by liyandong001** [comment]
闰土
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siliconflow/onediff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月5日(星期五) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siliconflow/onediff] oneflow_compile(unet) failed (Issue #995)





 
What example are you running?

**Comment by liyandong001** [comment]
May I ask if there is a conclusion?

**Comment by strint** [comment]
> May I ask if there is a conclusion?

More context is needed. What is the example you are running and what is the HF diffusers version.

**Comment by strint** [comment]
@liyandong001 Maybe you are compile some custom model?

**Comment by liyandong001** [comment]
I found the reason, it was caused by using xforms at the same time

**Comment by strint** [comment]
> I found the reason, it was caused by using xforms at the same time

OK. xformers can't be compiled by onediff so it needs to be disabled.
